/* Building-services pages (parent: Healthcare MEP). Written from the scope the client confirmed:
 * medical gas, HVAC, fire protection and nurse call installation. Each page explains the service in
 * general terms and states only that EGC installs / provides it. */
const SH = 'healthcare-contractor/radiation-shielding';
const MEP = 'healthcare-contractor/healthcare-mep';

export const BUILDING = [
  {
    key: 'medicalGas',
    segment: 'healthcare-contractor/medical-gas-systems',
    parent: 'mep',
    group: 'building',
    icon: 'gas',
    image: null,
    related: ['hvac', 'fireProtection', 'nurseCall', 'hospitalFitOut'],
    en: {
      name: 'Medical Gas Systems',
      title: 'Medical Gas Pipeline Installation in Saudi Arabia | EGC',
      description: 'Medical gas pipeline installation for hospitals in Saudi Arabia: oxygen, medical air and vacuum, with outlets, valves and alarms, tested before use.',
      short: 'Oxygen, medical air and vacuum pipework, outlets, valves and alarms.',
      h1: 'Medical gas pipeline systems for hospitals in Saudi Arabia',
      lead: 'We install the pipework that carries oxygen, medical air and vacuum to the bedside and the operating room, with the outlets, valves and alarms that make it safe to use, and test it before it goes into service.',
      flow: {
        title: 'From source to bedside',
        steps: ['Source equipment supplies the gas', 'Pipework carries it through the building', 'Valves let each zone be isolated', 'Outlets deliver it at the point of care'],
      },
      answerTitle: 'What a medical gas system is',
      answer: [
        'A medical gas pipeline system delivers gases such as oxygen and medical air, and suction (vacuum), from a central source to terminal units at the bedside, in operating rooms and in treatment areas, so staff do not depend on cylinders at the point of care. A system typically comprises the source equipment, copper pipework run through ceilings and walls, isolation valves and area valve service units that let a zone be shut off safely, terminal outlets at each point of use and alarm panels that warn when pressure leaves its limits. Because patients depend on these gases, installation is controlled: pipework must be clean and correctly identified, joints properly made, and every system tested, purged and verified before use. EGC installs medical gas pipelines as part of its healthcare MEP works, coordinating routes with ceilings, shielding and other services so that each outlet lands where the clinical team needs it.',
        `Medical gas is one part of [healthcare MEP](${MEP}); it is planned together with [HVAC](healthcare-contractor/healthcare-hvac), [fire protection](healthcare-contractor/fire-protection) and, in imaging rooms, the [shielding](${SH}).`,
      ],
      table: {
        title: 'Parts of a medical gas system',
        head: ['Part', 'What it does'],
        rows: [
          ['Source equipment', 'Provides the gas or vacuum for the whole system'],
          ['Pipework', 'Carries each gas to the departments that use it'],
          ['Isolation valves and area valve service units', 'Let a zone be shut off safely for maintenance or an emergency'],
          ['Terminal outlets', 'Deliver the gas or vacuum at the bedside, pendant or ceiling point'],
          ['Alarm panels', 'Warn staff when pressure or supply leaves its limits'],
        ],
      },
      usesTitle: 'Where medical gas is installed',
      uses: ['Patient rooms and wards', 'Operating theatres', 'Intensive care and high-dependency units', 'Emergency and resuscitation areas', 'Delivery rooms and neonatal units'],
      deliverTitle: 'What we install',
      deliver: [
        'Oxygen, medical air and vacuum pipework',
        'Terminal outlets and bedhead or pendant connections',
        'Isolation valves and area valve service units',
        'Alarm and monitoring panels',
        'Identification and labelling of pipework',
        'Pressure testing, purging and commissioning',
      ],
      process: [
        { t: 'Agree demand and routes', d: 'We work from the design and the clinical team’s outlet positions.' },
        { t: 'Install pipework and outlets', d: 'Pipework, valves and outlets are installed and identified.' },
        { t: 'Test, purge and verify', d: 'Every system is pressure-tested and purged before use.' },
        { t: 'Commission and hand over', d: 'Alarms are commissioned and records are handed over.' },
      ],
      ctaTitle: 'Need medical gas installed?',
      ctaText: 'Send us the design and the outlet schedule and we will respond with a proposal.',
    },
    ar: {
      name: 'الغازات الطبية',
      title: 'تركيب أنظمة الغازات الطبية في السعودية | EGC',
      description: 'تركيب شبكات الغازات الطبية للمستشفيات في السعودية: الأكسجين والهواء الطبي والتفريغ، بمخارج وصمامات وإنذارات، تُختبر قبل التشغيل.',
      short: 'شبكات الأكسجين والهواء الطبي والتفريغ والمخارج والصمامات والإنذارات.',
      h1: 'أنظمة الغازات الطبية للمستشفيات في السعودية',
      lead: 'نركّب الشبكات التي تنقل الأكسجين والهواء الطبي والتفريغ إلى جانب السرير وغرفة العمليات، بالمخارج والصمامات والإنذارات التي تجعل استخدامها آمنًا، ونختبرها قبل دخولها الخدمة.',
      flow: {
        title: 'من المصدر إلى جانب السرير',
        steps: ['تزوّد معدات المصدر بالغاز', 'تنقله الأنابيب عبر المبنى', 'تتيح الصمامات عزل كل منطقة', 'تسلّمه المخارج عند نقطة الرعاية'],
      },
      answerTitle: 'ما هو نظام الغازات الطبية',
      answer: [
        'تنقل شبكة الغازات الطبية غازات مثل الأكسجين والهواء الطبي، وكذلك الشفط (التفريغ)، من مصدر مركزي إلى مخارج عند السرير وفي غرف العمليات ومناطق العلاج، فلا يعتمد الطاقم على الأسطوانات عند نقطة الرعاية. وتتكون الشبكة عادةً من معدات المصدر وأنابيب نحاسية تمر عبر الأسقف والجدران وصمامات عزل ووحدات صمامات للمناطق تتيح عزل منطقة بأمان ومخارج عند كل نقطة استخدام ولوحات إنذار تنبّه عند خروج الضغط عن حدوده. ولأن المرضى يعتمدون على هذه الغازات فإن التركيب منضبط: يجب أن تكون الأنابيب نظيفة ومحددة الهوية بصورة صحيحة، والوصلات محكمة، وأن يُختبر كل نظام ويُنقَّى ويُتحقق منه قبل الاستخدام. وتركّب EGC شبكات الغازات الطبية ضمن أعمالها الكهروميكانيكية الطبية، وتنسّق المسارات مع الأسقف والتدريع والخدمات الأخرى لتقع كل نقطة حيث يحتاجها الفريق السريري.',
        `والغازات الطبية جزء من [الأعمال الكهروميكانيكية الطبية](${MEP})؛ وتُخطَّط مع [التكييف والتهوية](healthcare-contractor/healthcare-hvac) و[الحماية من الحريق](healthcare-contractor/fire-protection)، ومع [التدريع](${SH}) في غرف التصوير.`,
      ],
      table: {
        title: 'أجزاء نظام الغازات الطبية',
        head: ['الجزء', 'وظيفته'],
        rows: [
          ['معدات المصدر', 'توفر الغاز أو التفريغ للنظام كله'],
          ['الأنابيب', 'تنقل كل غاز إلى الأقسام التي تستخدمه'],
          ['صمامات العزل ووحدات صمامات المناطق', 'تتيح عزل منطقة بأمان للصيانة أو الطوارئ'],
          ['المخارج الطرفية', 'تسلّم الغاز أو التفريغ عند السرير أو الحامل المعلّق أو نقطة السقف'],
          ['لوحات الإنذار', 'تنبّه الطاقم عند خروج الضغط أو الإمداد عن حدوده'],
        ],
      },
      usesTitle: 'أين تُركَّب الغازات الطبية',
      uses: ['غرف المرضى والأجنحة', 'غرف العمليات', 'العناية المركزة ووحدات الرعاية العالية', 'الطوارئ ومناطق الإنعاش', 'غرف الولادة ووحدات حديثي الولادة'],
      deliverTitle: 'ما نركّبه',
      deliver: [
        'أنابيب الأكسجين والهواء الطبي والتفريغ',
        'المخارج الطرفية وتوصيلات رأس السرير أو الحوامل المعلّقة',
        'صمامات العزل ووحدات صمامات المناطق',
        'لوحات الإنذار والمراقبة',
        'تحديد هوية الأنابيب ووسمها',
        'اختبار الضغط والتنقية والتشغيل',
      ],
      process: [
        { t: 'اعتماد الاحتياج والمسارات', d: 'نعمل وفق التصميم ومواضع المخارج التي يحددها الفريق السريري.' },
        { t: 'تركيب الأنابيب والمخارج', d: 'تُركَّب الأنابيب والصمامات والمخارج وتُحدَّد هويتها.' },
        { t: 'الاختبار والتنقية والتحقق', d: 'يُختبر ضغط كل نظام ويُنقَّى قبل الاستخدام.' },
        { t: 'التشغيل والتسليم', d: 'تُشغَّل الإنذارات وتُسلَّم السجلات.' },
      ],
      ctaTitle: 'تحتاج تركيب غازات طبية؟',
      ctaText: 'أرسل لنا التصميم وجدول المخارج وسنرد بعرض.',
    },
  },

  {
    key: 'hvac',
    segment: 'healthcare-contractor/healthcare-hvac',
    parent: 'mep',
    group: 'building',
    icon: 'hvac',
    image: null,
    related: ['medicalGas', 'fireProtection', 'orCeilings', 'mriRoom'],
    en: {
      name: 'Healthcare HVAC',
      title: 'Hospital HVAC Contractor in Saudi Arabia | EGC',
      description: 'HVAC for hospitals and clinical rooms in Saudi Arabia: temperature, humidity, pressure and filtration control for operating rooms, imaging suites and wards.',
      short: 'Temperature, humidity, pressure and filtration control for clinical spaces.',
      h1: 'Hospital HVAC contractor in Saudi Arabia',
      lead: 'Heating, ventilation and air conditioning for clinical spaces, where temperature, humidity, air pressure and filtration are part of the clinical environment, installed and balanced to the specified conditions.',
      answerTitle: 'Why hospital HVAC is different',
      answer: [
        'Hospital HVAC does more than keep a building comfortable. It controls the clinical environment: temperature and humidity within the limits that equipment and procedures need, air changes that dilute contamination, filtration that removes particles, and the pressure relationship between rooms so that air flows from cleaner areas towards less clean ones. Operating rooms are typically supplied with filtered air under positive pressure, isolation rooms are held at negative pressure so contaminated air does not escape, and imaging rooms such as MRI and CT need tight temperature and humidity control for the equipment. Ducts that cross a shielded wall must do so without breaking the shield. EGC installs HVAC systems for healthcare projects, coordinating duct routes, diffusers and controls with the ceilings, shielding and other services, and balancing and testing the system to the specified conditions before handover.',
        `HVAC is part of [healthcare MEP](${MEP}) and is coordinated with [medical gas](healthcare-contractor/medical-gas-systems), [fire protection](healthcare-contractor/fire-protection) and the [shielding](${SH}) in imaging rooms.`,
      ],
      table: {
        title: 'What the air has to do, by room',
        head: ['Room', 'What the HVAC has to achieve'],
        rows: [
          ['Operating rooms', 'Filtered supply air, positive pressure and controlled temperature and humidity'],
          ['Isolation rooms', 'Negative pressure so contaminated air does not leave the room'],
          ['Imaging rooms (MRI, CT, PET-CT)', 'Stable temperature and humidity for the equipment, with ducts crossing the shield correctly'],
          ['Wards and patient rooms', 'Comfort, ventilation and the air changes needed for infection control'],
        ],
      },
      usesTitle: 'Where we install it',
      uses: ['Operating theatres', 'Isolation and intensive-care rooms', 'Imaging departments', 'Wards and patient rooms', 'Clinics and day-care areas'],
      deliverTitle: 'What we install',
      deliver: [
        'Ductwork, diffusers and filtration',
        'Air-handling and fan-coil equipment',
        'Pressure-controlled rooms, positive and negative',
        'Controls and integration with building management',
        'Penetration details through shielded and fire-rated walls',
        'Testing, balancing and commissioning',
      ],
      process: [
        { t: 'Agree conditions and routes', d: 'We take the design conditions and agree duct routes with the other trades.' },
        { t: 'Install', d: 'Ductwork, equipment and controls are installed to the design.' },
        { t: 'Test and balance', d: 'Airflows and pressures are tested and balanced room by room.' },
        { t: 'Commission and hand over', d: 'The system is commissioned and records handed over.' },
      ],
      ctaTitle: 'Need HVAC for a clinical project?',
      ctaText: 'Send us the design and the room schedule and we will respond with a proposal.',
    },
    ar: {
      name: 'التكييف والتهوية الطبية',
      title: 'مقاول تكييف وتهوية للمستشفيات في السعودية | EGC',
      description: 'تكييف وتهوية للمستشفيات والغرف السريرية في السعودية: تحكم في الحرارة والرطوبة والضغط والترشيح لغرف العمليات وأجنحة التصوير والأجنحة.',
      short: 'تحكم في الحرارة والرطوبة والضغط والترشيح للمساحات السريرية.',
      h1: 'مقاول تكييف وتهوية للمستشفيات في السعودية',
      lead: 'تدفئة وتهوية وتكييف للمساحات السريرية، حيث تشكّل الحرارة والرطوبة وضغط الهواء والترشيح جزءًا من البيئة السريرية، تُركَّب وتُضبط وفق الظروف المحددة.',
      answerTitle: 'لماذا يختلف تكييف المستشفيات',
      answer: [
        'لا يقتصر تكييف المستشفيات على راحة المبنى؛ فهو يتحكم في البيئة السريرية: حرارة ورطوبة ضمن الحدود التي تحتاجها المعدات والإجراءات، وتبديل للهواء يخفف التلوث، وترشيح يزيل الجسيمات، وعلاقة ضغط بين الغرف بحيث يتدفق الهواء من المناطق الأنظف نحو الأقل نظافة. وتُغذّى غرف العمليات عادةً بهواء مرشَّح بضغط موجب، وتُحفظ غرف العزل بضغط سالب كي لا يتسرب الهواء الملوث، وتحتاج غرف التصوير كالرنين المغناطيسي والأشعة المقطعية إلى تحكم دقيق بالحرارة والرطوبة من أجل المعدات. ويجب أن تعبر المجاري الجدار المدرّع دون كسر الدرع. وتركّب EGC أنظمة التكييف والتهوية للمشاريع الصحية، وتنسّق مسارات المجاري والناشرات والتحكم مع الأسقف والتدريع والخدمات الأخرى، وتضبط النظام وتختبره وفق الظروف المحددة قبل التسليم.',
        `والتكييف جزء من [الأعمال الكهروميكانيكية الطبية](${MEP}) ويُنسَّق مع [الغازات الطبية](healthcare-contractor/medical-gas-systems) و[الحماية من الحريق](healthcare-contractor/fire-protection) و[التدريع](${SH}) في غرف التصوير.`,
      ],
      table: {
        title: 'ما الذي يجب أن يحققه الهواء، بحسب الغرفة',
        head: ['الغرفة', 'ما يجب أن يحققه التكييف'],
        rows: [
          ['غرف العمليات', 'هواء مغذٍّ مرشَّح وضغط موجب وتحكم في الحرارة والرطوبة'],
          ['غرف العزل', 'ضغط سالب كي لا يخرج الهواء الملوث من الغرفة'],
          ['غرف التصوير (الرنين وCT وPET-CT)', 'حرارة ورطوبة مستقرتان للمعدات مع عبور صحيح للمجاري عبر الدرع'],
          ['الأجنحة وغرف المرضى', 'الراحة والتهوية وتبديل الهواء اللازم لمكافحة العدوى'],
        ],
      },
      usesTitle: 'أين نركّبه',
      uses: ['غرف العمليات', 'غرف العزل والعناية المركزة', 'أقسام التصوير', 'الأجنحة وغرف المرضى', 'العيادات ومناطق اليوم الواحد'],
      deliverTitle: 'ما نركّبه',
      deliver: [
        'المجاري والناشرات والترشيح',
        'وحدات معالجة الهواء ووحدات الملف والمروحة',
        'غرف مضبوطة الضغط، موجبة وسالبة',
        'أنظمة التحكم والتكامل مع إدارة المبنى',
        'تفاصيل الاختراق عبر الجدران المدرّعة والمقاومة للحريق',
        'الاختبار والموازنة والتشغيل',
      ],
      process: [
        { t: 'اعتماد الظروف والمسارات', d: 'نأخذ ظروف التصميم ونتفق على مسارات المجاري مع بقية الأعمال.' },
        { t: 'التركيب', d: 'تُركَّب المجاري والمعدات وأنظمة التحكم وفق التصميم.' },
        { t: 'الاختبار والموازنة', d: 'تُختبر تدفقات الهواء والضغوط وتُوازن غرفة غرفة.' },
        { t: 'التشغيل والتسليم', d: 'يُشغَّل النظام وتُسلَّم السجلات.' },
      ],
      ctaTitle: 'تحتاج تكييفًا لمشروع سريري؟',
      ctaText: 'أرسل لنا التصميم وجدول الغرف وسنرد بعرض.',
    },
  },

  {
    key: 'fireProtection',
    segment: 'healthcare-contractor/fire-protection',
    parent: 'mep',
    group: 'building',
    icon: 'fire',
    image: null,
    related: ['hvac', 'medicalGas', 'hospitalFitOut', 'shielding'],
    en: {
      name: 'Fire Protection',
      title: 'Hospital Fire Protection Contractor in Saudi Arabia | EGC',
      description: 'Fire protection for hospitals in Saudi Arabia: detection and alarm, sprinklers and fire-stopping, installed to the project specification.',
      short: 'Detection and alarm, sprinkler pipework and fire-stopping.',
      h1: 'Fire protection systems for hospitals in Saudi Arabia',
      lead: 'Fire detection, alarm and suppression systems for hospitals and clinical buildings, installed to the project specification and coordinated with the ceilings, shielding and services they pass through.',
      answerTitle: 'How fire protection works in a hospital',
      answer: [
        'Fire protection in a hospital has to work for people who cannot evacuate quickly, so hospitals rely on detection and compartmentation as well as suppression: detectors and alarms give early warning, sprinklers or other suppression control a fire, and fire-rated construction and fire-stopping keep smoke and flame within the compartment where they start, which lets staff move patients horizontally to a safe area. Shielded rooms add a complication: every sprinkler pipe, detector cable and duct that crosses a lead or RF shield must do so without leaving a gap, and every opening through a fire-rated wall must be sealed. EGC installs fire protection systems as part of its healthcare contracting, coordinating routes and penetrations with the shielding, ceilings and other services, and testing the systems before handover to the requirements of the project and the authorities.',
        `Fire protection is coordinated with [healthcare HVAC](healthcare-contractor/healthcare-hvac), [medical gas](healthcare-contractor/medical-gas-systems) and the [shielding](${SH}) it passes through.`,
      ],
      table: {
        title: 'The layers of hospital fire protection',
        head: ['Layer', 'What it does'],
        rows: [
          ['Detection and alarm', 'Gives early warning and tells staff where the fire is'],
          ['Suppression (sprinklers)', 'Controls the fire until it can be dealt with'],
          ['Compartmentation', 'Fire-rated walls, floors and doors keep the fire in one area'],
          ['Fire-stopping', 'Seals every pipe, cable and duct penetration through rated construction'],
        ],
      },
      usesTitle: 'Where we install it',
      uses: ['Hospitals and medical cities', 'Clinics and day-care centres', 'Imaging departments', 'Operating theatres', 'Laboratories and pharmacies'],
      deliverTitle: 'What we install',
      deliver: [
        'Fire detection and alarm systems',
        'Sprinkler and suppression pipework',
        'Fire-stopping of penetrations through rated walls and floors',
        'Coordination with fire-rated doors and dampers',
        'Testing and commissioning',
        'Handover documentation',
      ],
      process: [
        { t: 'Review the fire strategy', d: 'We work from the project’s fire design and the authority requirements.' },
        { t: 'Coordinate routes and penetrations', d: 'Pipes, cables and openings are coordinated with the other trades first.' },
        { t: 'Install', d: 'Systems and fire-stopping are installed to the specification.' },
        { t: 'Test and hand over', d: 'Systems are tested and commissioned, then handed over with records.' },
      ],
      ctaTitle: 'Need fire protection installed?',
      ctaText: 'Send us the fire design and the programme and we will respond with a proposal.',
    },
    ar: {
      name: 'الحماية من الحريق',
      title: 'مقاول حماية من الحريق للمستشفيات في السعودية | EGC',
      description: 'الحماية من الحريق للمستشفيات في السعودية: كشف وإنذار ورشاشات وسدّ منافذ الحريق، تُركَّب وفق مواصفات المشروع وتُنسَّق مع بقية الأعمال.',
      short: 'كشف وإنذار وأنابيب رشاشات وسدّ منافذ الحريق.',
      h1: 'أنظمة الحماية من الحريق للمستشفيات في السعودية',
      lead: 'أنظمة كشف وإنذار وإطفاء للمستشفيات والمباني السريرية، تُركَّب وفق مواصفات المشروع وتُنسَّق مع الأسقف والتدريع والخدمات التي تعبرها.',
      answerTitle: 'كيف تعمل الحماية من الحريق في المستشفى',
      answer: [
        'يجب أن تعمل الحماية من الحريق في المستشفى لصالح أشخاص لا يستطيعون الإخلاء بسرعة، ولذلك تعتمد المستشفيات على الكشف وعلى تقسيم المبنى إلى حيزات مقاومة للحريق إلى جانب الإطفاء: تعطي أجهزة الكشف والإنذار تنبيهًا مبكرًا، وتسيطر الرشاشات أو غيرها على الحريق، وتبقي الإنشاءات المقاومة للحريق وسدّ المنافذ الدخان واللهب داخل الحيز الذي بدأ فيه، فيتمكن الطاقم من نقل المرضى أفقيًا إلى منطقة آمنة. وتضيف الغرف المدرّعة تعقيدًا: فكل أنبوب رشاش وكابل كاشف ومجرى يعبر درع الرصاص أو الترددات الراديوية يجب أن يعبره دون ترك فجوة، وكل فتحة عبر جدار مقاوم للحريق يجب أن تُحكَم. وتركّب EGC أنظمة الحماية من الحريق ضمن أعمالها كمقاول مشاريع صحية، وتنسّق المسارات والاختراقات مع التدريع والأسقف والخدمات الأخرى، وتختبر الأنظمة قبل التسليم وفق متطلبات المشروع والجهات المختصة.',
        `وتُنسَّق الحماية من الحريق مع [التكييف والتهوية الطبية](healthcare-contractor/healthcare-hvac) و[الغازات الطبية](healthcare-contractor/medical-gas-systems) و[التدريع](${SH}) الذي تعبره.`,
      ],
      table: {
        title: 'طبقات الحماية من الحريق في المستشفى',
        head: ['الطبقة', 'وظيفتها'],
        rows: [
          ['الكشف والإنذار', 'تعطي تنبيهًا مبكرًا وتخبر الطاقم أين الحريق'],
          ['الإطفاء (الرشاشات)', 'تسيطر على الحريق إلى أن يمكن التعامل معه'],
          ['تقسيم الحيزات', 'جدران وأرضيات وأبواب مقاومة للحريق تبقي الحريق في منطقة واحدة'],
          ['سدّ منافذ الحريق', 'يحكم كل اختراق لأنبوب أو كابل أو مجرى عبر إنشاء مقاوم للحريق'],
        ],
      },
      usesTitle: 'أين نركّبها',
      uses: ['المستشفيات والمدن الطبية', 'العيادات ومراكز اليوم الواحد', 'أقسام التصوير', 'غرف العمليات', 'المختبرات والصيدليات'],
      deliverTitle: 'ما نركّبه',
      deliver: [
        'أنظمة كشف الحريق والإنذار',
        'أنابيب الرشاشات وأنظمة الإطفاء',
        'سدّ منافذ الاختراق عبر الجدران والأرضيات المقاومة للحريق',
        'التنسيق مع الأبواب والمخمّدات المقاومة للحريق',
        'الاختبار والتشغيل',
        'وثائق التسليم',
      ],
      process: [
        { t: 'مراجعة استراتيجية الحريق', d: 'نعمل وفق تصميم الحريق في المشروع ومتطلبات الجهات المختصة.' },
        { t: 'تنسيق المسارات والاختراقات', d: 'تُنسَّق الأنابيب والكابلات والفتحات مع بقية الأعمال أولًا.' },
        { t: 'التركيب', d: 'تُركَّب الأنظمة وسدّ المنافذ وفق المواصفات.' },
        { t: 'الاختبار والتسليم', d: 'تُختبر الأنظمة وتُشغَّل ثم تُسلَّم مع السجلات.' },
      ],
      ctaTitle: 'تحتاج تركيب حماية من الحريق؟',
      ctaText: 'أرسل لنا تصميم الحريق والبرنامج الزمني وسنرد بعرض.',
    },
  },

  {
    key: 'nurseCall',
    segment: 'healthcare-contractor/nurse-call-installation',
    parent: 'mep',
    group: 'building',
    icon: 'bell',
    image: null,
    related: ['medicalGas', 'hospitalFitOut', 'hvac', 'wallPanels'],
    en: {
      name: 'Nurse Call Installation',
      title: 'Nurse Call System Installation in Saudi Arabia | EGC',
      description: 'Nurse call system installation for hospitals in Saudi Arabia: cabling, bedside and bathroom call points, corridor lights and nurse-station units, tested and commissioned.',
      short: 'Cabling, call points, corridor lights and nurse-station units, tested bed by bed.',
      h1: 'Nurse call system installation for hospitals in Saudi Arabia',
      lead: 'We install nurse call systems in hospitals and care facilities: the cabling, the call points and indicators, tested bed by bed and commissioned with the ward team.',
      flow: {
        title: 'How a call travels',
        steps: ['The patient presses the call point', 'A dome light shows above the room door', 'The nurse station displays the call', 'Staff are alerted and answer'],
      },
      answerTitle: 'How a nurse call system works',
      answer: [
        'A nurse call system lets a patient summon help and lets staff see, prioritise and answer the call. A call point at the bedside or in the bathroom sends a signal to the nurse station and lights a dome lamp above the room door, and the call can be passed on to staff handsets where the system supports it. Emergency pull-cords in bathrooms and a separate emergency or staff-assist call let a call be escalated. The system is only as good as its installation: call points must be reachable from the bed, cabling must be routed and labelled, and the whole system must be tested bed by bed so that each call arrives where it should. EGC installs nurse call systems as part of its healthcare contracting: we run the cabling and containment, fit the call points, indicators and nurse-station units, and test and commission the system with the ward team, coordinating all of it with the rest of the ward works.',
        `Nurse call cabling is part of the room’s services, so it is planned with the [healthcare MEP](${MEP}) and the [hospital fit-out](healthcare-contractor/hospital-fit-out).`,
      ],
      table: {
        title: 'Parts of a nurse call system',
        head: ['Part', 'Where it is', 'What it does'],
        rows: [
          ['Bedside call point', 'At each bed', 'The patient calls for routine assistance'],
          ['Bathroom emergency pull-cord', 'In toilets and showers', 'Raises an emergency call from a place where patients are at risk'],
          ['Corridor dome light', 'Above each room door', 'Shows which room is calling, and its priority'],
          ['Nurse-station master unit', 'At the nurse station', 'Displays and logs calls and lets staff answer them'],
          ['Staff handset or pager', 'Carried by nurses', 'Delivers calls to the responsible nurse, where the system provides it'],
        ],
      },
      usesTitle: 'Where nurse call is installed',
      uses: ['Patient rooms and wards', 'Intensive care and high-dependency units', 'Emergency and day-care areas', 'Long-term care and rehabilitation', 'Clinics with patient bays'],
      deliverTitle: 'What we install',
      deliver: [
        'Cabling and containment for the system',
        'Bedside, bathroom and emergency call points',
        'Corridor dome lights and zone displays',
        'Nurse-station master units',
        'Connection to staff handsets or paging, where specified',
        'Testing and commissioning, bed by bed',
      ],
      process: [
        { t: 'Review the ward layout', d: 'We study the plans and the specified system and confirm where each device goes.' },
        { t: 'Cable and install', d: 'Cabling, call points and indicators are installed with the rest of the ward works.' },
        { t: 'Test bed by bed', d: 'Every call is tested end to end.' },
        { t: 'Commission and hand over', d: 'The system is commissioned with the ward team and records are handed over.' },
      ],
      ctaTitle: 'Need a nurse call system installed?',
      ctaText: 'Send us the ward plans and the specification and we will respond with a proposal.',
    },
    ar: {
      name: 'تركيب أنظمة نداء الممرضات',
      title: 'تركيب أنظمة نداء الممرضات في السعودية | EGC',
      description: 'تركيب أنظمة نداء الممرضات للمستشفيات في السعودية: التمديدات ونقاط النداء عند السرير ودورة المياه وأضواء الممرات ووحدات محطة التمريض، مع الاختبار والتشغيل.',
      short: 'التمديدات ونقاط النداء وأضواء الممرات ووحدات محطة التمريض، تُختبر سريرًا سريرًا.',
      h1: 'تركيب أنظمة نداء الممرضات في المستشفيات بالسعودية',
      lead: 'نركّب أنظمة نداء الممرضات في المستشفيات ومرافق الرعاية: التمديدات ونقاط النداء والمؤشرات، تُختبر سريرًا سريرًا وتُشغَّل مع فريق الجناح.',
      flow: {
        title: 'كيف يصل النداء',
        steps: ['يضغط المريض على نقطة النداء', 'يضيء ضوء فوق باب الغرفة', 'تعرض محطة التمريض النداء', 'يتنبه الطاقم ويرد'],
      },
      answerTitle: 'كيف يعمل نظام نداء الممرضات',
      answer: [
        'يتيح نظام نداء الممرضات للمريض طلب المساعدة، ويتيح للطاقم رؤية النداء وترتيب أولويته والرد عليه. فنقطة النداء عند السرير أو في دورة المياه ترسل إشارة إلى محطة التمريض وتضيء مصباحًا فوق باب الغرفة، ويمكن تمرير النداء إلى أجهزة الطاقم اليدوية حيث يدعم النظام ذلك. وتتيح حبال الطوارئ في دورات المياه ونداء الطوارئ أو طلب مساندة الطاقم تصعيد النداء. وجودة النظام من جودة تركيبه: يجب أن تكون نقاط النداء في متناول المريض من السرير، وأن تُمدَّد الكابلات وتُعنوَن، وأن يُختبر النظام كله سريرًا سريرًا ليصل كل نداء إلى وجهته. وتركّب EGC أنظمة نداء الممرضات ضمن أعمالها كمقاول مشاريع صحية: نمدّ الكابلات والمسارات، ونركّب نقاط النداء والمؤشرات ووحدات محطة التمريض، ونختبر النظام ونشغّله مع فريق الجناح، وننسّق ذلك كله مع بقية أعمال الجناح.',
        `وتمديدات نداء الممرضات جزء من خدمات الغرفة، ولذلك تُخطَّط مع [الأعمال الكهروميكانيكية الطبية](${MEP}) و[تجهيز المستشفيات](healthcare-contractor/hospital-fit-out).`,
      ],
      table: {
        title: 'أجزاء نظام نداء الممرضات',
        head: ['الجزء', 'مكانه', 'وظيفته'],
        rows: [
          ['نقطة النداء عند السرير', 'عند كل سرير', 'يطلب المريض المساعدة العادية'],
          ['حبل طوارئ دورة المياه', 'في دورات المياه والاستحمام', 'يرفع نداء طوارئ من مكان يتعرض فيه المرضى للخطر'],
          ['ضوء الممر فوق الباب', 'فوق باب كل غرفة', 'يبيّن أي غرفة تنادي وأولوية النداء'],
          ['الوحدة الرئيسية في محطة التمريض', 'في محطة التمريض', 'تعرض النداءات وتسجلها وتتيح للطاقم الرد عليها'],
          ['الجهاز اليدوي أو النداء للطاقم', 'يحمله الممرضون', 'يوصل النداء إلى الممرضة المسؤولة حيث يوفره النظام'],
        ],
      },
      usesTitle: 'أين تُركَّب أنظمة النداء',
      uses: ['غرف المرضى والأجنحة', 'العناية المركزة ووحدات الرعاية العالية', 'الطوارئ ومناطق اليوم الواحد', 'الرعاية طويلة الأمد والتأهيل', 'العيادات ذات مقاعد المرضى'],
      deliverTitle: 'ما نركّبه',
      deliver: [
        'تمديدات النظام ومساراته',
        'نقاط نداء عند السرير ودورة المياه وللطوارئ',
        'أضواء الممرات وشاشات المناطق',
        'وحدات رئيسية لمحطات التمريض',
        'الربط بأجهزة الطاقم اليدوية أو النداء حيث تُحدَّد',
        'الاختبار والتشغيل سريرًا سريرًا',
      ],
      process: [
        { t: 'مراجعة مخطط الجناح', d: 'ندرس المخططات والنظام المحدد ونؤكد موضع كل جهاز.' },
        { t: 'التمديد والتركيب', d: 'تُركَّب التمديدات ونقاط النداء والمؤشرات مع بقية أعمال الجناح.' },
        { t: 'اختبار سرير بسرير', d: 'يُختبر كل نداء من طرفه إلى طرفه.' },
        { t: 'التشغيل والتسليم', d: 'يُشغَّل النظام مع فريق الجناح وتُسلَّم السجلات.' },
      ],
      ctaTitle: 'تحتاج تركيب نظام نداء للممرضات؟',
      ctaText: 'أرسل لنا مخططات الجناح والمواصفات وسنرد بعرض.',
    },
  },
];
