/* Wood & Corian factory pages (parent: manufacturing): the products people search for by name. */
const SU = 'healthcare-contractor/infection-control-surfaces';
const DO = 'healthcare-contractor/medical-doors';

export const FACTORY = [
  {
    key: 'woodenDoors',
    segment: 'manufacturing/wooden-doors',
    parent: 'manufacturing',
    group: 'factory',
    icon: 'door',
    related: ['joinery', 'corianSurfaces', 'doors', 'hermeticDoors', 'hospitalFitOut'],
    en: {
      name: 'Wooden Doors',
      title: 'Wooden Doors Manufacturer in Jeddah, Saudi Arabia | EGC',
      description: 'Custom wooden doors and frames made in our own Jeddah factory for hospitals, hotels, offices and public buildings across Saudi Arabia.',
      short: 'Custom wooden doors, frames and door sets, made in our Jeddah factory.',
      h1: 'Wooden doors manufacturer in Jeddah, Saudi Arabia',
      lead: 'Our Wood & Corian factory makes custom wooden doors, frames and panelling for healthcare, hospitality and commercial projects: cut on CNC machinery, finished in the workshop and fitted by our own crews.',
      answerTitle: 'Custom wooden doors, made to the project',
      answer: [
        'A custom wooden door is made to the project, not picked from a catalogue. Dimensions, leaf thickness, core, face veneer or laminate, finish, glazing, ironmongery and frame profile are all set by the architect’s door schedule, and the door is fabricated to suit. Our Jeddah factory cuts the components on CNC machinery, assembles and finishes the leaves and frames in the workshop and fits them on site with the same team, so door, frame and wall are coordinated. For hospitals, the same factory makes the doors for patient rooms, offices, corridors and public areas, matched in finish to the specialist lead-lined and RF-shielded doors our shielding team installs in the imaging rooms. We work from your door schedule and shop drawings, sample the finish for approval and hand over doors that are adjusted and tested.',
        `For rooms that need radiation or RF protection, see our [medical doors](${DO}); for matching panelling, counters and cabinetry, see [architectural joinery](manufacturing/architectural-joinery).`,
      ],
      table: {
        title: 'Common door constructions and where they suit',
        head: ['Construction', 'Typical use', 'Points to consider'],
        rows: [
          ['Solid timber', 'Feature entrances and high-end interiors', 'Natural look; timber moves with humidity, so frames and sizes need care'],
          ['Veneered engineered core', 'Hotels, offices and patient rooms', 'Real-wood appearance with good dimensional stability'],
          ['Laminate or HPL-faced', 'Clinical corridors, wards and high-traffic areas', 'Durable and wipe-clean, which suits infection-control cleaning'],
          ['Glazed or vision-panel doors', 'Wards, consulting rooms and corridors', 'Visibility for staff; glass type and frame are set out to the specification'],
        ],
      },
      usesTitle: 'Where wooden doors are used',
      uses: ['Hospitals, clinics and medical centres', 'Hotels, resorts and hospitality', 'Offices and commercial buildings', 'Public and institutional buildings'],
      deliverTitle: 'What we make',
      deliver: [
        'Custom wooden doors and door sets to your schedule',
        'Timber and veneered frames, linings and architraves',
        'Glazed and vision-panel doors',
        'Matching wall panels and cladding',
        'Ironmongery and door furniture, fitted',
        'Workshop finishing, site installation and adjustment',
      ],
      process: [
        { t: 'Take the schedule', d: 'We price and programme from your door schedule and drawings.' },
        { t: 'Shop drawings and samples', d: 'Construction details and finish samples are approved before production.' },
        { t: 'Make in the factory', d: 'Components are cut on CNC machinery, then assembled and finished in the workshop.' },
        { t: 'Install and adjust', d: 'Our crews hang the doors, fit the ironmongery and adjust them before handover.' },
      ],
      ctaTitle: 'Need wooden doors for a project?',
      ctaText: 'Send us the door schedule and we will respond with options, lead times and a quotation.',
    },
    ar: {
      name: 'الأبواب الخشبية',
      title: 'مصنع أبواب خشبية في جدة، السعودية | EGC',
      description: 'أبواب وإطارات خشبية مصنّعة حسب الطلب في مصنعنا بجدة للمستشفيات والفنادق والمكاتب والمباني العامة في أنحاء المملكة.',
      short: 'أبواب وإطارات خشبية مصنّعة حسب الطلب في مصنعنا بجدة.',
      h1: 'مصنع أبواب خشبية في جدة، السعودية',
      lead: 'يصنع مصنع الخشب والكوريان لدينا أبوابًا وإطارات وألواحًا خشبية حسب الطلب لمشاريع الرعاية الصحية والضيافة والمباني التجارية: تُقطَّع بماكينات CNC وتُشطَّب في الورشة وتُركَّب بكوادرنا.',
      answerTitle: 'أبواب خشبية مصنّعة حسب المشروع',
      answer: [
        'الباب الخشبي المخصص يُصنع للمشروع ولا يُختار من كتالوج. فالأبعاد وسماكة الضلفة والقلب وقشرة الوجه أو الصفائح والتشطيب والزجاج والإكسسوارات ومقطع الإطار كلها تحددها جداول الأبواب لدى المعماري، ويُصنع الباب وفقها. يقطع مصنعنا في جدة المكونات بماكينات CNC، ويجمّع الضلف والإطارات ويشطّبها في الورشة، ثم يركّبها في الموقع بالفريق نفسه، فينسجم الباب والإطار والجدار. وفي المستشفيات يصنع المصنع نفسه أبواب غرف المرضى والمكاتب والممرات والمناطق العامة، متطابقة في التشطيب مع الأبواب المتخصصة المبطنة بالرصاص والمدرّعة ضد الترددات الراديوية التي يركّبها فريق التدريع لدينا في غرف التصوير. نعمل وفق جدول الأبواب والمخططات التنفيذية لديك، ونعرض عينات التشطيب للاعتماد، ونسلّم أبوابًا مضبوطة ومختبَرة.',
        `وللغرف التي تحتاج حماية من الإشعاع أو الترددات الراديوية راجع [الأبواب الطبية](${DO})، وللألواح والمنضدات والخزائن المتطابقة راجع [النجارة المعمارية](manufacturing/architectural-joinery).`,
      ],
      table: {
        title: 'أنواع إنشاء الأبواب الشائعة ومتى تناسب',
        head: ['نوع الإنشاء', 'الاستخدام المعتاد', 'ما يجب مراعاته'],
        rows: [
          ['خشب صلب', 'المداخل المميزة والتصميمات الداخلية الفاخرة', 'مظهر طبيعي؛ يتحرك الخشب مع الرطوبة فيلزم عناية بالإطارات والمقاسات'],
          ['قلب هندسي مكسو بقشرة خشبية', 'الفنادق والمكاتب وغرف المرضى', 'مظهر الخشب الحقيقي مع ثبات جيد في الأبعاد'],
          ['مكسو بالصفائح (HPL)', 'الممرات السريرية والأجنحة والمناطق كثيفة الاستخدام', 'متين وسهل المسح، ويناسب بروتوكولات التنظيف لمكافحة العدوى'],
          ['أبواب مزجّجة أو بلوحة رؤية', 'الأجنحة وغرف الاستشارة والممرات', 'رؤية للطاقم؛ يُحدَّد نوع الزجاج والإطار وفق المواصفات'],
        ],
      },
      usesTitle: 'أين تُستخدم الأبواب الخشبية',
      uses: ['المستشفيات والعيادات والمراكز الطبية', 'الفنادق والمنتجعات والضيافة', 'المكاتب والمباني التجارية', 'المباني العامة والمؤسسية'],
      deliverTitle: 'ما نصنعه',
      deliver: [
        'أبواب خشبية وأطقم أبواب مخصصة وفق جدولك',
        'إطارات وبطانات وكرانيش من الخشب والقشرة الخشبية',
        'أبواب مزجّجة وأبواب بلوحة رؤية',
        'ألواح جدارية وكسوات متطابقة',
        'توريد الإكسسوارات وتركيبها',
        'التشطيب في الورشة والتركيب والضبط في الموقع',
      ],
      process: [
        { t: 'استلام الجدول', d: 'نسعّر ونبرمج وفق جدول الأبواب والمخططات لديك.' },
        { t: 'المخططات والعينات', d: 'تُعتمد تفاصيل الإنشاء وعينات التشطيب قبل الإنتاج.' },
        { t: 'التصنيع في المصنع', d: 'تُقطَّع المكونات بماكينات CNC ثم تُجمَّع وتُشطَّب في الورشة.' },
        { t: 'التركيب والضبط', d: 'تعلّق كوادرنا الأبواب وتركّب الإكسسوارات وتضبطها قبل التسليم.' },
      ],
      ctaTitle: 'تحتاج أبوابًا خشبية لمشروع؟',
      ctaText: 'أرسل لنا جدول الأبواب وسنرد بالخيارات ومدد التوريد وعرض السعر.',
    },
  },

  {
    key: 'corianSurfaces',
    segment: 'manufacturing/corian-solid-surface',
    parent: 'manufacturing',
    group: 'factory',
    icon: 'layers',
    related: ['surfaces', 'joinery', 'woodenDoors', 'hospitalFitOut'],
    en: {
      name: 'Corian & Solid Surface',
      title: 'Corian Fabrication in Jeddah, Saudi Arabia | EGC Factory',
      description: 'Corian and solid-surface counters, nurse stations, reception desks and vanities fabricated in our Jeddah factory: seamless, made to fit and installed by our crews.',
      short: 'Seamless Corian counters, nurse stations, reception desks and vanities.',
      h1: 'Corian and solid-surface fabrication in Jeddah, Saudi Arabia',
      lead: 'Seamless Corian counters, nurse stations, reception desks, vanities and wall cladding, templated on site, fabricated in our own Jeddah factory and installed by our crews.',
      answerTitle: 'Why solid surface, and how we make it',
      answer: [
        'Corian is a solid-surface material: the same material runs all the way through, so edges can be profiled, sinks can be formed into the counter and joints can be bonded and sanded flush. That is why it is used wherever surfaces are cleaned constantly, in hospitals, laboratories, kitchens and hotels, as well as where designers want sculpted reception desks and curved counters. In our factory we template the room, cut the sheet on CNC machinery, thermoform curves and edges, bond the seams and finish the surface to the specified sheen. The pieces are then installed on site by the team that made them, with sinks and upstands integrated. Because fabrication is in-house, fit and lead times are under our control, and the same factory supplies the matching joinery and doors.',
        `For clinical rooms see [infection-control surfaces](${SU}); for matching woodwork see [wooden doors](manufacturing/wooden-doors) and [architectural joinery](manufacturing/architectural-joinery).`,
      ],
      table: {
        title: 'Surface materials compared',
        head: ['Material', 'Strengths', 'Points to consider'],
        rows: [
          ['Solid surface (Corian)', 'Non-porous, seamless joints, repairable, can be formed into curves and integrated sinks', 'Needs skilled fabrication and templating'],
          ['High-pressure laminate', 'Economical, wide range of finishes', 'Visible joints and edges; damage is hard to repair'],
          ['Stainless steel', 'Very hygienic and hard-wearing', 'Limited forms and a harder look'],
          ['Natural stone', 'Premium appearance', 'Heavy; porous unless sealed; joints are visible'],
        ],
      },
      usesTitle: 'Where we use it',
      uses: ['Nurse stations and reception counters', 'Scrub and hand-wash sinks', 'Laboratory benches', 'Hotel vanities and bathrooms', 'Wall cladding and feature panels'],
      deliverTitle: 'What we make',
      deliver: [
        'Counters and vanities with integrated sinks',
        'Nurse stations and reception desks',
        'Thermoformed curves and bespoke shapes',
        'Wall cladding and panels',
        'Laboratory and workstation surfaces',
        'Templating, fabrication, installation and finishing',
      ],
      process: [
        { t: 'Template on site', d: 'We measure the finished room so every piece fits the wall as built.' },
        { t: 'Fabricate in the factory', d: 'CNC cutting, thermoforming and seaming in our Jeddah workshop.' },
        { t: 'Install and join', d: 'Pieces are fixed, seams bonded and sinks integrated on site.' },
        { t: 'Polish and hand over', d: 'Surfaces are finished to the specified sheen and cleaned for use.' },
      ],
      ctaTitle: 'Need Corian or solid-surface work?',
      ctaText: 'Send us the drawings or the room dimensions and we will respond with a proposal and lead time.',
    },
    ar: {
      name: 'الكوريان والأسطح الصلبة',
      title: 'تصنيع الكوريان في جدة، السعودية | مصنع EGC',
      description: 'منضدات ومحطات تمريض ومكاتب استقبال وأحواض من الكوريان والأسطح الصلبة تُصنَّع في مصنعنا بجدة: متصلة بلا فواصل ومصممة لتناسب الموقع وتُركَّب بكوادرنا.',
      short: 'منضدات ومحطات تمريض ومكاتب استقبال وأحواض من الكوريان بلا فواصل.',
      h1: 'تصنيع الكوريان والأسطح الصلبة في جدة، السعودية',
      lead: 'منضدات ومحطات تمريض ومكاتب استقبال وأحواض وكسوات جدارية من الكوريان بلا فواصل، تُؤخذ مقاساتها في الموقع وتُصنَّع في مصنعنا بجدة وتُركَّب بكوادرنا.',
      answerTitle: 'لماذا الأسطح الصلبة وكيف نصنعها',
      answer: [
        'الكوريان مادة سطح صلب: المادة نفسها تمتد في كامل سماكتها، فيمكن تشكيل الحواف ودمج الأحواض في المنضدة ولصق الوصلات وصقلها حتى تستوي. ولذلك تُستخدم حيثما تُنظَّف الأسطح باستمرار، في المستشفيات والمختبرات والمطابخ والفنادق، وحيثما يريد المصممون مكاتب استقبال منحوتة ومنضدات منحنية. وفي مصنعنا نأخذ مقاسات الغرفة، ونقص اللوح بماكينات CNC، ونشكّل المنحنيات والحواف حراريًا، ونلصق الوصلات، ونشطّب السطح بدرجة اللمعان المطلوبة. ثم يركّب الفريق نفسه القطع في الموقع مع دمج الأحواض والحواف الخلفية. وبما أن التصنيع داخل المصنع فإن دقة المقاسات ومدد التوريد تحت سيطرتنا، ويورّد المصنع نفسه النجارة والأبواب المتطابقة.',
        `وللغرف السريرية راجع [الأسطح المقاومة للعدوى](${SU})، وللأعمال الخشبية المتطابقة راجع [الأبواب الخشبية](manufacturing/wooden-doors) و[النجارة المعمارية](manufacturing/architectural-joinery).`,
      ],
      table: {
        title: 'مقارنة بين مواد الأسطح',
        head: ['المادة', 'نقاط القوة', 'ما يجب مراعاته'],
        rows: [
          ['السطح الصلب (كوريان)', 'غير مسامي، بوصلات متصلة، قابل للإصلاح، ويمكن تشكيله بمنحنيات وأحواض مدمجة', 'يحتاج تصنيعًا ماهرًا وأخذ مقاسات دقيق'],
          ['الصفائح عالية الضغط (HPL)', 'اقتصادية وبتشكيلة واسعة من التشطيبات', 'وصلات وحواف ظاهرة؛ يصعب إصلاح التلف'],
          ['الفولاذ المقاوم للصدأ', 'صحي جدًا ومتين', 'أشكال محدودة ومظهر أكثر صلابة'],
          ['الحجر الطبيعي', 'مظهر فاخر', 'ثقيل ومسامي ما لم يُعزل، والوصلات ظاهرة'],
        ],
      },
      usesTitle: 'أين نستخدمه',
      uses: ['محطات التمريض ومكاتب الاستقبال', 'أحواض الغسيل الجراحي وغسل اليدين', 'طاولات المختبرات', 'منضدات الفنادق وحماماتها', 'الكسوات الجدارية واللوحات الجمالية'],
      deliverTitle: 'ما نصنعه',
      deliver: [
        'منضدات وأحواض بأحواض مدمجة',
        'محطات تمريض ومكاتب استقبال',
        'منحنيات مشكّلة حراريًا وأشكال مخصصة',
        'كسوات وألواح جدارية',
        'أسطح المختبرات ومحطات العمل',
        'أخذ المقاسات والتصنيع والتركيب والتشطيب',
      ],
      process: [
        { t: 'أخذ المقاسات في الموقع', d: 'نقيس الغرفة بعد اكتمالها لتناسب كل قطعة الجدار كما بُني.' },
        { t: 'التصنيع في المصنع', d: 'قص بماكينات CNC وتشكيل حراري ولصق في ورشتنا بجدة.' },
        { t: 'التركيب والوصل', d: 'تُثبَّت القطع وتُلصق الوصلات وتُدمج الأحواض في الموقع.' },
        { t: 'الصقل والتسليم', d: 'تُشطَّب الأسطح بدرجة اللمعان المحددة وتُنظَّف للاستخدام.' },
      ],
      ctaTitle: 'تحتاج أعمال كوريان أو أسطح صلبة؟',
      ctaText: 'أرسل لنا المخططات أو أبعاد الغرفة وسنرد بعرض ومدة توريد.',
    },
  },

  {
    key: 'joinery',
    segment: 'manufacturing/architectural-joinery',
    parent: 'manufacturing',
    group: 'factory',
    icon: 'hammer',
    related: ['woodenDoors', 'corianSurfaces', 'surfaces', 'wallPanels', 'hospitalFitOut'],
    en: {
      name: 'Architectural Joinery & Millwork',
      title: 'Architectural Joinery & Millwork in Saudi Arabia | EGC',
      description: 'Joinery, millwork, wall panelling, reception counters and built-in furniture made in our Jeddah factory for healthcare, hotel and commercial interiors.',
      short: 'Wall panelling, reception counters, casework and built-in furniture.',
      h1: 'Architectural joinery and millwork factory in Jeddah, Saudi Arabia',
      lead: 'CNC-cut timber components finished into doors, wall panelling, reception counters, casework and built-in furniture, from one workshop and one quality programme.',
      answerTitle: 'Joinery made to fit the building',
      answer: [
        'Joinery is the fixed and fitted woodwork of a building: doors and frames, wall panelling, reception counters, cabinetry, wardrobes and built-in furniture. Good joinery starts with measured drawings, accurate components and a controlled workshop, because the finished pieces have to fit walls that are never perfectly straight. Our Jeddah factory works from the architect’s drawings, cuts components on CNC machinery, assembles and finishes them under one roof and installs them with the team that made them. The same workshop makes the clinical cabinetry and infection-control joinery for our healthcare rooms and the interior packages for hotels, offices and public buildings, so the finishes, profiles and tolerances stay consistent across a whole project.',
        'For individual products see [wooden doors](manufacturing/wooden-doors) and [Corian and solid surface](manufacturing/corian-solid-surface).',
      ],
      table: null,
      usesTitle: 'Where we install it',
      uses: ['Hospitals, clinics and medical centres', 'Hotels and resorts', 'Offices and commercial towers', 'Retail and food-and-beverage interiors', 'Public and institutional buildings'],
      deliverTitle: 'What we make',
      deliver: [
        'Wall panelling and cladding',
        'Reception counters and casework',
        'Built-in furniture and wardrobes',
        'Clinical cabinetry and storage',
        'Doors, frames, linings and architraves',
        'Templating, workshop fabrication and site installation',
      ],
      process: [
        { t: 'Measure and detail', d: 'Site measurements and shop drawings for every piece.' },
        { t: 'Cut and assemble', d: 'CNC-cut components assembled in the workshop.' },
        { t: 'Finish', d: 'Finishing in the workshop to the approved sample.' },
        { t: 'Install and snag', d: 'Fitting on site by the team that made the pieces, then snagging to handover.' },
      ],
      ctaTitle: 'Planning an interior package?',
      ctaText: 'Send us the drawings and we will respond with a proposal, programme and lead times.',
    },
    ar: {
      name: 'النجارة المعمارية',
      title: 'نجارة معمارية وأعمال خشبية في السعودية | EGC',
      description: 'نجارة وأعمال خشبية وألواح جدارية ومكاتب استقبال وأثاث مدمج يُصنَّع في مصنعنا بجدة للمشاريع الصحية والفنادق والمباني التجارية.',
      short: 'ألواح جدارية ومكاتب استقبال وخزائن وأثاث مدمج.',
      h1: 'مصنع نجارة معمارية وأعمال خشبية في جدة، السعودية',
      lead: 'مكونات خشبية مقطوعة بتقنية CNC تتحول إلى أبواب وألواح جدارية ومكاتب استقبال وخزائن وأثاث مدمج، من ورشة واحدة وبرنامج جودة واحد.',
      answerTitle: 'نجارة تُصنع لتناسب المبنى',
      answer: [
        'النجارة هي الأعمال الخشبية الثابتة والمركّبة في المبنى: الأبواب والإطارات والألواح الجدارية ومكاتب الاستقبال والخزائن والدواليب والأثاث المدمج. وتبدأ النجارة الجيدة بمخططات مقاسة ومكونات دقيقة وورشة مضبوطة، لأن القطع النهائية يجب أن تناسب جدرانًا لا تكون مستقيمة تمامًا. يعمل مصنعنا في جدة وفق مخططات المعماري، ويقطع المكونات بماكينات CNC، ويجمّعها ويشطّبها تحت سقف واحد، ثم يركّبها الفريق الذي صنعها. وتصنع الورشة نفسها الخزائن السريرية والنجارة المقاومة للعدوى لغرفنا الطبية وحزم التصميم الداخلي للفنادق والمكاتب والمباني العامة، فتبقى التشطيبات والمقاطع والتفاوتات متسقة في المشروع كله.',
        'وللمنتجات المفردة راجع [الأبواب الخشبية](manufacturing/wooden-doors) و[الكوريان والأسطح الصلبة](manufacturing/corian-solid-surface).',
      ],
      table: null,
      usesTitle: 'أين نركّبها',
      uses: ['المستشفيات والعيادات والمراكز الطبية', 'الفنادق والمنتجعات', 'المكاتب والأبراج التجارية', 'التجزئة وتصميمات المطاعم والمقاهي', 'المباني العامة والمؤسسية'],
      deliverTitle: 'ما نصنعه',
      deliver: [
        'ألواح وكسوات جدارية',
        'مكاتب استقبال وخزائن',
        'أثاث مدمج ودواليب',
        'خزائن وتخزين سريري',
        'أبواب وإطارات وبطانات وكرانيش',
        'أخذ المقاسات والتصنيع في الورشة والتركيب في الموقع',
      ],
      process: [
        { t: 'القياس والتفصيل', d: 'قياسات في الموقع ومخططات تنفيذية لكل قطعة.' },
        { t: 'القص والتجميع', d: 'مكونات مقطوعة بتقنية CNC تُجمَّع في الورشة.' },
        { t: 'التشطيب', d: 'التشطيب في الورشة وفق العينة المعتمدة.' },
        { t: 'التركيب والملاحظات', d: 'يركّب الفريق الذي صنع القطع في الموقع، ثم معالجة الملاحظات حتى التسليم.' },
      ],
      ctaTitle: 'تخطط لحزمة تصميم داخلي؟',
      ctaText: 'أرسل لنا المخططات وسنرد بعرض وبرنامج زمني ومدد توريد.',
    },
  },
];
