/* Hospital-interiors pages (parent: the healthcare-contractor hub): fit-out, OR ceilings, walls and
 * panels, hermetic doors. Written from the scope the client confirmed; each page explains the work in
 * general terms and states only that EGC provides / installs it. */
const DO = 'healthcare-contractor/medical-doors';
const SH = 'healthcare-contractor/radiation-shielding';

export const INTERIORS = [
  {
    key: 'hospitalFitOut',
    segment: 'healthcare-contractor/hospital-fit-out',
    parent: 'hub',
    group: 'interiors',
    icon: 'hospital',
    related: ['orCeilings', 'wallPanels', 'hermeticDoors', 'medicalGas', 'woodenDoors'],
    en: {
      name: 'Hospital Fit-Out',
      title: 'Hospital Fit-Out Contractor in Saudi Arabia | EGC',
      description: 'Hospital and clinic fit-out contractor in Saudi Arabia: partitions, ceilings, doors, finishes, building services and specialist rooms delivered under one contract.',
      short: 'Partitions, ceilings, doors, finishes, services and specialist rooms under one contract.',
      h1: 'Hospital fit-out contractor in Saudi Arabia',
      lead: 'Fit-out of hospital departments, clinics and medical centres: partitions and ceilings, doors, finishes and joinery, the building services and the specialist rooms inside them, coordinated under one contract.',
      answerTitle: 'What a hospital fit-out involves',
      answer: [
        'A hospital fit-out turns a shell, or an existing department, into a working clinical space. It is more than finishes. The layout is driven by clinical workflow and infection control, partitions and ceilings must be sealed and cleanable, floors and walls must withstand daily cleaning, and the building services, such as medical gas, HVAC, fire protection, power and nurse call, must be installed so the spaces meet clinical requirements. Specialist rooms such as imaging suites and operating rooms add shielding, special doors and tighter environmental control. EGC carries out hospital fit-outs as a healthcare contractor with its own factory for doors, joinery and surfaces: the finishing trades, the building services and the specialist rooms are coordinated under one contract and one programme, which means fewer interfaces between packages and one team accountable for the result. Works inside live hospitals are phased, with dust and infection-control measures.',
        `The work draws on the rest of what we do: [medical gas](healthcare-contractor/medical-gas-systems), [HVAC](healthcare-contractor/healthcare-hvac), [fire protection](healthcare-contractor/fire-protection), [nurse call installation](healthcare-contractor/nurse-call-installation), [operating-room ceilings](healthcare-contractor/operating-room-ceilings), [wall panels](healthcare-contractor/hygienic-wall-panels) and [doors](${DO}).`,
      ],
      table: {
        title: 'What a hospital fit-out covers',
        head: ['Package', 'What it includes'],
        rows: [
          ['Partitions, walls and ceilings', 'Hygienic wall systems and sealed or cleanable ceilings'],
          ['Doors and joinery', 'Medical, hermetic and wooden doors, counters, casework and nurse stations'],
          ['Floors and finishes', 'Surfaces that withstand daily cleaning and disinfection'],
          ['Building services', 'Medical gas, HVAC, fire protection, power and nurse call'],
          ['Specialist rooms', 'Imaging suites and operating rooms, with shielding and controlled environments'],
        ],
      },
      usesTitle: 'Where we carry out fit-outs',
      uses: ['Hospital departments and wards', 'Imaging departments', 'Operating theatres', 'Clinics and medical centres', 'Works inside live hospitals'],
      deliverTitle: 'What we deliver',
      deliver: [
        'Partitions, walls and ceilings',
        'Doors, joinery, counters and nurse stations',
        'Floor and wall finishes',
        'Medical gas, HVAC, fire protection and nurse call installation',
        'Specialist rooms: imaging and operating rooms',
        'Phasing and infection-control measures for live hospitals',
      ],
      process: [
        { t: 'Define the scope', d: 'We agree the departments, the packages and the programme in one scope.' },
        { t: 'Coordinate', d: 'Drawings and services are coordinated once, before work starts.' },
        { t: 'Build and install', d: 'Our crews and our factory deliver the work, phased around the live hospital where needed.' },
        { t: 'Test and hand over', d: 'Systems are tested and commissioned, then handed over with records.' },
      ],
      ctaTitle: 'Planning a hospital fit-out?',
      ctaText: 'Share the scope and the programme and we will respond with a proposal.',
    },
    ar: {
      name: 'تجهيز المستشفيات',
      title: 'مقاول تجهيز مستشفيات وعيادات في السعودية | EGC',
      description: 'مقاول تجهيز مستشفيات وعيادات في السعودية: قواطع وأسقف وأبواب وتشطيبات وخدمات المبنى والغرف المتخصصة بعقد واحد.',
      short: 'قواطع وأسقف وأبواب وتشطيبات وخدمات وغرف متخصصة بعقد واحد.',
      h1: 'مقاول تجهيز مستشفيات في السعودية',
      lead: 'تجهيز أقسام المستشفيات والعيادات والمراكز الطبية: قواطع وأسقف وأبواب وتشطيبات ونجارة، وخدمات المبنى والغرف المتخصصة بداخلها، منسّقة بعقد واحد.',
      answerTitle: 'ما الذي يتضمنه تجهيز المستشفى',
      answer: [
        'يحوّل تجهيز المستشفى الهيكل الخام أو القسم القائم إلى حيز سريري عامل. وهو أكثر من تشطيبات: فالتخطيط تحكمه مسارات العمل السريرية ومكافحة العدوى، ويجب أن تكون القواطع والأسقف محكمة وسهلة التنظيف، وأن تتحمل الأرضيات والجدران التنظيف اليومي، وأن تُركَّب خدمات المبنى، كالغازات الطبية والتكييف والحماية من الحريق والكهرباء ونداء الممرضات، بما يحقق المتطلبات السريرية. وتضيف الغرف المتخصصة، كأجنحة التصوير وغرف العمليات، التدريع والأبواب الخاصة وتحكمًا أدق بالبيئة. وتنفذ EGC تجهيز المستشفيات بصفتها مقاول مشاريع صحية لديه مصنعه الخاص للأبواب والنجارة والأسطح: تُنسَّق أعمال التشطيب وخدمات المبنى والغرف المتخصصة بعقد واحد وبرنامج زمني واحد، فتقل نقاط التماس بين الحزم ويتحمل فريق واحد مسؤولية النتيجة. وتُنفَّذ الأعمال داخل المستشفيات العاملة على مراحل مع إجراءات لعزل الغبار ومكافحة العدوى.',
        `ويستفيد العمل من بقية ما نقدمه: [الغازات الطبية](healthcare-contractor/medical-gas-systems) و[التكييف والتهوية](healthcare-contractor/healthcare-hvac) و[الحماية من الحريق](healthcare-contractor/fire-protection) و[تركيب أنظمة نداء الممرضات](healthcare-contractor/nurse-call-installation) و[أسقف غرف العمليات](healthcare-contractor/operating-room-ceilings) و[الألواح الجدارية](healthcare-contractor/hygienic-wall-panels) و[الأبواب](${DO}).`,
      ],
      table: {
        title: 'ما يغطيه تجهيز المستشفى',
        head: ['الحزمة', 'ما تتضمنه'],
        rows: [
          ['القواطع والجدران والأسقف', 'أنظمة جدران صحية وأسقف محكمة أو سهلة التنظيف'],
          ['الأبواب والنجارة', 'أبواب طبية وهيرمتية وخشبية ومنضدات وخزائن ومحطات تمريض'],
          ['الأرضيات والتشطيبات', 'أسطح تتحمل التنظيف والتطهير اليومي'],
          ['خدمات المبنى', 'الغازات الطبية والتكييف والحماية من الحريق والكهرباء ونداء الممرضات'],
          ['الغرف المتخصصة', 'أجنحة التصوير وغرف العمليات، بالتدريع وببيئات مضبوطة'],
        ],
      },
      usesTitle: 'أين ننفذ التجهيز',
      uses: ['أقسام المستشفيات والأجنحة', 'أقسام التصوير', 'غرف العمليات', 'العيادات والمراكز الطبية', 'الأعمال داخل المستشفيات العاملة'],
      deliverTitle: 'ما نقدمه',
      deliver: [
        'القواطع والجدران والأسقف',
        'الأبواب والنجارة والمنضدات ومحطات التمريض',
        'تشطيبات الأرضيات والجدران',
        'تركيب الغازات الطبية والتكييف والحماية من الحريق ونداء الممرضات',
        'الغرف المتخصصة: التصوير والعمليات',
        'مراحل العمل وإجراءات مكافحة العدوى في المستشفيات العاملة',
      ],
      process: [
        { t: 'تحديد النطاق', d: 'نتفق على الأقسام والحزم والبرنامج الزمني في نطاق واحد.' },
        { t: 'التنسيق', d: 'تُنسَّق المخططات والخدمات مرة واحدة قبل بدء العمل.' },
        { t: 'البناء والتركيب', d: 'تنفذ كوادرنا ومصنعنا العمل، على مراحل حول المستشفى العامل عند الحاجة.' },
        { t: 'الاختبار والتسليم', d: 'تُختبر الأنظمة وتُشغَّل ثم تُسلَّم مع السجلات.' },
      ],
      ctaTitle: 'تخطط لتجهيز مستشفى؟',
      ctaText: 'شاركنا النطاق والبرنامج الزمني وسنرد بعرض.',
    },
  },

  {
    key: 'orCeilings',
    segment: 'healthcare-contractor/operating-room-ceilings',
    parent: 'hub',
    group: 'interiors',
    icon: 'ceiling',
    related: ['hospitalFitOut', 'wallPanels', 'hermeticDoors', 'hvac'],
    en: {
      name: 'Operating-Room Ceilings',
      title: 'Operating Room Ceiling Systems in Saudi Arabia | EGC',
      description: 'Sealed, cleanable ceilings for operating rooms and clean areas in Saudi Arabia, integrated with air diffusers, lights and services, installed by EGC.',
      short: 'Sealed, cleanable ceilings integrated with diffusers, lights and services.',
      h1: 'Operating-room ceiling systems in Saudi Arabia',
      lead: 'Sealed, cleanable ceilings for operating rooms and other clean areas, installed with the openings for air diffusers, lights and pendants coordinated from the start.',
      flow: {
        title: 'What the ceiling has to carry',
        steps: ['A sealed, smooth ceiling surface', 'Air diffusers set into the ceiling', 'Surgical lights and pendants fixed above', 'Access for maintenance without breaking the seal'],
      },
      answerTitle: 'Why an operating-room ceiling is special',
      answer: [
        'An operating-room ceiling is part of the room’s infection-control system. It is typically a smooth, non-porous, sealed surface with few joints, so that it can be cleaned and does not shed particles into the room. It also separates the clean room from the services above, which helps hold the room’s air pressure, and it carries openings for the air-supply diffusers, surgical lights, pendants and other equipment, all of which must be set in without leaving gaps. Maintenance access has to be planned so that servicing the equipment above does not break the seal. EGC installs operating-room ceilings as part of its hospital fit-out work, coordinating the ceiling with the HVAC, lighting, medical gas and fire protection that pass through or sit above it, and with the walls, doors and finishes of the room.',
        'The ceiling works together with [HVAC](healthcare-contractor/healthcare-hvac), [wall panels](healthcare-contractor/hygienic-wall-panels) and [hermetic doors](healthcare-contractor/hermetic-doors) as part of a complete [hospital fit-out](healthcare-contractor/hospital-fit-out).',
      ],
      table: {
        title: 'What an operating-room ceiling has to do',
        head: ['Requirement', 'Why it matters'],
        rows: [
          ['Smooth, sealed surface', 'Can be cleaned and does not collect or shed particles'],
          ['Few joints, sealed openings', 'Helps hold room pressure and keeps services above separated from the clean room'],
          ['Openings for diffusers, lights and pendants', 'The equipment must be set in without gaps'],
          ['Maintenance access', 'Servicing above the ceiling must not break the seal'],
        ],
      },
      usesTitle: 'Where we install them',
      uses: ['Operating theatres', 'Procedure and interventional rooms', 'Clean rooms and sterile areas', 'Intensive-care and isolation rooms'],
      deliverTitle: 'What we install',
      deliver: [
        'Sealed, cleanable ceiling systems',
        'Openings and framing for air diffusers',
        'Provisions for surgical lights and pendants',
        'Sealed access panels for maintenance',
        'Coordination with HVAC, lighting, medical gas and fire protection',
        'Finishing and sealing of junctions with walls',
      ],
      process: [
        { t: 'Coordinate the ceiling', d: 'Diffusers, lights, pendants and services are located on one coordinated drawing.' },
        { t: 'Install the ceiling', d: 'The ceiling system is installed with sealed joints and openings.' },
        { t: 'Seal and finish', d: 'Junctions with walls and around fittings are sealed and finished.' },
        { t: 'Inspect and hand over', d: 'The ceiling is inspected for continuity and handed over.' },
      ],
      ctaTitle: 'Fitting out operating rooms?',
      ctaText: 'Send us the drawings and the specification and we will respond with a proposal.',
    },
    ar: {
      name: 'أسقف غرف العمليات',
      title: 'أنظمة أسقف غرف العمليات في السعودية | EGC',
      description: 'أسقف محكمة وسهلة التنظيف لغرف العمليات والمناطق النظيفة في السعودية، متكاملة مع ناشرات الهواء والإضاءة والخدمات، تركّبها EGC.',
      short: 'أسقف محكمة وسهلة التنظيف متكاملة مع الناشرات والإضاءة والخدمات.',
      h1: 'أنظمة أسقف غرف العمليات في السعودية',
      lead: 'أسقف محكمة وسهلة التنظيف لغرف العمليات والمناطق النظيفة الأخرى، تُركَّب مع تنسيق فتحات ناشرات الهواء والإضاءة والحوامل المعلّقة منذ البداية.',
      flow: {
        title: 'ما الذي يحمله السقف',
        steps: ['سطح سقف أملس ومحكم', 'ناشرات هواء مدمجة في السقف', 'إضاءة جراحية وحوامل معلّقة مثبتة فوقه', 'فتحات صيانة لا تكسر الإحكام'],
      },
      answerTitle: 'لماذا يختلف سقف غرفة العمليات',
      answer: [
        'سقف غرفة العمليات جزء من منظومة مكافحة العدوى في الغرفة. وهو عادةً سطح أملس غير مسامي ومحكم بوصلات قليلة، ليسهل تنظيفه ولا يطلق جسيمات في الغرفة. ويفصل كذلك الغرفة النظيفة عن الخدمات التي فوقه، مما يساعد على الحفاظ على ضغط هواء الغرفة، ويحمل فتحات ناشرات هواء التغذية والإضاءة الجراحية والحوامل المعلّقة وغيرها من المعدات، وكلها يجب أن تُركَّب دون ترك فجوات. ويجب تخطيط فتحات الصيانة بحيث لا تكسر صيانة المعدات في الأعلى الإحكام. وتركّب EGC أسقف غرف العمليات ضمن أعمال تجهيز المستشفيات، وتنسّق السقف مع التكييف والإضاءة والغازات الطبية والحماية من الحريق التي تعبره أو تقع فوقه، ومع جدران الغرفة وأبوابها وتشطيباتها.',
        'ويعمل السقف مع [التكييف والتهوية](healthcare-contractor/healthcare-hvac) و[الألواح الجدارية](healthcare-contractor/hygienic-wall-panels) و[الأبواب الهيرمتية](healthcare-contractor/hermetic-doors) ضمن [تجهيز مستشفى](healthcare-contractor/hospital-fit-out) متكامل.',
      ],
      table: {
        title: 'ما الذي يجب أن يحققه سقف غرفة العمليات',
        head: ['المتطلب', 'لماذا يهم'],
        rows: [
          ['سطح أملس ومحكم', 'يمكن تنظيفه ولا يجمع الجسيمات أو يطلقها'],
          ['وصلات قليلة وفتحات محكمة', 'يساعد على الحفاظ على ضغط الغرفة ويفصل الخدمات في الأعلى عن الغرفة النظيفة'],
          ['فتحات للناشرات والإضاءة والحوامل المعلّقة', 'يجب تركيب المعدات دون فجوات'],
          ['فتحات الصيانة', 'يجب ألا تكسر الصيانة فوق السقف الإحكام'],
        ],
      },
      usesTitle: 'أين نركّبها',
      uses: ['غرف العمليات', 'غرف الإجراءات والتدخل', 'الغرف النظيفة والمناطق المعقمة', 'غرف العناية المركزة والعزل'],
      deliverTitle: 'ما نركّبه',
      deliver: [
        'أنظمة أسقف محكمة وسهلة التنظيف',
        'فتحات وهياكل لناشرات الهواء',
        'تجهيزات للإضاءة الجراحية والحوامل المعلّقة',
        'فتحات صيانة محكمة',
        'التنسيق مع التكييف والإضاءة والغازات الطبية والحماية من الحريق',
        'تشطيب وإحكام الوصلات مع الجدران',
      ],
      process: [
        { t: 'تنسيق السقف', d: 'تُحدَّد الناشرات والإضاءة والحوامل والخدمات على مخطط منسّق واحد.' },
        { t: 'تركيب السقف', d: 'يُركَّب نظام السقف بوصلات وفتحات محكمة.' },
        { t: 'الإحكام والتشطيب', d: 'تُحكَم وتُشطَّب الوصلات مع الجدران وحول التجهيزات.' },
        { t: 'الفحص والتسليم', d: 'يُفحص السقف للتأكد من استمراريته ثم يُسلَّم.' },
      ],
      ctaTitle: 'تجهّز غرف عمليات؟',
      ctaText: 'أرسل لنا المخططات والمواصفات وسنرد بعرض.',
    },
  },

  {
    key: 'wallPanels',
    segment: 'healthcare-contractor/hygienic-wall-panels',
    parent: 'hub',
    group: 'interiors',
    icon: 'panel',
    related: ['hospitalFitOut', 'orCeilings', 'surfaces', 'hermeticDoors'],
    en: {
      name: 'Walls & Wall Panels',
      title: 'Hospital Wall Panels & Partitions in Saudi Arabia | EGC',
      description: 'Hygienic wall panels and partitions for hospitals, operating rooms and clean areas in Saudi Arabia, with smooth, cleanable surfaces and sealed joints.',
      short: 'Hygienic wall panels and partitions with smooth, cleanable surfaces and sealed joints.',
      h1: 'Hospital walls, partitions and wall panels in Saudi Arabia',
      lead: 'Partitions and hygienic wall panels for hospitals, operating rooms and clean areas, with smooth, cleanable surfaces and sealed joints, installed to the project specification.',
      answerTitle: 'What hospital walls have to do',
      answer: [
        'Walls in a hospital take more punishment and need more care than walls elsewhere. They are cleaned and disinfected often, struck by trolleys and beds, and in clinical areas they must not give contamination somewhere to hide. Hygienic wall systems therefore use smooth, non-porous panels with sealed or tightly controlled joints, finished so that they can be wiped down end to end. In operating rooms and clean areas, the walls form part of the sealed envelope that holds the room’s air pressure. In imaging rooms the wall build-up also carries the lead or RF shielding, so the wall and the shield are built together. EGC installs partitions and wall panels as part of its hospital fit-out work, coordinating them with the ceilings, doors, services and shielding, and with the finishes and joinery from its own factory.',
        `Walls and panels are part of a complete [hospital fit-out](healthcare-contractor/hospital-fit-out) and are coordinated with [operating-room ceilings](healthcare-contractor/operating-room-ceilings), [doors](${DO}) and, in imaging rooms, the [shielding](${SH}).`,
      ],
      table: {
        title: 'What hospital wall systems have to deliver',
        head: ['Requirement', 'Why it matters'],
        rows: [
          ['Smooth, non-porous surface', 'Can be wiped and disinfected without absorbing contamination'],
          ['Sealed or controlled joints', 'Leaves no crevices where contamination can collect'],
          ['Impact resistance', 'Withstands trolleys, beds and equipment'],
          ['Services and shielding built in', 'Openings, lead or RF shielding and fixings are built into the wall, not added later'],
        ],
      },
      usesTitle: 'Where we install them',
      uses: ['Operating rooms and clean areas', 'Patient rooms and wards', 'Imaging rooms', 'Corridors and public areas', 'Laboratories and pharmacies'],
      deliverTitle: 'What we install',
      deliver: [
        'Partitions and framed walls',
        'Hygienic wall panels and cladding',
        'Sealed joints and junctions',
        'Lead-lined or RF-shielded wall build-ups for imaging rooms',
        'Openings and fixings for services and equipment',
        'Protective rails and corner protection',
      ],
      process: [
        { t: 'Agree the wall types', d: 'We take the specification and agree each wall type, from clinical to shielded.' },
        { t: 'Set out and frame', d: 'Walls are set out and framed with openings and services in place.' },
        { t: 'Fix panels and seal', d: 'Panels are fixed and joints sealed.' },
        { t: 'Inspect and hand over', d: 'Finishes are inspected and handed over.' },
      ],
      ctaTitle: 'Need hospital walls or panels?',
      ctaText: 'Send us the drawings and the specification and we will respond with a proposal.',
    },
    ar: {
      name: 'الجدران والألواح الجدارية',
      title: 'ألواح جدارية وقواطع للمستشفيات في السعودية | EGC',
      description: 'ألواح جدارية صحية وقواطع للمستشفيات وغرف العمليات والمناطق النظيفة في السعودية، بأسطح ملساء سهلة التنظيف ووصلات محكمة.',
      short: 'ألواح جدارية وقواطع صحية بأسطح ملساء سهلة التنظيف ووصلات محكمة.',
      h1: 'جدران وقواطع وألواح جدارية للمستشفيات في السعودية',
      lead: 'قواطع وألواح جدارية صحية للمستشفيات وغرف العمليات والمناطق النظيفة، بأسطح ملساء سهلة التنظيف ووصلات محكمة، تُركَّب وفق مواصفات المشروع.',
      answerTitle: 'ما الذي يجب أن تفعله جدران المستشفى',
      answer: [
        'تتحمل جدران المستشفى أكثر مما تتحمله جدران غيرها وتحتاج عناية أكبر. فهي تُنظَّف وتُعقَّم كثيرًا، وتصطدم بها العربات والأسرّة، ويجب في المناطق السريرية ألا تمنح الملوثات مكانًا تختبئ فيه. ولذلك تستخدم أنظمة الجدران الصحية ألواحًا ملساء غير مسامية بوصلات محكمة أو مضبوطة بدقة، بتشطيب يمكن مسحه من طرفه إلى طرفه. وفي غرف العمليات والمناطق النظيفة تشكّل الجدران جزءًا من الغلاف المحكم الذي يحافظ على ضغط هواء الغرفة. وفي غرف التصوير يحمل بناء الجدار كذلك التدريع بالرصاص أو ضد الترددات الراديوية، فيُبنى الجدار والدرع معًا. وتركّب EGC القواطع والألواح الجدارية ضمن أعمال تجهيز المستشفيات، وتنسّقها مع الأسقف والأبواب والخدمات والتدريع، ومع التشطيبات والنجارة من مصنعها.',
        `والجدران والألواح جزء من [تجهيز المستشفى](healthcare-contractor/hospital-fit-out) المتكامل وتُنسَّق مع [أسقف غرف العمليات](healthcare-contractor/operating-room-ceilings) و[الأبواب](${DO}) و[التدريع](${SH}) في غرف التصوير.`,
      ],
      table: {
        title: 'ما يجب أن تحققه أنظمة جدران المستشفيات',
        head: ['المتطلب', 'لماذا يهم'],
        rows: [
          ['سطح أملس غير مسامي', 'يمكن مسحه وتعقيمه دون أن يمتص الملوثات'],
          ['وصلات محكمة أو مضبوطة', 'لا يترك شقوقًا تتجمع فيها الملوثات'],
          ['مقاومة الصدمات', 'يتحمل العربات والأسرّة والمعدات'],
          ['الخدمات والتدريع مدمجة', 'تُبنى الفتحات والتدريع بالرصاص أو ضد الترددات الراديوية والتثبيتات في الجدار لا إضافةً لاحقة'],
        ],
      },
      usesTitle: 'أين نركّبها',
      uses: ['غرف العمليات والمناطق النظيفة', 'غرف المرضى والأجنحة', 'غرف التصوير', 'الممرات والمناطق العامة', 'المختبرات والصيدليات'],
      deliverTitle: 'ما نركّبه',
      deliver: [
        'القواطع والجدران المؤطرة',
        'ألواح وكسوات جدارية صحية',
        'وصلات وتقاطعات محكمة',
        'جدران مبطنة بالرصاص أو مدرّعة ضد الترددات الراديوية لغرف التصوير',
        'فتحات وتثبيتات للخدمات والمعدات',
        'حواجز حماية وحماية للزوايا',
      ],
      process: [
        { t: 'اعتماد أنواع الجدران', d: 'نأخذ المواصفات ونتفق على كل نوع جدار، من السريري إلى المدرّع.' },
        { t: 'التحديد والتأطير', d: 'تُحدَّد الجدران وتُؤطَّر مع الفتحات والخدمات في مواضعها.' },
        { t: 'تثبيت الألواح والإحكام', d: 'تُثبَّت الألواح وتُحكَم الوصلات.' },
        { t: 'الفحص والتسليم', d: 'تُفحص التشطيبات وتُسلَّم.' },
      ],
      ctaTitle: 'تحتاج جدرانًا أو ألواحًا للمستشفى؟',
      ctaText: 'أرسل لنا المخططات والمواصفات وسنرد بعرض.',
    },
  },

  {
    key: 'hermeticDoors',
    segment: 'healthcare-contractor/hermetic-doors',
    parent: 'hub',
    group: 'interiors',
    icon: 'door',
    related: ['doors', 'orCeilings', 'wallPanels', 'hospitalFitOut'],
    en: {
      name: 'Hermetic Doors',
      title: 'Hermetic Sliding Doors for Hospitals in Saudi Arabia | EGC',
      description: 'Hermetic sliding doors for operating rooms and clean areas in Saudi Arabia: sealed, easy-to-clean automatic doors, installed and commissioned by EGC.',
      short: 'Sealed, easy-to-clean automatic sliding doors for operating rooms and clean areas.',
      h1: 'Hermetic sliding doors for hospitals in Saudi Arabia',
      lead: 'Sealed, easy-to-clean automatic sliding doors for operating rooms, intensive-care units and other controlled areas, installed and commissioned with the walls and ceilings around them.',
      answerTitle: 'What a hermetic door does',
      answer: [
        'A hermetic door seals the opening it closes. Where a room is held at a different air pressure from its surroundings, as an operating room or an isolation room is, a door that leaks air defeats the purpose of the ventilation. A hermetic sliding door closes against gaskets so that air does not pass, opens automatically so that staff with sterile hands do not need to touch it, and presents a smooth, flush surface that can be wiped clean, often with a vision panel so staff can see through. Because the door is part of the room’s sealed envelope, it must be installed together with the wall and the ceiling around it. EGC provides and installs hermetic sliding doors as part of its medical doors and hospital fit-out work, setting out the opening with the walls, fitting and sealing the door, and commissioning the operator, sensors and interlocks.',
        `Hermetic doors are one kind of [medical door](${DO}); the same team also installs lead-lined and RF-shielded doors for imaging rooms and makes [wooden doors](manufacturing/wooden-doors) for the rest of the building.`,
      ],
      table: {
        title: 'Hermetic sliding doors and other hospital doors',
        head: ['Door', 'Main job', 'Typical place'],
        rows: [
          ['Hermetic sliding door', 'Seal the opening and operate without touch', 'Operating rooms, intensive care, clean areas'],
          ['Lead-lined door', 'Match the lead in the wall around it', 'CT, PET-CT and X-ray rooms'],
          ['RF-shielded door', 'Keep radio-frequency interference out', 'MRI scan rooms'],
          ['Wooden door', 'Privacy, appearance and durability', 'Patient rooms, offices, corridors'],
        ],
      },
      usesTitle: 'Where hermetic doors are used',
      uses: ['Operating theatres', 'Intensive-care and isolation rooms', 'Clean rooms and sterile areas', 'Procedure rooms', 'Laboratories'],
      deliverTitle: 'What we provide and install',
      deliver: [
        'Hermetic automatic sliding doors',
        'Sealing gaskets and flush, cleanable finishes',
        'Vision panels',
        'Touch-free operation and sensors',
        'Interlocks and access control where specified',
        'Installation, sealing and commissioning with the walls and ceiling',
      ],
      process: [
        { t: 'Set out the opening', d: 'The opening is set out with the walls and ceiling so the seal is continuous.' },
        { t: 'Install and seal', d: 'The door is hung, sealed and aligned.' },
        { t: 'Commission', d: 'Operator, sensors and interlocks are commissioned and tested.' },
        { t: 'Hand over', d: 'The door is handed over with operating instructions.' },
      ],
      ctaTitle: 'Need hermetic doors?',
      ctaText: 'Send us the door schedule and the specification and we will respond with a proposal.',
    },
    ar: {
      name: 'الأبواب الهيرمتية',
      title: 'أبواب انزلاقية هيرمتية للمستشفيات في السعودية | EGC',
      description: 'أبواب انزلاقية هيرمتية لغرف العمليات والمناطق النظيفة في السعودية: أبواب آلية محكمة وسهلة التنظيف، تركّبها EGC وتشغّلها.',
      short: 'أبواب انزلاقية آلية محكمة وسهلة التنظيف لغرف العمليات والمناطق النظيفة.',
      h1: 'أبواب انزلاقية هيرمتية للمستشفيات في السعودية',
      lead: 'أبواب انزلاقية آلية محكمة وسهلة التنظيف لغرف العمليات ووحدات العناية المركزة والمناطق المضبوطة الأخرى، تُركَّب وتُشغَّل مع الجدران والأسقف المحيطة بها.',
      answerTitle: 'ما وظيفة الباب الهيرمتي',
      answer: [
        'يحكم الباب الهيرمتي الفتحة التي يغلقها. فحيث تُحفظ الغرفة بضغط هواء مختلف عن محيطها، كغرفة العمليات أو غرفة العزل، فإن الباب الذي يسرّب الهواء يُبطل الغرض من التهوية. ويُغلق الباب الانزلاقي الهيرمتي على حشيات فلا يمر الهواء، ويُفتح آليًا فلا يحتاج الطاقم ذو الأيدي المعقمة إلى لمسه، ويقدّم سطحًا أملس مستويًا يسهل مسحه، وغالبًا بلوحة رؤية ليرى الطاقم عبره. ولأن الباب جزء من الغلاف المحكم للغرفة فيجب تركيبه مع الجدار والسقف المحيطين به. وتوفّر EGC الأبواب الانزلاقية الهيرمتية وتركّبها ضمن أعمال الأبواب الطبية وتجهيز المستشفيات، فتحدد الفتحة مع الجدران وتركّب الباب وتحكم عزله وتشغّل المشغّل والحساسات والأقفال التبادلية.',
        `والأبواب الهيرمتية نوع من [الأبواب الطبية](${DO})؛ ويركّب الفريق نفسه أبوابًا مبطنة بالرصاص ومدرّعة ضد الترددات الراديوية لغرف التصوير، ويصنع [أبوابًا خشبية](manufacturing/wooden-doors) لبقية المبنى.`,
      ],
      table: {
        title: 'الأبواب الهيرمتية وأبواب المستشفيات الأخرى',
        head: ['الباب', 'وظيفته الرئيسية', 'مكانه المعتاد'],
        rows: [
          ['باب انزلاقي هيرمتي', 'إحكام الفتحة والتشغيل دون لمس', 'غرف العمليات والعناية المركزة والمناطق النظيفة'],
          ['باب مبطن بالرصاص', 'مطابقة الرصاص في الجدار المحيط', 'غرف الأشعة المقطعية وPET-CT والأشعة السينية'],
          ['باب مدرّع ضد الترددات الراديوية', 'منع تداخل الترددات الراديوية', 'غرف فحص الرنين المغناطيسي'],
          ['باب خشبي', 'الخصوصية والمظهر والمتانة', 'غرف المرضى والمكاتب والممرات'],
        ],
      },
      usesTitle: 'أين تُستخدم الأبواب الهيرمتية',
      uses: ['غرف العمليات', 'غرف العناية المركزة والعزل', 'الغرف النظيفة والمناطق المعقمة', 'غرف الإجراءات', 'المختبرات'],
      deliverTitle: 'ما نوفره ونركّبه',
      deliver: [
        'أبواب انزلاقية آلية هيرمتية',
        'حشيات إحكام وتشطيبات مستوية سهلة التنظيف',
        'لوحات رؤية',
        'تشغيل دون لمس وحساسات',
        'أقفال تبادلية وتحكم بالدخول حيث تُحدَّد',
        'التركيب والإحكام والتشغيل مع الجدران والسقف',
      ],
      process: [
        { t: 'تحديد الفتحة', d: 'تُحدَّد الفتحة مع الجدران والسقف ليبقى الإحكام متصلًا.' },
        { t: 'التركيب والإحكام', d: 'يُعلَّق الباب ويُحكَم ويُضبط.' },
        { t: 'التشغيل', d: 'يُشغَّل المشغّل والحساسات والأقفال التبادلية وتُختبر.' },
        { t: 'التسليم', d: 'يُسلَّم الباب مع تعليمات التشغيل.' },
      ],
      ctaTitle: 'تحتاج أبوابًا هيرمتية؟',
      ctaText: 'أرسل لنا جدول الأبواب والمواصفات وسنرد بعرض.',
    },
  },
];
