/* Imaging-room pages (parent: the healthcare-contractor hub). One page per room type, because
 * that is how hospitals search: "MRI room construction", "CT room lead lining", "PET-CT room design".
 * Plain data, no JSX: scripts/ import it directly. Body links use [label](route-segment). */
const SH = 'healthcare-contractor/radiation-shielding';
const DO = 'healthcare-contractor/medical-doors';
const ME = 'healthcare-contractor/healthcare-mep';
const SU = 'healthcare-contractor/infection-control-surfaces';

export const ROOMS = [
  {
    key: 'mriRoom',
    segment: 'healthcare-contractor/mri-room-construction',
    parent: 'hub',
    group: 'specialist',
    icon: 'magnet',
    image: 'hero-bg',
    imagePosition: 'center 45%',
    related: ['shielding', 'doors', 'mep', 'ctRoom', 'hospitalFitOut'],
    en: {
      name: 'MRI Room Construction',
      title: 'MRI Room Construction & Shielding in Saudi Arabia | EGC',
      description: 'MRI room construction in Saudi Arabia: RF and magnetic shielding, RF doors and windows, waveguides and quench pipe, built to the manufacturer’s site-planning guide.',
      short: 'RF shield, RF door and window, waveguides and quench pipe, ready for the scanner.',
      h1: 'MRI room construction and shielding contractor in Saudi Arabia',
      lead: 'We build MRI suites from the manufacturer’s site-planning guide: the RF shield, magnetic shielding where it is specified, the RF door and window, the services that cross the shield and the finishes, ready for the scanner installation team.',
      imageAlt: 'EGC crew installing shielding panels in an MRI suite',
      answerTitle: 'What goes into an MRI room',
      answer: [
        'An MRI room is a controlled environment built around the scanner’s demands. The scan room is enclosed in a continuous radio-frequency shield, usually copper, aluminium or galvanised steel, so outside signals cannot create artefacts in the image. Where the manufacturer specifies it, steel plate contains the magnet’s fringe field so it does not reach areas that are sensitive to it. An RF-shielded door and window let staff work and watch the patient without breaking the shield, and every pipe, duct and cable that crosses it passes through a waveguide, honeycomb vent or filter. A quench pipe carries helium gas safely outside if the magnet quenches. EGC builds all of this from the manufacturer’s site-planning guide for the exact scanner model, coordinates with its installation team and supports the RF attenuation test before the room is released.',
        `The control room, equipment room and patient areas around the scan room belong to the same package: [radiation and magnetic shielding](${SH}), [RF-shielded doors](${DO}), [healthcare MEP](${ME}) and [clinical surfaces](${SU}).`,
      ],
      table: {
        title: 'The four MRI safety zones',
        head: ['Zone', 'Who can be there', 'Typical space'],
        rows: [
          ['Zone I', 'The general public, with free access', 'Entrance and public areas'],
          ['Zone II', 'Patients and staff, under supervision', 'Reception, patient screening and changing'],
          ['Zone III', 'Screened, authorised personnel only, with controlled access', 'Control room and the areas next to the scan room'],
          ['Zone IV', 'Only screened people accompanied by trained MRI staff', 'The scan room that contains the magnet'],
        ],
      },
      usesTitle: 'Spaces in an MRI suite',
      uses: ['Scan room (Zone IV)', 'Control room', 'Equipment (technical) room', 'Patient preparation and changing', 'Screening and waiting area'],
      deliverTitle: 'What we build',
      deliver: [
        'RF (Faraday cage) shielding of the scan room',
        'Magnetic shielding where the manufacturer specifies it',
        'RF-shielded door and RF window',
        'Waveguides, honeycomb vents and filters for every penetration',
        'Quench pipe routing to the outside',
        'Non-magnetic finishes and fittings inside the scan room',
      ],
      process: [
        { t: 'Read the siting guide', d: 'We work from the manufacturer’s guide for the exact scanner model and the physicist’s requirements.' },
        { t: 'Detail the shield', d: 'Shop drawings locate every seam, door, window and penetration before work starts.' },
        { t: 'Build and check continuity', d: 'Our crews install the shield and check it is continuous before finishes close it in.' },
        { t: 'Test and hand over', d: 'We support the RF attenuation test, then release the room to the scanner installation team.' },
      ],
      ctaTitle: 'Planning an MRI suite?',
      ctaText: 'Send us the scanner model and the site and we will tell you what the room needs and how we would build it.',
    },
    ar: {
      name: 'إنشاء غرف الرنين المغناطيسي',
      title: 'إنشاء وتدريع غرف الرنين المغناطيسي في السعودية | EGC',
      description: 'إنشاء غرف الرنين المغناطيسي في السعودية: تدريع ضد الترددات الراديوية والمجال المغناطيسي، وأبواب ونوافذ مدرّعة، وموجّهات موجية وأنبوب إخماد وفق دليل الشركة المصنِّعة.',
      short: 'درع الترددات الراديوية والباب والنافذة والموجّهات وأنبوب الإخماد، جاهزة لتركيب الجهاز.',
      h1: 'مقاول إنشاء وتدريع غرف الرنين المغناطيسي في السعودية',
      lead: 'نبني غرف الرنين المغناطيسي وفق دليل تخطيط الموقع الصادر عن الشركة المصنِّعة: درع الترددات الراديوية، والتدريع المغناطيسي حيث يُشترط، والباب والنافذة المدرّعان، والخدمات التي تخترق الدرع، والتشطيبات، جاهزة لفريق تركيب الجهاز.',
      imageAlt: 'فريق EGC أثناء تركيب ألواح التدريع في غرفة رنين مغناطيسي',
      answerTitle: 'ما الذي تتكون منه غرفة الرنين المغناطيسي',
      answer: [
        'غرفة الرنين المغناطيسي بيئة محكومة تُبنى حول متطلبات الجهاز. تُحاط غرفة الفحص بدرع متصل ضد الترددات الراديوية، عادةً من النحاس أو الألومنيوم أو الصلب المجلفن، حتى لا تُحدث الإشارات الخارجية تشويشًا في الصورة. وحيث تشترط الشركة المصنِّعة، تحتوي ألواح الصلب المجال المغناطيسي المتسرب حول المغناطيس فلا يصل إلى المناطق الحساسة له. ويتيح الباب والنافذة المدرّعان للطاقم العمل ومراقبة المريض دون كسر الدرع، ويمر كل أنبوب ومجرى وكابل يخترقه عبر موجّه موجي أو فتحة تهوية خلوية أو مرشح. وينقل أنبوب الإخماد غاز الهيليوم بأمان إلى الخارج إذا حدث إخماد للمغناطيس. وتبني EGC ذلك كله وفق دليل تخطيط الموقع للطراز المحدد من الجهاز، وتنسّق مع فريق التركيب لدى الشركة المصنِّعة، وتدعم اختبار توهين الترددات الراديوية قبل تسليم الغرفة.',
        `وتدخل غرفة التحكم وغرفة المعدات ومناطق المرضى حول غرفة الفحص في الحزمة نفسها: [التدريع الإشعاعي والمغناطيسي](${SH}) و[الأبواب المدرّعة](${DO}) و[الأعمال الكهروميكانيكية الطبية](${ME}) و[الأسطح السريرية](${SU}).`,
      ],
      table: {
        title: 'مناطق السلامة الأربع في الرنين المغناطيسي',
        head: ['المنطقة', 'من يمكنه التواجد', 'المساحة المعتادة'],
        rows: [
          ['المنطقة I', 'عامة الناس، بوصول حر', 'المدخل والمناطق العامة'],
          ['المنطقة II', 'المرضى والطاقم تحت الإشراف', 'الاستقبال وفحص المرضى وتغيير الملابس'],
          ['المنطقة III', 'أفراد مخوّلون خضعوا للفحص فقط، مع وصول مضبوط', 'غرفة التحكم والمناطق المجاورة لغرفة الفحص'],
          ['المنطقة IV', 'أشخاص خضعوا للفحص فقط وبصحبة طاقم رنين مدرَّب', 'غرفة الفحص التي تحتوي المغناطيس'],
        ],
      },
      usesTitle: 'المساحات في جناح الرنين المغناطيسي',
      uses: ['غرفة الفحص (المنطقة IV)', 'غرفة التحكم', 'غرفة المعدات (الفنية)', 'تحضير المرضى وتغيير الملابس', 'منطقة الفحص الأولي والانتظار'],
      deliverTitle: 'ما نبنيه',
      deliver: [
        'تدريع غرفة الفحص ضد الترددات الراديوية (قفص فاراداي)',
        'تدريع مغناطيسي حيث تشترطه الشركة المصنِّعة',
        'باب مدرّع ونافذة مدرّعة ضد الترددات الراديوية',
        'موجّهات موجية وفتحات تهوية خلوية ومرشحات لكل اختراق',
        'مسار أنبوب الإخماد إلى الخارج',
        'تشطيبات وتجهيزات غير مغناطيسية داخل غرفة الفحص',
      ],
      process: [
        { t: 'قراءة دليل التخطيط', d: 'نعمل وفق دليل الشركة المصنِّعة للطراز المحدد من الجهاز ومتطلبات الفيزيائي.' },
        { t: 'تفصيل الدرع', d: 'تحدد المخططات التنفيذية كل وصلة وباب ونافذة واختراق قبل بدء العمل.' },
        { t: 'البناء وفحص الاتصال', d: 'تركّب كوادرنا الدرع وتتحقق من اتصاله قبل أن تغطيه التشطيبات.' },
        { t: 'الاختبار والتسليم', d: 'ندعم اختبار توهين الترددات الراديوية ثم نسلّم الغرفة لفريق تركيب الجهاز.' },
      ],
      ctaTitle: 'تخطط لجناح رنين مغناطيسي؟',
      ctaText: 'أرسل لنا طراز الجهاز والموقع، وسنوضح ما تحتاجه الغرفة وكيف سنبنيها.',
    },
  },

  {
    key: 'ctRoom',
    segment: 'healthcare-contractor/ct-room-construction',
    parent: 'hub',
    group: 'specialist',
    icon: 'scan',
    image: 'healthcare-xray',
    imagePosition: 'center 40%',
    related: ['shielding', 'doors', 'petCtRoom', 'xrayRoom', 'mep'],
    en: {
      name: 'CT Room Construction',
      title: 'CT Room Construction & Lead Lining in Saudi Arabia | EGC',
      description: 'CT room construction in Saudi Arabia: lead-lined walls, floor and ceiling, lead-glass viewing window, shielded door and warning signage, built to the physicist’s report.',
      short: 'Lead lining, lead-glass window, shielded door and warning light, to the physicist’s report.',
      h1: 'CT room construction and lead lining contractor in Saudi Arabia',
      lead: 'We build CT scan rooms and their control rooms to the radiation protection physicist’s shielding report and the manufacturer’s site-planning guide, then support the radiation survey before the room goes into use.',
      imageAlt: 'Lead-lined imaging room with shielded door and warning sign',
      answerTitle: 'What goes into a CT room',
      answer: [
        'A CT room has to contain ionising radiation. The scanner produces X-rays in a rotating gantry, and the walls, floor, ceiling, door and viewing window around it are lined with lead, or an equivalent material, to the thickness a radiation protection physicist calculates in the shielding report. The control room sits behind a lead-lined wall with a lead-glass window, so staff can see the patient without being exposed. A warning light outside the door shows when the scanner is in use, and the door is interlocked where the design calls for it. EGC builds CT rooms from that report and the manufacturer’s site-planning guide: we detail the lead lining at every junction, box and penetration so there is no gap in the shield, install it with our own crews and support the radiation survey before handover.',
        `The same package includes the [lead-lined door](${DO}), the [services](${ME}) that enter the room and the [clinical finishes](${SU}), so the shielding is not compromised by the trades that follow.`,
      ],
      table: {
        title: 'Parts of a CT room and how each is protected',
        head: ['Part', 'Purpose', 'Protection detail'],
        rows: [
          ['Walls, floor and ceiling', 'Contain scattered radiation', 'Lead lining to the physicist’s specification'],
          ['Lead-glass viewing window', 'Lets staff see the patient from the control room', 'Lead equivalence matched to the wall'],
          ['Lead-lined door', 'Controlled access to the scan room', 'Leaf overlaps the wall lining at the frame'],
          ['Warning light and interlock', 'Shows when the scanner is in use', 'Wired to the equipment where specified'],
          ['Cable trays, pipes and ducts', 'Bring services into the room', 'Lead-backed sleeves and boxes at each crossing'],
        ],
      },
      usesTitle: 'Spaces in a CT suite',
      uses: ['Scan room', 'Control room', 'Equipment room', 'Patient preparation and changing', 'Contrast and injection preparation'],
      deliverTitle: 'What we build',
      deliver: [
        'Lead-lined walls, floor and ceiling',
        'Lead-glass viewing window',
        'Lead-lined door, manual or motorised',
        'Warning lights and door interlocks',
        'Lead-backed boxes and sleeves for services',
        'Retrofit shielding for existing CT rooms',
      ],
      process: [
        { t: 'Read the shielding report', d: 'We read the physicist’s report and the manufacturer’s guide side by side and resolve any conflict first.' },
        { t: 'Detail the lining', d: 'Drawings show each layer, seam and penetration so nothing is improvised on site.' },
        { t: 'Build and inspect', d: 'Our crews install the lining and check continuity before finishes close it in.' },
        { t: 'Survey and hand over', d: 'We support the radiation survey, then release the room for use.' },
      ],
      ctaTitle: 'Planning a CT room?',
      ctaText: 'Send us the scanner model and the physicist’s report and we will tell you how we would build it.',
    },
    ar: {
      name: 'إنشاء غرف الأشعة المقطعية',
      title: 'إنشاء وتبطين غرف الأشعة المقطعية بالرصاص في السعودية | EGC',
      description: 'إنشاء غرف الأشعة المقطعية في السعودية: جدران وأرضية وسقف مبطنة بالرصاص، ونافذة مراقبة من زجاج الرصاص، وباب مدرّع ولوحات تحذير، وفق تقرير الفيزيائي.',
      short: 'تبطين بالرصاص ونافذة زجاج رصاص وباب مدرّع وضوء تحذير وفق تقرير الفيزيائي.',
      h1: 'مقاول إنشاء وتبطين غرف الأشعة المقطعية بالرصاص في السعودية',
      lead: 'نبني غرف فحص الأشعة المقطعية وغرف التحكم وفق تقرير التدريع الصادر عن الفيزيائي المختص بالوقاية الإشعاعية ودليل تخطيط الموقع الصادر عن الشركة المصنِّعة، وندعم المسح الإشعاعي قبل تشغيل الغرفة.',
      imageAlt: 'غرفة تصوير مبطنة بالرصاص مع باب مدرّع ولوحة تحذير',
      answerTitle: 'ما الذي تتكون منه غرفة الأشعة المقطعية',
      answer: [
        'يجب أن تحتوي غرفة الأشعة المقطعية الإشعاع المؤيِّن. فالجهاز يولّد الأشعة السينية في حلقة دوّارة، وتُبطَّن الجدران والأرضية والسقف والباب ونافذة المراقبة حوله بالرصاص أو مادة مكافئة بالسماكة التي يحسبها الفيزيائي المختص بالوقاية الإشعاعية في تقرير التدريع. وتقع غرفة التحكم خلف جدار مبطن بالرصاص بنافذة من زجاج الرصاص، فيرى الطاقم المريض دون تعرّض. ويبيّن ضوء تحذير خارج الباب متى يعمل الجهاز، ويُربط الباب بقفل تبادلي حيث يتطلب التصميم ذلك. وتبني EGC غرف الأشعة المقطعية وفق ذلك التقرير ودليل تخطيط الموقع الصادر عن الشركة المصنِّعة: نفصّل التبطين بالرصاص عند كل وصلة وصندوق واختراق حتى لا تبقى فجوة في الدرع، وتركّبه كوادرنا بنفسها، وندعم المسح الإشعاعي قبل التسليم.',
        `وتشمل الحزمة نفسها [الباب المبطن بالرصاص](${DO}) و[الخدمات](${ME}) الداخلة إلى الغرفة و[التشطيبات السريرية](${SU})، فلا يتأثر الدرع بالأعمال اللاحقة.`,
      ],
      table: {
        title: 'أجزاء غرفة الأشعة المقطعية وكيف يُحمى كل جزء',
        head: ['الجزء', 'الغرض', 'تفصيل الحماية'],
        rows: [
          ['الجدران والأرضية والسقف', 'احتواء الإشعاع المتناثر', 'تبطين بالرصاص وفق مواصفات الفيزيائي'],
          ['نافذة المراقبة من زجاج الرصاص', 'تتيح للطاقم رؤية المريض من غرفة التحكم', 'رصاص مكافئ يطابق الجدار'],
          ['الباب المبطن بالرصاص', 'وصول مضبوط إلى غرفة الفحص', 'تتداخل الضلفة مع تبطين الجدار عند الإطار'],
          ['ضوء التحذير والقفل التبادلي', 'يبيّن متى يعمل الجهاز', 'يُربط بالجهاز حيث تتطلب المواصفات'],
          ['مسارات الكابلات والأنابيب والمجاري', 'تُدخل الخدمات إلى الغرفة', 'أغلفة وصناديق مبطنة بالرصاص عند كل اختراق'],
        ],
      },
      usesTitle: 'المساحات في جناح الأشعة المقطعية',
      uses: ['غرفة الفحص', 'غرفة التحكم', 'غرفة المعدات', 'تحضير المرضى وتغيير الملابس', 'تحضير مواد التباين والحقن'],
      deliverTitle: 'ما نبنيه',
      deliver: [
        'جدران وأرضية وسقف مبطنة بالرصاص',
        'نافذة مراقبة من زجاج الرصاص',
        'باب مبطن بالرصاص، يدوي أو آلي',
        'أضواء تحذير وأقفال تبادلية للأبواب',
        'صناديق وأغلفة مبطنة بالرصاص للخدمات',
        'تدريع تحديثي لغرف الأشعة المقطعية القائمة',
      ],
      process: [
        { t: 'قراءة تقرير التدريع', d: 'نقرأ تقرير الفيزيائي ودليل الشركة المصنِّعة معًا ونحسم أي تعارض أولًا.' },
        { t: 'تفصيل التبطين', d: 'تبيّن المخططات كل طبقة ووصلة واختراق فلا يُرتجل شيء في الموقع.' },
        { t: 'البناء والفحص', d: 'تركّب كوادرنا التبطين وتتحقق من اتصاله قبل أن تغطيه التشطيبات.' },
        { t: 'المسح والتسليم', d: 'ندعم المسح الإشعاعي ثم نسلّم الغرفة للتشغيل.' },
      ],
      ctaTitle: 'تخطط لغرفة أشعة مقطعية؟',
      ctaText: 'أرسل لنا طراز الجهاز وتقرير الفيزيائي، وسنوضح كيف سنبنيها.',
    },
  },

  {
    key: 'petCtRoom',
    segment: 'healthcare-contractor/pet-ct-room-construction',
    parent: 'hub',
    group: 'specialist',
    icon: 'radiation',
    image: 'healthcare-xray',
    imagePosition: 'center 55%',
    related: ['shielding', 'doors', 'ctRoom', 'mep', 'hospitalFitOut'],
    en: {
      name: 'PET-CT Room Construction',
      title: 'PET-CT Room Design & Shielding in Saudi Arabia | EGC',
      description: 'PET-CT suite construction in Saudi Arabia: shielding for 511 keV photons, hot lab, injection and uptake rooms, scanner and control rooms, built to the physicist’s report.',
      short: '511 keV shielding for the scanner room, uptake rooms, hot lab and control room.',
      h1: 'PET-CT room construction and shielding contractor in Saudi Arabia',
      lead: 'We build PET-CT suites to the radiation protection physicist’s report: the scanner room, the injection and uptake rooms, the hot lab and the control room, shielded for the higher-energy photons of PET tracers.',
      imageAlt: 'Shielded imaging room with lead-lined door',
      answerTitle: 'What makes a PET-CT room different',
      answer: [
        'PET-CT rooms are shielded for more than a CT scanner. The tracer used in PET emits 511 keV photons, which are more penetrating than diagnostic X-rays, so the lead lining is thicker and the rooms around the scanner, where patients receive the tracer and wait for it to take effect, are shielded as well. A PET-CT suite typically includes a hot lab for preparing radiopharmaceuticals, injection and uptake rooms, the scanner room, a control room and a dedicated patient toilet, laid out so that activity is contained and staff exposure is kept as low as reasonably achievable. The radiation protection physicist sets the shielding for each of these spaces. EGC builds from that report and the manufacturer’s site-planning guide, lining walls, doors, windows and penetrations, coordinating the services and finishes and supporting the radiation survey before the suite goes into use.',
        `Doors, drainage and services in a PET-CT suite all cross the shield, so [shielding](${SH}), [lead-lined doors](${DO}) and [MEP](${ME}) are planned together.`,
      ],
      table: {
        title: 'Spaces in a PET-CT suite and why they are shielded',
        head: ['Space', 'Why it needs shielding'],
        rows: [
          ['Hot lab', 'Radiopharmaceuticals are prepared and handled here before injection'],
          ['Injection and uptake rooms', 'Patients are radioactive while the tracer distributes through the body'],
          ['Scanner room', 'Contains the 511 keV photons from the patient and the CT X-rays'],
          ['Control room', 'Staff work behind lined walls and a lead-glass window'],
          ['Patient toilet', 'Excreted tracer needs controlled handling and disposal'],
        ],
      },
      usesTitle: 'Spaces we shield',
      uses: ['Hot lab', 'Injection and uptake rooms', 'PET-CT scanner room', 'Control room', 'Patient toilet and waste areas'],
      deliverTitle: 'What we build',
      deliver: [
        'Lead lining for the scanner room, uptake rooms and hot lab',
        'Shielded doors and lead-glass windows',
        'Lead-backed sleeves and boxes for services and drainage penetrations',
        'Warning lights and signage',
        'Finishes that clean easily and meet infection-control needs',
        'Coordination with the physicist and the manufacturer’s installation team',
      ],
      process: [
        { t: 'Read the report', d: 'We take the shielding for each space from the physicist’s report and the manufacturer’s guide.' },
        { t: 'Detail every crossing', d: 'Doors, drains, pipes and cables are located and detailed first.' },
        { t: 'Build and inspect', d: 'Our crews install and check the lining, then the finishes.' },
        { t: 'Survey and hand over', d: 'We support the radiation survey before the suite is used.' },
      ],
      ctaTitle: 'Planning a PET-CT suite?',
      ctaText: 'Share the equipment model and the physicist’s report and we will respond with how we would deliver it.',
    },
    ar: {
      name: 'إنشاء غرف PET-CT',
      title: 'تصميم وتدريع غرف PET-CT في السعودية | EGC',
      description: 'إنشاء أجنحة PET-CT في السعودية: تدريع لفوتونات 511 كيلو إلكترون فولت، ومختبر ساخن وغرف حقن وامتصاص وغرفة الجهاز والتحكم وفق تقرير الفيزيائي.',
      short: 'تدريع لفوتونات 511 كيلو إلكترون فولت لغرفة الجهاز وغرف الامتصاص والمختبر الساخن وغرفة التحكم.',
      h1: 'مقاول إنشاء وتدريع غرف PET-CT في السعودية',
      lead: 'نبني أجنحة PET-CT وفق تقرير الفيزيائي المختص بالوقاية الإشعاعية: غرفة الجهاز وغرف الحقن والامتصاص والمختبر الساخن وغرفة التحكم، مدرّعة للفوتونات الأعلى طاقة في مواد PET.',
      imageAlt: 'غرفة تصوير مدرّعة بباب مبطن بالرصاص',
      answerTitle: 'ما الذي يميّز غرفة PET-CT',
      answer: [
        'تُدرَّع غرف PET-CT لأكثر مما يتطلبه جهاز الأشعة المقطعية. فالمادة المستخدمة في PET تُصدر فوتونات بطاقة 511 كيلو إلكترون فولت، وهي أنفذ من الأشعة السينية التشخيصية، ولذلك يكون التبطين بالرصاص أسمك، وتُدرَّع كذلك الغرف المحيطة بالجهاز حيث يتلقى المرضى المادة وينتظرون انتشارها. ويضم جناح PET-CT عادةً مختبرًا ساخنًا لتحضير المستحضرات الإشعاعية، وغرف حقن وامتصاص، وغرفة الجهاز، وغرفة تحكم، ودورة مياه مخصصة للمرضى، مرتبة بحيث يُحتوى النشاط الإشعاعي ويبقى تعرّض الطاقم عند أدنى مستوى يمكن تحقيقه. ويحدد الفيزيائي المختص بالوقاية الإشعاعية التدريع لكل من هذه المساحات. وتبني EGC وفق ذلك التقرير ودليل تخطيط الموقع الصادر عن الشركة المصنِّعة، فتبطّن الجدران والأبواب والنوافذ والاختراقات، وتنسّق الخدمات والتشطيبات، وتدعم المسح الإشعاعي قبل تشغيل الجناح.',
        `وتخترق الأبواب والصرف والخدمات الدرع في جناح PET-CT، ولذلك يُخطَّط [التدريع](${SH}) و[الأبواب المبطنة بالرصاص](${DO}) و[الأعمال الكهروميكانيكية](${ME}) معًا.`,
      ],
      table: {
        title: 'المساحات في جناح PET-CT وسبب تدريعها',
        head: ['المساحة', 'سبب الحاجة إلى التدريع'],
        rows: [
          ['المختبر الساخن', 'تُحضَّر فيه المستحضرات الإشعاعية وتُتداول قبل الحقن'],
          ['غرف الحقن والامتصاص', 'يكون المرضى مصدرًا للإشعاع أثناء انتشار المادة في الجسم'],
          ['غرفة الجهاز', 'تحتوي فوتونات 511 كيلو إلكترون فولت الصادرة من المريض والأشعة السينية للجهاز'],
          ['غرفة التحكم', 'يعمل الطاقم خلف جدران مبطنة ونافذة من زجاج الرصاص'],
          ['دورة مياه المرضى', 'تحتاج المادة المفرَزة إلى تعامل وتصريف مضبوطين'],
        ],
      },
      usesTitle: 'المساحات التي ندرّعها',
      uses: ['المختبر الساخن', 'غرف الحقن والامتصاص', 'غرفة جهاز PET-CT', 'غرفة التحكم', 'دورة مياه المرضى ومناطق النفايات'],
      deliverTitle: 'ما نبنيه',
      deliver: [
        'تبطين بالرصاص لغرفة الجهاز وغرف الامتصاص والمختبر الساخن',
        'أبواب مدرّعة ونوافذ من زجاج الرصاص',
        'أغلفة وصناديق مبطنة بالرصاص للخدمات واختراقات الصرف',
        'أضواء ولوحات تحذير',
        'تشطيبات سهلة التنظيف تلبي متطلبات مكافحة العدوى',
        'التنسيق مع الفيزيائي وفريق تركيب الشركة المصنِّعة',
      ],
      process: [
        { t: 'قراءة التقرير', d: 'نأخذ التدريع لكل مساحة من تقرير الفيزيائي ودليل الشركة المصنِّعة.' },
        { t: 'تفصيل كل اختراق', d: 'تُحدَّد الأبواب والمصارف والأنابيب والكابلات وتُفصَّل أولًا.' },
        { t: 'البناء والفحص', d: 'تركّب كوادرنا التبطين وتفحصه، ثم التشطيبات.' },
        { t: 'المسح والتسليم', d: 'ندعم المسح الإشعاعي قبل استخدام الجناح.' },
      ],
      ctaTitle: 'تخطط لجناح PET-CT؟',
      ctaText: 'شاركنا طراز الجهاز وتقرير الفيزيائي وسنرد بكيفية تنفيذنا له.',
    },
  },

  {
    key: 'xrayRoom',
    segment: 'healthcare-contractor/x-ray-room-construction',
    parent: 'hub',
    group: 'specialist',
    icon: 'radiation',
    image: 'healthcare-xray',
    imagePosition: '85% 50%',
    related: ['shielding', 'doors', 'ctRoom', 'surfaces', 'mep'],
    en: {
      name: 'X-Ray Room Construction',
      title: 'X-Ray Room Construction & Lead Lining in Saudi Arabia | EGC',
      description: 'X-ray and fluoroscopy room construction in Saudi Arabia: lead-lined walls, shielded door, lead-glass window and warning signage, built to the physicist’s report.',
      short: 'Lead lining, shielded door, lead-glass window and warning signs for X-ray and fluoroscopy rooms.',
      h1: 'X-ray and fluoroscopy room construction contractor in Saudi Arabia',
      lead: 'We build general radiography and fluoroscopy rooms to the radiation protection physicist’s report and the equipment manufacturer’s guide, from the lead lining and shielded door to the warning signage and the supports the equipment needs.',
      imageAlt: 'X-ray room with a lead-lined door and warning light',
      answerTitle: 'What goes into an X-ray room',
      answer: [
        'A general X-ray (radiography) room is the simplest shielded imaging room, but the details still matter. The X-ray tube produces a beam directed at the patient and detector, so the walls, door and viewing window around it are lead-lined to the physicist’s specification, and the operator works from a protected control area or behind a lead screen. Fluoroscopy rooms, used for live imaging during procedures, need the same protection and often more of it. The door is lead-lined, and an illuminated warning sign outside shows when X-rays are on. EGC builds X-ray and fluoroscopy rooms from the shielding report and the equipment manufacturer’s guide, with the lead lining, lead-glass window, door, warning signage and the provisions for the equipment’s ceiling and wall supports, and supports the radiation survey before the room is used.',
        `Because the room is used all day, the [door](${DO}) and the [wipe-clean surfaces](${SU}) matter as much as the [lead lining](${SH}).`,
      ],
      table: null,
      usesTitle: 'Rooms we build',
      uses: ['General radiography rooms', 'Fluoroscopy rooms', 'Procedure and interventional rooms', 'Other diagnostic X-ray rooms'],
      deliverTitle: 'What we build',
      deliver: [
        'Lead-lined walls, ceiling and floor where specified',
        'Lead-lined door with warning light and signage',
        'Lead-glass viewing window and shielded control area',
        'Lead-backed boxes and sleeves for services',
        'Provisions for ceiling and wall equipment supports',
        'Clean, durable finishes for daily clinical use',
      ],
      process: [
        { t: 'Read the report', d: 'We work from the physicist’s shielding report and the equipment manufacturer’s guide.' },
        { t: 'Detail the lining', d: 'Every junction, box and penetration is drawn before work starts.' },
        { t: 'Build and inspect', d: 'Our crews install and check the lining, door and window.' },
        { t: 'Survey and hand over', d: 'We support the radiation survey, then release the room.' },
      ],
      ctaTitle: 'Planning an X-ray room?',
      ctaText: 'Send us the equipment model and the shielding report and we will tell you how we would build it.',
    },
    ar: {
      name: 'إنشاء غرف الأشعة السينية',
      title: 'إنشاء وتبطين غرف الأشعة السينية بالرصاص في السعودية | EGC',
      description: 'إنشاء غرف الأشعة السينية والتنظير الفلوري في السعودية: جدران مبطنة بالرصاص وباب مدرّع ونافذة زجاج رصاص ولوحات تحذير وفق تقرير الفيزيائي.',
      short: 'تبطين بالرصاص وباب مدرّع ونافذة زجاج رصاص ولوحات تحذير لغرف الأشعة السينية والتنظير الفلوري.',
      h1: 'مقاول إنشاء غرف الأشعة السينية والتنظير الفلوري في السعودية',
      lead: 'نبني غرف التصوير الشعاعي العام والتنظير الفلوري وفق تقرير الفيزيائي المختص بالوقاية الإشعاعية ودليل الشركة المصنِّعة للجهاز، من التبطين بالرصاص والباب المدرّع إلى لوحات التحذير وما يحتاجه الجهاز من دعامات.',
      imageAlt: 'غرفة أشعة سينية بباب مبطن بالرصاص وضوء تحذير',
      answerTitle: 'ما الذي تتكون منه غرفة الأشعة السينية',
      answer: [
        'غرفة الأشعة السينية العامة (التصوير الشعاعي) هي أبسط غرف التصوير المدرّعة، لكن التفاصيل فيها مهمة. فأنبوب الأشعة يُصدر حزمة موجّهة نحو المريض وكاشف الصورة، ولذلك تُبطَّن الجدران والباب ونافذة المراقبة حوله بالرصاص وفق مواصفات الفيزيائي، ويعمل المشغّل من منطقة تحكم محمية أو خلف حاجز رصاصي. وتحتاج غرف التنظير الفلوري، المستخدمة للتصوير الحي أثناء الإجراءات، إلى الحماية نفسها وغالبًا إلى أكثر منها. ويكون الباب مبطنًا بالرصاص، وتبيّن لوحة تحذير مضاءة خارج الغرفة متى تعمل الأشعة. وتبني EGC غرف الأشعة السينية والتنظير الفلوري وفق تقرير التدريع ودليل الشركة المصنِّعة، بالتبطين بالرصاص ونافذة زجاج الرصاص والباب ولوحات التحذير وتجهيزات دعامات السقف والجدار للجهاز، وتدعم المسح الإشعاعي قبل استخدام الغرفة.',
        `ولأن الغرفة تُستخدم طوال اليوم، فإن [الباب](${DO}) و[الأسطح سهلة المسح](${SU}) لا تقل أهمية عن [التبطين بالرصاص](${SH}).`,
      ],
      table: null,
      usesTitle: 'الغرف التي نبنيها',
      uses: ['غرف التصوير الشعاعي العام', 'غرف التنظير الفلوري', 'غرف الإجراءات والتدخل الإشعاعي', 'غرف الأشعة السينية التشخيصية الأخرى'],
      deliverTitle: 'ما نبنيه',
      deliver: [
        'جدران وسقف وأرضية مبطنة بالرصاص حيث يُشترط',
        'باب مبطن بالرصاص مع ضوء ولوحة تحذير',
        'نافذة مراقبة من زجاج الرصاص ومنطقة تحكم محمية',
        'صناديق وأغلفة مبطنة بالرصاص للخدمات',
        'تجهيزات لدعامات المعدات في السقف والجدار',
        'تشطيبات نظيفة ومتينة للاستخدام السريري اليومي',
      ],
      process: [
        { t: 'قراءة التقرير', d: 'نعمل وفق تقرير التدريع الصادر عن الفيزيائي ودليل الشركة المصنِّعة للجهاز.' },
        { t: 'تفصيل التبطين', d: 'تُرسم كل وصلة وصندوق واختراق قبل بدء العمل.' },
        { t: 'البناء والفحص', d: 'تركّب كوادرنا التبطين والباب والنافذة وتفحصها.' },
        { t: 'المسح والتسليم', d: 'ندعم المسح الإشعاعي ثم نسلّم الغرفة.' },
      ],
      ctaTitle: 'تخطط لغرفة أشعة سينية؟',
      ctaText: 'أرسل لنا طراز الجهاز وتقرير التدريع، وسنوضح كيف سنبنيها.',
    },
  },
];
