/* Software engineering pages (parent: software): one per product people search for. */
export const SOFTWARE_PAGES = [
  {
    key: 'hisRis',
    segment: 'software-engineering/hospital-information-systems',
    parent: 'software',
    group: 'software',
    icon: 'server',
    related: ['erp', 'websites', 'mriRoom'],
    en: {
      name: 'Hospital & Radiology Information Systems',
      title: 'HIS & RIS Software for Hospitals in Saudi Arabia | EGC',
      description: 'Hospital and radiology information systems (HIS, RIS) for Saudi Arabia: scheduling, radiology workflow, reporting and imaging-equipment integration.',
      short: 'Scheduling, radiology workflow, reporting and imaging-equipment integration.',
      h1: 'Hospital and radiology information systems (HIS and RIS) in Saudi Arabia',
      lead: 'Software for the departments we build the rooms for: patient scheduling and department workflow, radiology orders and reporting, and integration with imaging equipment, built around Saudi data-protection requirements.',
      answerTitle: 'What HIS and RIS software does',
      answer: [
        'A hospital information system (HIS) manages the administrative and clinical work of a hospital: registering patients, scheduling appointments, recording visits, orders and results, and billing. A radiology information system (RIS) does the same for the imaging department: it takes the order for a scan, schedules the room and the equipment, tracks the patient through the examination, records the radiologist’s report and sends the result back to the referring doctor. A RIS typically exchanges images with a PACS and data with the HIS using standards such as HL7 and DICOM. EGC’s software engineering team builds HIS and RIS modules that fit these workflows, aligned with Saudi requirements such as the Personal Data Protection Law (PDPL), and connects them to the imaging equipment that our other teams prepare the rooms for.',
        'For the same department we also build the rooms: see [MRI room construction](healthcare-contractor/mri-room-construction) and [CT room construction](healthcare-contractor/ct-room-construction). For finance and administration see our [ERP software](software-engineering/erp-software).',
      ],
      table: {
        title: 'HIS, RIS and PIMS compared',
        head: ['System', 'Scope', 'Typical users'],
        rows: [
          ['HIS (hospital information system)', 'Whole-hospital administration and clinical workflow', 'Administration, clinicians, billing'],
          ['RIS (radiology information system)', 'Imaging department workflow, scheduling and reporting', 'Radiologists, technologists, reception'],
          ['PIMS (patient information management)', 'Patient records, history, access control and audit trails', 'Clinicians and records staff'],
        ],
      },
      usesTitle: 'Where it is used',
      uses: ['Hospitals and medical cities', 'Diagnostic and imaging centres', 'Radiology departments', 'Clinics and polyclinics'],
      deliverTitle: 'What we build',
      deliver: [
        'Patient scheduling and department workflow',
        'Radiology orders, worklists and reporting',
        'Integration with imaging equipment and PACS (HL7, DICOM)',
        'Role-based access and audit trails',
        'PDPL-aligned data handling',
        'Arabic and English interfaces',
      ],
      process: [
        { t: 'Discover the workflow', d: 'We map your departments, users and obligations before writing code.' },
        { t: 'Design and build', d: 'Short iterations with working software at each stage.' },
        { t: 'Integrate and test', d: 'Connection to equipment and existing systems, tested with your staff.' },
        { t: 'Launch and support', d: 'Training, go-live support and a named engineer.' },
      ],
      ctaTitle: 'Need a hospital or radiology system?',
      ctaText: 'Tell us about your department and workflow and we will respond with a proposal.',
    },
    ar: {
      name: 'أنظمة معلومات المستشفيات والأشعة',
      title: 'برمجيات HIS وRIS للمستشفيات في السعودية | EGC',
      description: 'أنظمة معلومات المستشفيات والأشعة (HIS وRIS) للسعودية: جدولة وسير عمل الأشعة والتقارير والتكامل مع معدات التصوير.',
      short: 'جدولة وسير عمل الأشعة والتقارير والتكامل مع معدات التصوير.',
      h1: 'أنظمة معلومات المستشفيات والأشعة (HIS وRIS) في السعودية',
      lead: 'برمجيات للأقسام التي نبني لها الغرف: جدولة المرضى وسير عمل الأقسام، وطلبات الأشعة وتقاريرها، والتكامل مع معدات التصوير، مبنية حول متطلبات حماية البيانات السعودية.',
      answerTitle: 'ماذا تفعل برمجيات HIS وRIS',
      answer: [
        'يدير نظام معلومات المستشفى (HIS) العمل الإداري والسريري للمستشفى: تسجيل المرضى وجدولة المواعيد وتدوين الزيارات والطلبات والنتائج والفوترة. ويؤدي نظام معلومات الأشعة (RIS) الدور نفسه لقسم التصوير: يستقبل طلب الفحص ويجدول الغرفة والجهاز ويتتبع المريض خلال الفحص ويدوّن تقرير أخصائي الأشعة ويعيد النتيجة إلى الطبيب المحيل. ويتبادل RIS عادةً الصور مع نظام PACS والبيانات مع HIS عبر معايير مثل HL7 وDICOM. ويبني فريق هندسة البرمجيات في EGC وحدات HIS وRIS تلائم هذه المسارات، وفق متطلبات سعودية مثل نظام حماية البيانات الشخصية (PDPL)، ويربطها بمعدات التصوير التي تجهّز فرقنا الأخرى غرفها.',
        'ونبني للقسم نفسه الغرف أيضًا: راجع [إنشاء غرف الرنين المغناطيسي](healthcare-contractor/mri-room-construction) و[إنشاء غرف الأشعة المقطعية](healthcare-contractor/ct-room-construction). وللمالية والإدارة راجع [برمجيات تخطيط الموارد](software-engineering/erp-software).',
      ],
      table: {
        title: 'مقارنة بين HIS وRIS وPIMS',
        head: ['النظام', 'النطاق', 'المستخدمون المعتادون'],
        rows: [
          ['HIS (نظام معلومات المستشفى)', 'إدارة المستشفى كاملة وسير العمل السريري', 'الإدارة والأطباء والفوترة'],
          ['RIS (نظام معلومات الأشعة)', 'سير عمل قسم التصوير والجدولة والتقارير', 'أخصائيو الأشعة والفنيون والاستقبال'],
          ['PIMS (إدارة معلومات المرضى)', 'سجلات المرضى وتاريخهم وضبط الوصول وسجلات التدقيق', 'الأطباء وموظفو السجلات'],
        ],
      },
      usesTitle: 'أين يُستخدم',
      uses: ['المستشفيات والمدن الطبية', 'مراكز التشخيص والتصوير', 'أقسام الأشعة', 'العيادات والمجمعات الطبية'],
      deliverTitle: 'ما نبنيه',
      deliver: [
        'جدولة المرضى وسير عمل الأقسام',
        'طلبات الأشعة وقوائم العمل والتقارير',
        'التكامل مع معدات التصوير ونظام PACS (HL7 وDICOM)',
        'صلاحيات وصول قائمة على الأدوار وسجلات تدقيق',
        'معالجة بيانات متوافقة مع نظام حماية البيانات الشخصية',
        'واجهات بالعربية والإنجليزية',
      ],
      process: [
        { t: 'استكشاف مسار العمل', d: 'نرسم أقسامك ومستخدميك والتزاماتك قبل كتابة أي كود.' },
        { t: 'التصميم والبناء', d: 'دورات قصيرة وبرمجيات تعمل في كل مرحلة.' },
        { t: 'التكامل والاختبار', d: 'الربط بالمعدات والأنظمة القائمة واختباره مع موظفيك.' },
        { t: 'الإطلاق والدعم', d: 'تدريب ودعم عند التشغيل ومهندس مخصص.' },
      ],
      ctaTitle: 'تحتاج نظامًا للمستشفى أو للأشعة؟',
      ctaText: 'أخبرنا عن قسمك ومسار العمل وسنرد بعرض.',
    },
  },

  {
    key: 'erp',
    segment: 'software-engineering/erp-software',
    parent: 'software',
    group: 'software',
    icon: 'database',
    related: ['hisRis', 'websites'],
    en: {
      name: 'ERP & Management Software',
      title: 'ERP Software for Saudi Arabia: ZATCA, GOSI & WPS | EGC',
      description: 'ERP and management software for Saudi companies: ZATCA e-invoicing, GOSI and WPS integration, finance, procurement, HR and project modules.',
      short: 'Finance, procurement, HR and project modules with ZATCA, GOSI and WPS built in.',
      h1: 'ERP and management software for Saudi Arabia',
      lead: 'Enterprise resource planning built around Saudi compliance from the start, covering finance, procurement, HR and operations, and including project tools informed by how EGC runs its own contracting business.',
      answerTitle: 'What an ERP needs in Saudi Arabia',
      answer: [
        'An ERP system brings a company’s finance, procurement, inventory, HR and project data into one place, so decisions are made from the same numbers. In Saudi Arabia an ERP also has to meet local rules: invoices must be issued as structured e-invoices that comply with ZATCA’s e-invoicing (Fatoora) requirements, payroll must follow the Wage Protection System (WPS), social insurance contributions go to GOSI, and personal data must be handled in line with the Personal Data Protection Law (PDPL). EGC’s software engineering team builds ERP and managerial software with those requirements designed in rather than added later. Modules cover finance and e-invoicing, procurement and vendor management, HR and payroll, and construction and project management, with Arabic and English interfaces.',
        'The same team builds [hospital and radiology information systems](software-engineering/hospital-information-systems) and [bilingual websites](software-engineering/website-development).',
      ],
      table: {
        title: 'Saudi compliance touchpoints',
        head: ['Requirement', 'What the software handles'],
        rows: [
          ['ZATCA e-invoicing (Fatoora)', 'Issues structured e-invoices with a QR code and submits them as the taxpayer’s phase requires'],
          ['GOSI', 'Employee and contribution data for social insurance'],
          ['Wage Protection System (WPS)', 'Payroll files for the wage-protection payment process'],
          ['PDPL', 'Controls over personal data: who can see it, how it is stored and how long it is kept'],
        ],
      },
      usesTitle: 'Who it is for',
      uses: ['Contractors and construction companies', 'Hospitals and healthcare groups', 'Manufacturers and factories', 'Trading and service companies'],
      deliverTitle: 'What we build',
      deliver: [
        'Finance, accounting and ZATCA e-invoicing',
        'Procurement, inventory and vendor management',
        'HR, payroll, GOSI and WPS',
        'Construction and project management: scheduling, documentation, RFIs',
        'Reporting and dashboards',
        'Arabic and English interfaces',
      ],
      process: [
        { t: 'Discover', d: 'We map workflows, users and regulatory obligations before writing code.' },
        { t: 'Build', d: 'Short iterations with working software at every stage.' },
        { t: 'Deploy', d: 'Hosting, security and data migration planned with your IT team.' },
        { t: 'Support', d: 'Training, monitoring and a named engineer for your system.' },
      ],
      ctaTitle: 'Planning an ERP rollout?',
      ctaText: 'Tell us about your company and workflows and we will respond with a proposal.',
    },
    ar: {
      name: 'تخطيط الموارد والبرمجيات الإدارية',
      title: 'برمجيات ERP للسعودية: الفوترة الإلكترونية والتأمينات ونظام الأجور | EGC',
      description: 'برمجيات تخطيط الموارد للشركات السعودية: الفوترة الإلكترونية والتأمينات ونظام حماية الأجور ووحدات المالية والمشتريات والموارد البشرية والمشاريع.',
      short: 'وحدات المالية والمشتريات والموارد البشرية والمشاريع مع الفوترة الإلكترونية والتأمينات ونظام الأجور.',
      h1: 'برمجيات تخطيط الموارد (ERP) والإدارة للسعودية',
      lead: 'تخطيط موارد مبني حول الامتثال السعودي منذ البداية، يغطي المالية والمشتريات والموارد البشرية والعمليات، ويشمل أدوات مشاريع مستندة إلى طريقة إدارة EGC لأعمالها المقاولاتية.',
      answerTitle: 'ما الذي يحتاجه نظام ERP في السعودية',
      answer: [
        'يجمع نظام تخطيط الموارد بيانات المالية والمشتريات والمخزون والموارد البشرية والمشاريع في مكان واحد، فتُتخذ القرارات من الأرقام نفسها. وفي السعودية يجب أن يلتزم النظام بالأنظمة المحلية: تصدر الفواتير فواتير إلكترونية منظمة وفق متطلبات الفوترة الإلكترونية (فاتورة) لهيئة الزكاة والضريبة والجمارك، وتتبع الرواتب نظام حماية الأجور، وتُرفع اشتراكات التأمينات الاجتماعية إلى المؤسسة العامة للتأمينات الاجتماعية، وتُعالَج البيانات الشخصية وفق نظام حماية البيانات الشخصية (PDPL). ويبني فريق هندسة البرمجيات في EGC نظم تخطيط الموارد والبرمجيات الإدارية بهذه المتطلبات ضمن التصميم لا إضافةً لاحقة. وتغطي الوحدات المالية والفوترة الإلكترونية، والمشتريات وإدارة الموردين، والموارد البشرية والرواتب، وإدارة الإنشاءات والمشاريع، بواجهات عربية وإنجليزية.',
        'ويبني الفريق نفسه [أنظمة معلومات المستشفيات والأشعة](software-engineering/hospital-information-systems) و[مواقع إلكترونية ثنائية اللغة](software-engineering/website-development).',
      ],
      table: {
        title: 'نقاط الامتثال السعودي',
        head: ['المتطلب', 'ما تعالجه البرمجية'],
        rows: [
          ['الفوترة الإلكترونية (فاتورة)', 'إصدار فواتير إلكترونية منظمة برمز QR وإرسالها وفق مرحلة المكلف'],
          ['التأمينات الاجتماعية', 'بيانات الموظفين والاشتراكات للتأمينات الاجتماعية'],
          ['نظام حماية الأجور', 'ملفات الرواتب لعملية صرف الأجور المحمية'],
          ['نظام حماية البيانات الشخصية', 'ضوابط على البيانات الشخصية: من يراها وكيف تُخزَّن ومدة حفظها'],
        ],
      },
      usesTitle: 'لمن هي',
      uses: ['شركات المقاولات والإنشاءات', 'المستشفيات والمجموعات الصحية', 'المصانع والشركات الصناعية', 'شركات التجارة والخدمات'],
      deliverTitle: 'ما نبنيه',
      deliver: [
        'المالية والمحاسبة والفوترة الإلكترونية',
        'المشتريات والمخزون وإدارة الموردين',
        'الموارد البشرية والرواتب والتأمينات ونظام حماية الأجور',
        'إدارة الإنشاءات والمشاريع: الجدولة والتوثيق وطلبات المعلومات',
        'التقارير ولوحات المتابعة',
        'واجهات بالعربية والإنجليزية',
      ],
      process: [
        { t: 'الاستكشاف', d: 'نرسم مسارات العمل والمستخدمين والالتزامات التنظيمية قبل كتابة أي كود.' },
        { t: 'البناء', d: 'دورات قصيرة وبرمجيات تعمل في كل مرحلة.' },
        { t: 'النشر', d: 'تُخطَّط الاستضافة والأمن ونقل البيانات مع فريق تقنية المعلومات لديك.' },
        { t: 'الدعم', d: 'تدريب ومراقبة ومهندس مخصص لنظامك.' },
      ],
      ctaTitle: 'تخطط لتطبيق نظام تخطيط موارد؟',
      ctaText: 'أخبرنا عن شركتك ومسارات عملها وسنرد بعرض.',
    },
  },

  {
    key: 'websites',
    segment: 'software-engineering/website-development',
    parent: 'software',
    group: 'software',
    icon: 'globe',
    related: ['erp', 'hisRis'],
    en: {
      name: 'Website Development',
      title: 'Bilingual Website Development in Jeddah, Saudi Arabia | EGC',
      description: 'Arabic and English websites for Saudi companies: fast, mobile-first and search-ready, designed and built by EGC’s software engineering team in Jeddah.',
      short: 'Fast, mobile-first Arabic and English websites with search-ready structure.',
      h1: 'Bilingual website design and development in Jeddah, Saudi Arabia',
      lead: 'Fast, mobile-first Arabic and English websites built by EGC’s software engineers: right-to-left layouts done properly, search-ready markup and content structure, and hosting that fits Saudi requirements.',
      answerTitle: 'What a Saudi company website needs',
      answer: [
        'A company website in Saudi Arabia usually has to work in two languages, on every phone, and be found in search. That means a layout that mirrors correctly for Arabic, fonts that render both scripts well, pages that load quickly on mobile networks and markup that tells search engines and AI assistants what the company is, what it does and where. EGC’s software engineering team designs and builds bilingual websites to that standard: content structure and page titles planned around the queries customers actually use, structured data for the business, a mobile-first interface and hosting set up with local requirements in mind. Websites can stand alone or connect to the ERP and information systems we also build, so enquiries, documents and data flow into the tools staff use every day.',
        'The same team builds [ERP and management software](software-engineering/erp-software) and [hospital information systems](software-engineering/hospital-information-systems).',
      ],
      table: null,
      usesTitle: 'Who it is for',
      uses: ['Corporate and company-profile websites', 'Hospital and clinic websites', 'Contractor and engineering company sites', 'Product catalogues and customer portals'],
      deliverTitle: 'What we build',
      deliver: [
        'Arabic and English design with proper right-to-left layouts',
        'Mobile-first, fast-loading pages',
        'Search-ready structure, structured data and sitemaps',
        'Content management or static builds, as appropriate',
        'Contact forms and integration with ERP or CRM',
        'Hosting, handover and maintenance',
      ],
      process: [
        { t: 'Plan the content', d: 'We plan pages and wording around the queries your customers use.' },
        { t: 'Design and build', d: 'A mobile-first design in both languages, built and reviewed with you.' },
        { t: 'Launch', d: 'Hosting, redirects, analytics and search setup.' },
        { t: 'Maintain', d: 'Updates, monitoring and support after launch.' },
      ],
      ctaTitle: 'Need a website?',
      ctaText: 'Tell us about your company and we will respond with a plan and a proposal.',
    },
    ar: {
      name: 'تطوير المواقع الإلكترونية',
      title: 'تطوير مواقع إلكترونية ثنائية اللغة في جدة، السعودية | EGC',
      description: 'مواقع إلكترونية بالعربية والإنجليزية للشركات السعودية: سريعة ومتوافقة مع الجوال وجاهزة لمحركات البحث، يصممها ويبنيها فريق هندسة البرمجيات في EGC بجدة.',
      short: 'مواقع سريعة ومتوافقة مع الجوال بالعربية والإنجليزية وبنية جاهزة لمحركات البحث.',
      h1: 'تصميم وتطوير المواقع الإلكترونية ثنائية اللغة في جدة، السعودية',
      lead: 'مواقع سريعة ومتوافقة مع الجوال بالعربية والإنجليزية يبنيها مهندسو البرمجيات في EGC: تخطيطات من اليمين إلى اليسار بإتقان، وهيكل محتوى وترميز جاهزان لمحركات البحث، واستضافة تلائم المتطلبات السعودية.',
      answerTitle: 'ما الذي يحتاجه موقع شركة سعودية',
      answer: [
        'يلزم عادةً أن يعمل موقع الشركة في السعودية بلغتين وعلى كل هاتف وأن يظهر في البحث. وهذا يعني تخطيطًا ينعكس بصورة صحيحة للعربية، وخطوطًا تعرض الكتابتين جيدًا، وصفحات تُحمَّل بسرعة على شبكات الجوال، وترميزًا يخبر محركات البحث والمساعدات الذكية ما هي الشركة وماذا تفعل وأين. ويصمم فريق هندسة البرمجيات في EGC مواقع ثنائية اللغة بهذا المعيار: هيكل محتوى وعناوين صفحات مخططة حول استفسارات العملاء الفعلية، وبيانات منظمة للنشاط، وواجهة تراعي الجوال أولًا، واستضافة مُعدّة مع مراعاة المتطلبات المحلية. ويمكن أن يعمل الموقع بمفرده أو يرتبط بنظام تخطيط الموارد وأنظمة المعلومات التي نبنيها أيضًا، فتتدفق الاستفسارات والمستندات والبيانات إلى الأدوات التي يستخدمها الموظفون يوميًا.',
        'ويبني الفريق نفسه [برمجيات تخطيط الموارد والإدارة](software-engineering/erp-software) و[أنظمة معلومات المستشفيات](software-engineering/hospital-information-systems).',
      ],
      table: null,
      usesTitle: 'لمن هي',
      uses: ['مواقع الشركات والتعريف بها', 'مواقع المستشفيات والعيادات', 'مواقع شركات المقاولات والهندسة', 'كتالوجات المنتجات وبوابات العملاء'],
      deliverTitle: 'ما نبنيه',
      deliver: [
        'تصميم بالعربية والإنجليزية بتخطيطات يمين-يسار صحيحة',
        'صفحات سريعة التحميل تراعي الجوال أولًا',
        'بنية جاهزة للبحث وبيانات منظمة وخرائط مواقع',
        'إدارة محتوى أو مواقع ثابتة بحسب الحاجة',
        'نماذج تواصل وتكامل مع ERP أو CRM',
        'الاستضافة والتسليم والصيانة',
      ],
      process: [
        { t: 'تخطيط المحتوى', d: 'نخطط الصفحات والصياغة حول الاستفسارات التي يستخدمها عملاؤك.' },
        { t: 'التصميم والبناء', d: 'تصميم يراعي الجوال أولًا باللغتين، يُبنى ويُراجَع معك.' },
        { t: 'الإطلاق', d: 'الاستضافة وإعادة التوجيه والتحليلات وإعداد البحث.' },
        { t: 'الصيانة', d: 'تحديثات ومراقبة ودعم بعد الإطلاق.' },
      ],
      ctaTitle: 'تحتاج موقعًا إلكترونيًا؟',
      ctaText: 'أخبرنا عن شركتك وسنرد بخطة وعرض.',
    },
  },
];
