/* Page-level prose, grouped by page key, each `{ en, ar }`. Structured
 * data used elsewhere on the same page (SERVICES, PROJECTS, CAREERS, etc.)
 * lives in its own module — this file only holds copy that belongs to one
 * page and isn't reused. Manufacturing/Software Engineering pages pull
 * their copy straight from content/manufacturing.js and content/software.js
 * instead (their hero fields double as PageHeader props). */
export const COPY = {
  home: {
    en: {
      heroLabel: 'Jeddah · Kingdom of Saudi Arabia',
      heroHeadline1: 'We prepare the rooms',
      heroHeadlineAccent: 'your equipment moves into.',
      heroSub: 'Specialty contractor for healthcare room preparation — structural radiation & magnetic shielding, medical doors, specialized MEP, and infection-controlled surfaces for MRI, CT and PET-CT rooms across the Kingdom of Saudi Arabia.',
      heroTrust: ['ISO 9001 Certified', '18+ Years in Saudi Arabia', '150+ Projects Delivered'],
      heroCtaPrimary: 'What We Build',
      heroCtaSecondary: 'Get In Touch',
      svcStripLabel: 'What We Build',
      spotlightOverline: 'Our Core Expertise',
      spotlightHeadline1: 'Rooms built for OEM',
      spotlightHeadline2: 'equipment, not general use.',
      spotlightBody1: "EGC's most specialist work happens before the equipment ever arrives — constructing the rooms Siemens Healthineers, Philips Healthcare, and GE Healthcare imaging systems move into. Structural radiation and magnetic shielding, medical doors, and specialized MEP, built to the tolerances each OEM's installation team requires.",
      spotlightBody2: 'Our teams work alongside radiation physicists, hospital project managers, and OEM installation crews to deliver rooms that pass compliance testing and equipment commissioning first time — on the programme dates that matter to clinical operations.',
      spotlightChecklist: ['MRI & CT suite magnetic and RF shielding', 'Lead-lined and radiation-shielded doors', 'Specialized MEP for imaging equipment', 'Infection-controlled surfaces and joinery'],
      spotlightCta: 'Healthcare Construction',
      spotlightBadgeLabel: 'Structural Radiation & Magnetic Shielding',
      servicesLabel: 'Full Scope of Work',
      servicesHeadline: 'Four disciplines. One contractor.',
      servicesSub: 'Healthcare room preparation is our speciality — structural shielding, medical doors, specialized MEP, and infection-controlled surfaces, all delivered under one quality programme.',
      manufacturingLabel: 'Manufacturing',
      manufacturingHeadline: 'Backed by our own factory floor.',
      manufacturingBody: "EGC's in-house Wood & Corian factory produces the solid-surface and joinery work behind our healthcare projects — and stands on its own, with flagship work including interiors at Jeddah's international airport and multiple military hospital facilities.",
      manufacturingCta: 'See Manufacturing',
      softwareLabel: 'Software Engineering',
      softwareHeadline: 'A new sector, built on what we already know.',
      softwareBody: 'Hospital & Radiology Information Systems, ERP and managerial software engineered for KSA regulatory compliance, and client-facing websites — from a team that already understands hospitals and job sites.',
      softwareCta: 'See Software Engineering',
      galleryLabel: 'Our Work',
      galleryHeadline: 'Built across the Kingdom.',
      galleryCtaLabel: 'See all work',
      galleryMainCaption: 'MRI suite installation — Jeddah hospital project',
      galleryMainService: 'Healthcare',
      galleryItem1Caption: 'Architectural door installation',
      galleryItem1Service: 'Joinery',
      galleryItem2Caption: 'Corian nurse station — hospital project',
      galleryItem2Service: 'Surfaces',
      aboutLabel: 'About EGC',
      aboutHeadline: 'Built in Jeddah. Working across the Kingdom.',
      aboutBody1: 'Engineering Grouping Co. (EGC) is a Jeddah-based specialty contractor preparing healthcare rooms for OEM medical imaging equipment. We design, fabricate, and install radiation shielding, medical doors, specialized MEP, and infection-controlled surfaces — with our own crews, our own Wood & Corian factory, and our own quality programme.',
      aboutBody2: "We don't subcontract the core of what we do. Every shielded room, every medical door, every Corian countertop is built by our people — from first drawing to final handover.",
      aboutCta: 'About EGC',
      aboutFeatures: [
        { icon: '🏥', title: 'OEM Room-Preparation Specialist', desc: 'Rooms built to the tolerances Siemens Healthineers, Philips, and GE equipment require.' },
        { icon: '🪵', title: 'In-House Manufacturing', desc: 'Our own Wood & Corian factory, our own craftsmen.' },
        { icon: '💻', title: 'Three Sectors, One Standard', desc: 'Healthcare construction, manufacturing, and software engineering.' },
      ],
      ctaLabel: 'Start a Conversation',
      ctaHeadline: 'Ready to discuss your project?',
      ctaSub: "Whether it's a hospital imaging department, a manufacturing order, or a software system — our team is ready to respond.",
      ctaPrimary: 'Contact Us',
    },
    ar: {
      heroLabel: 'جدة · المملكة العربية السعودية',
      heroHeadline1: 'نُجهّز الغرف',
      heroHeadlineAccent: 'التي تنتقل إليها معداتكم.',
      heroSub: 'مقاول متخصص في تجهيز الغرف الطبية — تدريع إنشائي للإشعاع والمجال المغناطيسي، وأبواب طبية، وأعمال كهروميكانيكية متخصصة، وأسطح مقاومة للعدوى لغرف الرنين المغناطيسي والأشعة المقطعية وPET-CT في جميع أنحاء المملكة العربية السعودية.',
      heroTrust: ['معتمدة بشهادة ISO 9001', '+18 عامًا في السعودية', '+150 مشروعًا منجزًا'],
      heroCtaPrimary: 'ماذا نبني',
      heroCtaSecondary: 'تواصل معنا',
      svcStripLabel: 'ماذا نبني',
      spotlightOverline: 'خبرتنا الأساسية',
      spotlightHeadline1: 'غرف مصممة لمعدات',
      spotlightHeadline2: 'الشركات المصنّعة، لا للاستخدام العام.',
      spotlightBody1: 'يبدأ عمل EGC الأكثر تخصصًا قبل وصول المعدات — ببناء الغرف التي تنتقل إليها أنظمة التصوير من Siemens Healthineers وPhilips Healthcare وGE Healthcare. تدريع إنشائي للإشعاع والمجال المغناطيسي، وأبواب طبية، وأعمال كهروميكانيكية متخصصة، مبنية وفق التفاوتات التي يتطلبها فريق تركيب كل شركة مصنّعة.',
      spotlightBody2: 'تعمل فرقنا جنبًا إلى جنب مع الفيزيائيين الإشعاعيين ومديري مشاريع المستشفيات وفرق تركيب الشركات المصنّعة لتسليم غرف تجتاز اختبارات الامتثال وتشغيل المعدات من أول محاولة — في المواعيد التي تهم العمليات السريرية.',
      spotlightChecklist: ['تدريع مغناطيسي وترددي لغرف الرنين المغناطيسي والأشعة المقطعية', 'أبواب مُبطّنة بالرصاص للتدريع الإشعاعي', 'أعمال كهروميكانيكية متخصصة لمعدات التصوير', 'أسطح ونجارة مقاومة للعدوى'],
      spotlightCta: 'الإنشاءات الطبية',
      spotlightBadgeLabel: 'التدريع الإنشائي للإشعاع والمجال المغناطيسي',
      servicesLabel: 'النطاق الكامل للعمل',
      servicesHeadline: 'أربعة تخصصات. مقاول واحد.',
      servicesSub: 'تجهيز الغرف الطبية هو تخصصنا — تدريع إنشائي، وأبواب طبية، وأعمال كهروميكانيكية متخصصة، وأسطح مقاومة للعدوى، كلها تحت برنامج جودة واحد.',
      manufacturingLabel: 'التصنيع',
      manufacturingHeadline: 'مدعومون بمصنعنا الخاص.',
      manufacturingBody: 'ينتج مصنع الخشب والكوريان التابع لـ EGC أعمال الأسطح الصلبة والنجارة خلف مشاريعنا الطبية — وله حضوره المستقل أيضًا، بأعمال بارزة تشمل التصميمات الداخلية لمطار جدة الدولي وعدد من المستشفيات العسكرية.',
      manufacturingCta: 'استعرض التصنيع',
      softwareLabel: 'هندسة البرمجيات',
      softwareHeadline: 'قطاع جديد، مبني على ما نتقنه بالفعل.',
      softwareBody: 'أنظمة معلومات المستشفيات والأشعة، وبرمجيات تخطيط الموارد والإدارة المصممة للتوافق مع الأنظمة السعودية، ومواقع إلكترونية للعملاء — من فريق يفهم المستشفيات ومواقع العمل بالفعل.',
      softwareCta: 'استعرض هندسة البرمجيات',
      galleryLabel: 'أعمالنا',
      galleryHeadline: 'أعمال منجزة في جميع أنحاء المملكة.',
      galleryCtaLabel: 'عرض جميع الأعمال',
      galleryMainCaption: 'تركيب غرفة رنين مغناطيسي — مشروع مستشفى بجدة',
      galleryMainService: 'الرعاية الصحية',
      galleryItem1Caption: 'تركيب أبواب معمارية',
      galleryItem1Service: 'النجارة',
      galleryItem2Caption: 'محطة تمريض كوريان — مشروع مستشفى',
      galleryItem2Service: 'الأسطح',
      aboutLabel: 'عن EGC',
      aboutHeadline: 'تأسست في جدة. تعمل في جميع أنحاء المملكة.',
      aboutBody1: 'شركة المجموعة الهندسية (EGC) مقاول متخصص مقره جدة يُجهّز الغرف الطبية لمعدات التصوير الطبي من الشركات المصنّعة. نصمم ونصنّع ونركّب التدريع الإشعاعي، والأبواب الطبية، والأعمال الكهروميكانيكية المتخصصة، والأسطح المقاومة للعدوى — بكوادرنا الخاصة، ومصنعنا الخاص للخشب والكوريان، وبرنامج جودتنا الخاص.',
      aboutBody2: 'لا نعهّد جوهر عملنا لجهات خارجية. كل غرفة مدرّعة، وكل باب طبي، وكل منضدة كوريان يبنيها فريقنا — من أول مخطط حتى التسليم النهائي.',
      aboutCta: 'عن EGC',
      aboutFeatures: [
        { icon: '🏥', title: 'متخصصون في تجهيز الغرف لمعدات الشركات المصنّعة', desc: 'غرف مبنية وفق التفاوتات التي تتطلبها معدات Siemens Healthineers وPhilips وGE.' },
        { icon: '🪵', title: 'تصنيع داخلي', desc: 'مصنعنا الخاص للخشب والكوريان، وحرفيونا الخاصون.' },
        { icon: '💻', title: 'ثلاثة قطاعات، معيار واحد', desc: 'الإنشاءات الطبية، والتصنيع، وهندسة البرمجيات.' },
      ],
      ctaLabel: 'ابدأ محادثة',
      ctaHeadline: 'مستعد لمناقشة مشروعك؟',
      ctaSub: 'سواء كان قسم تصوير بمستشفى، أو طلب تصنيع، أو نظامًا برمجيًا — فريقنا جاهز للاستجابة.',
      ctaPrimary: 'تواصل معنا',
    },
  },

  about: {
    en: {
      pageOverline: 'Company Profile',
      pageTitle: 'About Engineering Grouping Co.',
      pageSubtitle: 'A Jeddah-based specialty contractor preparing healthcare rooms for OEM medical imaging equipment — with an in-house manufacturing factory and a growing software engineering sector.',
      storyOverline: 'Our Story',
      storyHeadline1: 'Precision environments.',
      storyHeadline2: 'Built by our hands.',
      storyBody1: 'Engineering Grouping Co. (EGC) was founded in Jeddah on a straightforward conviction: the best way to deliver a specialist interior project is to control it entirely in-house. From the first shop drawing to the final surface polish, our people do the work.',
      storyBody2: 'Over time, healthcare room preparation became our core — preparing MRI, CT, PET-CT and X-ray rooms for Siemens Healthineers, Philips Healthcare, and GE Healthcare equipment. That work demands radiation and magnetic shielding measured in millimetres, medical doors that seal against RF leakage, and surfaces that meet clinical infection-control standards. EGC built the expertise, the tools, and the processes to deliver that work reliably.',
      storyBody3: "Alongside healthcare construction, our in-house Wood & Corian factory produces architectural joinery and solid-surface work at scale, and our newest sector — Software Engineering — builds the hospital information systems and managerial software that run alongside the rooms we build.",
      storyCta: 'What we build',
      quickFacts: [
        { num: '2006', label: 'Founded' },
        { num: '150+', label: 'Projects' },
        { num: '3', label: 'Sectors' },
        { num: '9', label: 'Regions' },
      ],
      valuesOverline: 'How we work',
      valuesHeadline: 'Four principles. Every project.',
      valuesSub: 'The same standards that apply to a radiation-shielded MRI room apply to a bespoke reception counter, or a line of code. Our principles don\'t flex by sector.',
      sectorsOverline: 'Who We Work With',
      sectorsHeadline: 'Healthcare and commercial clients.',
      sectorsCard1Title: 'Healthcare & Government',
      sectorsCard1Body: "EGC's primary clients are hospitals, medical cities, diagnostic centres, and the government health authorities that commission them, alongside the OEM equipment manufacturers whose installations we prepare rooms for.",
      sectorsCard1List: [
        'Government hospitals and medical cities',
        'Private hospital groups and diagnostic networks',
        'Oncology, radiology, and imaging departments',
        'Nuclear medicine and radiation therapy facilities',
        'OEM equipment manufacturers (Siemens Healthineers, Philips Healthcare, GE Healthcare)',
      ],
      sectorsCard2Title: 'Commercial & Hospitality',
      sectorsCard2Body: 'Beyond healthcare, EGC delivers interior joinery and surface works — and increasingly, software systems — for developers, EPC contractors, hospitality operators, and commercial tenants who need a specialist partner with in-house capacity.',
      sectorsCard2List: [
        'Commercial office buildings and towers',
        'Hotels, resorts, and hospitality fit-outs',
        'Café and F&B interior packages',
        'Retail and mixed-use development fit-outs',
        'Businesses needing ERP, HIS/RIS, or web software',
      ],
      certsOverline: 'Accreditations',
      certsHeadline: 'Quality. Safety. Environment.',
      certsSub: 'EGC operates under internationally recognised management systems across all sectors.',
      teamOverline: 'The Team',
      teamHeadline: 'The people behind the build.',
      teamSub: "Leadership and sector heads driving EGC's work from tender to handover.",
      teamPlaceholder: 'Leadership team profiles coming soon.',
      ctaOverline: 'Work With EGC',
      ctaHeadline: 'Ready to start your project?',
      ctaSub: 'Get in touch to discuss your scope, timeline, and requirements.',
      ctaPrimary: 'Contact Us',
      ctaSecondary: 'What We Build',
    },
    ar: {
      pageOverline: 'ملف الشركة',
      pageTitle: 'عن شركة المجموعة الهندسية',
      pageSubtitle: 'مقاول متخصص مقره جدة يُجهّز الغرف الطبية لمعدات التصوير الطبي من الشركات المصنّعة — بمصنع تصنيع داخلي وقطاع هندسة برمجيات متنامٍ.',
      storyOverline: 'قصتنا',
      storyHeadline1: 'بيئات دقيقة.',
      storyHeadline2: 'يبنيها أيدينا.',
      storyBody1: 'تأسست شركة المجموعة الهندسية (EGC) في جدة على قناعة بسيطة: أفضل طريقة لتنفيذ مشروع تجهيز داخلي متخصص هي التحكم الكامل فيه داخليًا. من أول مخطط تنفيذي حتى التلميع النهائي للسطح، فريقنا هو من ينفذ العمل.',
      storyBody2: 'مع الوقت، أصبح تجهيز الغرف الطبية جوهر عملنا — تجهيز غرف الرنين المغناطيسي والأشعة المقطعية وPET-CT والأشعة السينية لمعدات Siemens Healthineers وPhilips Healthcare وGE Healthcare. يتطلب هذا العمل تدريعًا إشعاعيًا ومغناطيسيًا يُقاس بالمليمتر، وأبوابًا طبية تمنع التسرب الترددي، وأسطحًا تلبي معايير التحكم بالعدوى السريرية. بنت EGC الخبرة والأدوات والعمليات اللازمة لتنفيذ هذا العمل بموثوقية.',
      storyBody3: 'إلى جانب الإنشاءات الطبية، ينتج مصنعنا الداخلي للخشب والكوريان أعمال النجارة المعمارية والأسطح الصلبة على نطاق واسع، ويبني قطاعنا الأحدث — هندسة البرمجيات — أنظمة معلومات المستشفيات والبرمجيات الإدارية التي تعمل جنبًا إلى جنب مع الغرف التي نبنيها.',
      storyCta: 'ماذا نبني',
      quickFacts: [
        { num: '2006', label: 'التأسيس' },
        { num: '+150', label: 'مشروعًا' },
        { num: '3', label: 'قطاعات' },
        { num: '9', label: 'مناطق' },
      ],
      valuesOverline: 'طريقة عملنا',
      valuesHeadline: 'أربعة مبادئ. في كل مشروع.',
      valuesSub: 'المعايير ذاتها التي تُطبّق على غرفة رنين مغناطيسي مدرّعة تُطبّق على مكتب استقبال مخصص، أو حتى سطر برمجي. مبادئنا لا تتغير باختلاف القطاع.',
      sectorsOverline: 'مع من نعمل',
      sectorsHeadline: 'عملاء من القطاعين الصحي والتجاري.',
      sectorsCard1Title: 'الرعاية الصحية والجهات الحكومية',
      sectorsCard1Body: 'عملاء EGC الرئيسيون هم المستشفيات والمدن الطبية ومراكز التشخيص والجهات الصحية الحكومية التي تكلّفها، إلى جانب الشركات المصنّعة للمعدات التي نُجهّز الغرف لتركيباتها.',
      sectorsCard1List: [
        'المستشفيات الحكومية والمدن الطبية',
        'مجموعات المستشفيات الخاصة وشبكات التشخيص',
        'أقسام الأورام والأشعة والتصوير',
        'منشآت الطب النووي والعلاج الإشعاعي',
        'الشركات المصنّعة للمعدات (Siemens Healthineers وPhilips Healthcare وGE Healthcare)',
      ],
      sectorsCard2Title: 'القطاع التجاري والضيافة',
      sectorsCard2Body: 'إلى جانب الرعاية الصحية، تقدم EGC أعمال النجارة الداخلية والأسطح — وبرمجيات بشكل متزايد — للمطورين ومقاولي EPC ومشغلي الضيافة والمستأجرين التجاريين الذين يحتاجون شريكًا متخصصًا بقدرة تنفيذ داخلية.',
      sectorsCard2List: [
        'المباني والأبراج التجارية',
        'الفنادق والمنتجعات ومشاريع الضيافة',
        'حزم تجهيز المقاهي والمطاعم',
        'مشاريع التجزئة والاستخدام المختلط',
        'الشركات التي تحتاج أنظمة تخطيط موارد أو مستشفيات أو برمجيات ويب',
      ],
      certsOverline: 'الاعتمادات',
      certsHeadline: 'الجودة. السلامة. البيئة.',
      certsSub: 'تعمل EGC وفق أنظمة إدارة معتمدة دوليًا في جميع قطاعاتها.',
      teamOverline: 'الفريق',
      teamHeadline: 'الأشخاص خلف كل مشروع.',
      teamSub: 'القيادة ورؤساء القطاعات الذين يقودون عمل EGC من العطاء حتى التسليم.',
      teamPlaceholder: 'الملفات التعريفية لفريق القيادة ستُضاف قريبًا.',
      ctaOverline: 'اعمل مع EGC',
      ctaHeadline: 'مستعد لبدء مشروعك؟',
      ctaSub: 'تواصل معنا لمناقشة نطاق العمل والجدول الزمني والمتطلبات.',
      ctaPrimary: 'تواصل معنا',
      ctaSecondary: 'ماذا نبني',
    },
  },

  whatWeBuild: {
    en: {
      pageOverline: 'Capabilities & Work',
      pageTitle: 'Healthcare Construction',
      pageSubtitle: 'EGC prepares healthcare rooms for OEM medical imaging equipment — structural radiation & magnetic shielding, medical doors, specialized MEP, and infection-controlled surfaces, delivered in-house.',
      introHeadline: 'Specialist room preparation, from MRI suites to nurse stations.',
      introBody: "Our work spans hospitals, diagnostic centres, and clinical facilities throughout Saudi Arabia. The common thread is precision — whether we're installing magnetic shielding in an MRI room or fitting a bespoke Corian nurse station, the standard doesn't change.",
      introStats: [
        { n: '150+', l: 'Projects Completed' },
        { n: '18+', l: 'Years Operating' },
        { n: '4', l: 'Specialist Disciplines' },
      ],
      capabilitiesHeading: 'What we deliver',
      serviceCta: 'Discuss a project',
      projectsOverline: 'Project Track Record',
      projectsHeadline: 'Our work spans the Kingdom.',
      projectsSub: 'From Jeddah and Riyadh to Dammam and the Aseer region — EGC has delivered healthcare room-preparation projects across Saudi Arabia. View our project map for details.',
      projectsCta: 'View Project Map',
      projectsSeeAll: 'See all projects',
      ctaOverline: 'Start a conversation',
      ctaHeadline: 'Discuss your project scope.',
      ctaSub: 'Whether you need a full radiology department, a single shielded room, or a multi-site specification — our team will respond quickly.',
      ctaPrimary: 'Contact Us',
    },
    ar: {
      pageOverline: 'القدرات والأعمال',
      pageTitle: 'الإنشاءات الطبية',
      pageSubtitle: 'تُجهّز EGC الغرف الطبية لمعدات التصوير الطبي من الشركات المصنّعة — تدريع إنشائي للإشعاع والمجال المغناطيسي، وأبواب طبية، وأعمال كهروميكانيكية متخصصة، وأسطح مقاومة للعدوى، كلها منفذة داخليًا.',
      introHeadline: 'تجهيز متخصص للغرف، من أجنحة الرنين المغناطيسي إلى محطات التمريض.',
      introBody: 'يمتد عملنا عبر المستشفيات ومراكز التشخيص والمنشآت السريرية في جميع أنحاء المملكة العربية السعودية. القاسم المشترك هو الدقة — سواء كنا نركّب تدريعًا مغناطيسيًا في غرفة رنين مغناطيسي أو نُجهّز محطة تمريض كوريان مخصصة، فإن المعيار لا يتغير.',
      introStats: [
        { n: '+150', l: 'مشروعًا مكتملًا' },
        { n: '+18', l: 'عامًا من التشغيل' },
        { n: '4', l: 'تخصصات دقيقة' },
      ],
      capabilitiesHeading: 'ماذا نقدّم',
      serviceCta: 'ناقش مشروعك',
      projectsOverline: 'سجل المشاريع',
      projectsHeadline: 'أعمالنا تمتد عبر المملكة.',
      projectsSub: 'من جدة والرياض إلى الدمام ومنطقة عسير — نفذت EGC مشاريع تجهيز غرف طبية في جميع أنحاء المملكة العربية السعودية. استعرض خريطة مشاريعنا للتفاصيل.',
      projectsCta: 'عرض خريطة المشاريع',
      projectsSeeAll: 'عرض جميع المشاريع',
      ctaOverline: 'ابدأ محادثة',
      ctaHeadline: 'ناقش نطاق مشروعك.',
      ctaSub: 'سواء احتجت قسم أشعة كاملًا، أو غرفة مدرّعة واحدة، أو مواصفات لعدة مواقع — سيستجيب فريقنا بسرعة.',
      ctaPrimary: 'تواصل معنا',
    },
  },

  careers: {
    en: {
      pageOverline: 'Careers',
      pageTitle: 'Build the rooms that matter.',
      pageSubtitle: 'Open positions across healthcare projects, manufacturing, software engineering, and corporate functions at EGC.',
      cultureOverline: 'Why EGC',
      cultureHeadline: 'A specialist across three sectors.',
      positionsOverline: 'Open Positions',
      positionsHeadline: 'Current openings.',
      applyLabel: 'Apply Now',
      openAppTitle: "Don't see the right role?",
      openAppSub: 'Send us an open application — we review CVs against upcoming openings across all three sectors.',
      openAppButton: 'Send open application',
      mailSubject: 'Open Application — EGC Careers',
      mailBody: 'Hello EGC team,\n\nI would like to submit my CV for future opportunities.\n\n',
      applyMailSubjectPrefix: 'Application — ',
      applyMailBody: 'Hello EGC team,\n\nI would like to apply for the following position: ',
    },
    ar: {
      pageOverline: 'الوظائف',
      pageTitle: 'ابنِ الغرف التي تُحدث فرقًا.',
      pageSubtitle: 'وظائف شاغرة في المشاريع الطبية والتصنيع وهندسة البرمجيات والوظائف الإدارية لدى EGC.',
      cultureOverline: 'لماذا EGC',
      cultureHeadline: 'متخصصون عبر ثلاثة قطاعات.',
      positionsOverline: 'الوظائف الشاغرة',
      positionsHeadline: 'الشواغر الحالية.',
      applyLabel: 'قدّم الآن',
      openAppTitle: 'لم تجد الوظيفة المناسبة؟',
      openAppSub: 'أرسل لنا طلبًا مفتوحًا — نراجع السير الذاتية مقابل الشواغر القادمة عبر القطاعات الثلاثة.',
      openAppButton: 'إرسال طلب مفتوح',
      mailSubject: 'طلب مفتوح — وظائف EGC',
      mailBody: 'مرحبًا فريق EGC،\n\nأرغب في تقديم سيرتي الذاتية للفرص المستقبلية.\n\n',
      applyMailSubjectPrefix: 'طلب توظيف — ',
      applyMailBody: 'مرحبًا فريق EGC،\n\nأرغب في التقديم على الوظيفة التالية: ',
    },
  },

  suppliers: {
    en: {
      pageOverline: 'Supplier Network',
      pageTitle: 'Become a Registered EGC Supplier.',
      pageSubtitle: 'EGC sources materials, products, and services across healthcare construction, manufacturing, and software engineering through a single vendor network managed on our ERP platform. Register once — receive RFQs across all our active projects.',
      sourceOverline: 'Procurement Categories',
      sourceHeadline: 'What we source.',
      sourceSub: 'We procure materials, products, and services across four categories year-round.',
      regOverline: 'Registration Process',
      regHeadline: 'How to register.',
      regBody: 'The process takes less than 30 minutes. Complete your registration on the EGC ERP portal and our procurement team will review your submission.',
      portalLabel: 'EGC ERP — SUPPLIER PORTAL',
      portalHeadline: 'Register or sign in to the Supplier Portal.',
      portalBody: 'Create your vendor profile, submit prequalification documents, and respond to RFQs — all in one place.',
      portalRegister: 'Register on the Supplier Portal',
      portalSignin: 'Already registered? Sign in',
      portalHelp: 'For portal access issues, contact',
      reqOverline: "What You'll Need",
      reqHeadline: 'Registration requirements.',
      reqBody: 'Prepare these documents before starting your registration. Incomplete submissions may delay the prequalification review.',
      faqOverline: 'FAQs',
      faqHeadline: 'Frequently asked questions.',
    },
    ar: {
      pageOverline: 'شبكة الموردين',
      pageTitle: 'كن موردًا معتمدًا لدى EGC.',
      pageSubtitle: 'تشتري EGC المواد والمنتجات والخدمات عبر الإنشاءات الطبية والتصنيع وهندسة البرمجيات من خلال شبكة موردين واحدة تُدار على منصة تخطيط الموارد لدينا. سجّل مرة واحدة — واستلم طلبات عروض الأسعار عبر جميع مشاريعنا النشطة.',
      sourceOverline: 'فئات المشتريات',
      sourceHeadline: 'ماذا نشتري.',
      sourceSub: 'نشتري المواد والمنتجات والخدمات عبر أربع فئات على مدار العام.',
      regOverline: 'عملية التسجيل',
      regHeadline: 'كيفية التسجيل.',
      regBody: 'تستغرق العملية أقل من 30 دقيقة. أكمل تسجيلك على بوابة EGC ERP وسيراجع فريق المشتريات طلبك.',
      portalLabel: 'بوابة موردي EGC ERP',
      portalHeadline: 'سجّل أو سجّل الدخول إلى بوابة الموردين.',
      portalBody: 'أنشئ ملفك كمورد، وقدّم مستندات التأهيل المسبق، وردّ على طلبات عروض الأسعار — كل ذلك في مكان واحد.',
      portalRegister: 'سجّل في بوابة الموردين',
      portalSignin: 'مسجل بالفعل؟ سجّل الدخول',
      portalHelp: 'لمشاكل الدخول إلى البوابة، تواصل مع',
      reqOverline: 'ما ستحتاجه',
      reqHeadline: 'متطلبات التسجيل.',
      reqBody: 'جهّز هذه المستندات قبل بدء التسجيل. قد تؤخر الطلبات غير المكتملة مراجعة التأهيل المسبق.',
      faqOverline: 'الأسئلة الشائعة',
      faqHeadline: 'الأسئلة المتكررة.',
    },
  },

  projects: {
    en: {
      pageOverline: 'Our Track Record',
      pageTitle: 'Projects across the Kingdom.',
      pageSubtitle: 'Healthcare room preparation, manufacturing, and specialist fabrication — delivered by EGC\'s own crews. Click any city pin on the map to explore projects in that location.',
      statDelivered: 'Projects Delivered',
      statActive: 'Active Right Now',
      statCities: 'Cities & Regions',
      statServiceLines: 'Service Lines',
      mapCaption: 'KINGDOM OF SAUDI ARABIA — EGC PROJECT FOOTPRINT',
      hintTitle: 'Select a city',
      hintSub: 'Click any numbered pin on the map to explore projects delivered in that city or region.',
      cityPanelProjectsSuffix: 'projects in this city',
      cityPanelProjectSuffix: 'project in this city',
      cityPanelEmpty: 'No projects match this filter for',
      closePanel: 'Close panel',
      allProjectsLabel: 'All Projects',
      projectsShownSuffix: 'shown',
      projectsInSuffix: 'in',
      clearCityFilter: 'Clear city filter',
      emptyState: 'No projects match the current filters.',
      ctaOverline: 'Your Project',
      ctaHeadline: 'Discuss your scope with our team.',
      ctaSub: "Whether you have tender documents or just a concept, we're ready to discuss how EGC can deliver — healthcare rooms, manufacturing, and software systems.",
      ctaPrimary: 'Contact Us',
      ctaSecondary: 'What We Build',
    },
    ar: {
      pageOverline: 'سجل أعمالنا',
      pageTitle: 'مشاريع في جميع أنحاء المملكة.',
      pageSubtitle: 'تجهيز الغرف الطبية، والتصنيع، والتصنيع المتخصص — تنفذها كوادر EGC الخاصة. انقر على أي دبوس مدينة على الخريطة لاستكشاف المشاريع في ذلك الموقع.',
      statDelivered: 'مشروعًا منجزًا',
      statActive: 'نشط حاليًا',
      statCities: 'مدن ومناطق',
      statServiceLines: 'خطوط خدمة',
      mapCaption: 'المملكة العربية السعودية — البصمة الجغرافية لمشاريع EGC',
      hintTitle: 'اختر مدينة',
      hintSub: 'انقر على أي دبوس مرقّم على الخريطة لاستكشاف المشاريع المنفذة في تلك المدينة أو المنطقة.',
      cityPanelProjectsSuffix: 'مشاريع في هذه المدينة',
      cityPanelProjectSuffix: 'مشروع في هذه المدينة',
      cityPanelEmpty: 'لا توجد مشاريع تطابق هذا الفلتر في',
      closePanel: 'إغلاق اللوحة',
      allProjectsLabel: 'جميع المشاريع',
      projectsShownSuffix: 'معروض',
      projectsInSuffix: 'في',
      clearCityFilter: 'مسح فلتر المدينة',
      emptyState: 'لا توجد مشاريع تطابق الفلاتر الحالية.',
      ctaOverline: 'مشروعك',
      ctaHeadline: 'ناقش نطاق عملك مع فريقنا.',
      ctaSub: 'سواء كانت لديك مستندات مناقصة أو مجرد فكرة، نحن مستعدون لمناقشة كيف يمكن لـ EGC التنفيذ — غرف طبية، وتصنيع، وأنظمة برمجية.',
      ctaPrimary: 'تواصل معنا',
      ctaSecondary: 'ماذا نبني',
    },
  },

  contact: {
    en: {
      pageOverline: 'Get In Touch',
      pageTitle: 'Tell us about your project.',
      pageSubtitle: 'Our business development team responds within 1–2 business days. For urgent enquiries, call us directly.',
      formTitle: 'Project Enquiry',
      labelName: 'Full name *',
      placeholderName: 'Your full name',
      labelCompany: 'Company',
      placeholderCompany: 'Company name',
      labelEmail: 'Email *',
      placeholderEmail: 'you@company.com',
      labelPhone: 'Phone',
      placeholderPhone: '+966 5x xxx xxxx',
      labelSector: 'Sector',
      labelService: 'Service of interest',
      labelMessage: 'Message *',
      placeholderMessage: 'Tell us about your project — scope, location, timeline, and any technical requirements.',
      submitLabel: 'Send message',
      sectors: ['Government', 'Private', 'Industrial', 'Other'],
      services: ['Healthcare Construction', 'Manufacturing', 'Software Engineering', 'Multiple Sectors', 'Not sure'],
      successTitle: 'Message received.',
      successBody: 'Our team will be in touch within 1–2 business days.',
      successButton: 'Send another message',
      officeTitle: 'Head Office',
      officeHoursLabel: undefined,
      supplierLabel: 'Supplier Portal',
      supplierLink: 'Open the Supplier Portal',
      connectLabel: 'Connect',
      linkedinLabel: 'LinkedIn — EGC',
      altOverline: 'Other Ways to Reach Us',
      altHeadline: 'Direct contacts.',
      altCards: [
        { title: 'General Enquiries', desc: 'For project enquiries, capability discussions, and general information.', linkLabel: 'email' },
        { title: 'Supplier Portal', desc: 'Vendor registration, prequalification documents, and RFQ responses.', linkLabel: 'erp.egc-me.com' },
        { title: 'Careers', desc: 'Job applications and open CV submissions for future positions.', linkLabel: 'View open positions' },
      ],
    },
    ar: {
      pageOverline: 'تواصل معنا',
      pageTitle: 'أخبرنا عن مشروعك.',
      pageSubtitle: 'يستجيب فريق تطوير الأعمال لدينا خلال يوم إلى يومي عمل. للاستفسارات العاجلة، اتصل بنا مباشرة.',
      formTitle: 'استفسار عن مشروع',
      labelName: 'الاسم الكامل *',
      placeholderName: 'اسمك الكامل',
      labelCompany: 'الشركة',
      placeholderCompany: 'اسم الشركة',
      labelEmail: 'البريد الإلكتروني *',
      placeholderEmail: 'you@company.com',
      labelPhone: 'الهاتف',
      placeholderPhone: '+966 5x xxx xxxx',
      labelSector: 'القطاع',
      labelService: 'الخدمة المطلوبة',
      labelMessage: 'الرسالة *',
      placeholderMessage: 'أخبرنا عن مشروعك — النطاق، الموقع، الجدول الزمني، وأي متطلبات فنية.',
      submitLabel: 'إرسال الرسالة',
      sectors: ['حكومي', 'خاص', 'صناعي', 'أخرى'],
      services: ['الإنشاءات الطبية', 'التصنيع', 'هندسة البرمجيات', 'عدة قطاعات', 'غير متأكد'],
      successTitle: 'تم استلام رسالتك.',
      successBody: 'سيتواصل معك فريقنا خلال يوم إلى يومي عمل.',
      successButton: 'إرسال رسالة أخرى',
      officeTitle: 'المكتب الرئيسي',
      supplierLabel: 'بوابة الموردين',
      supplierLink: 'فتح بوابة الموردين',
      connectLabel: 'تواصل',
      linkedinLabel: 'لينكدإن — EGC',
      altOverline: 'طرق أخرى للتواصل',
      altHeadline: 'جهات تواصل مباشرة.',
      altCards: [
        { title: 'استفسارات عامة', desc: 'للاستفسارات عن المشاريع، ومناقشة القدرات، والمعلومات العامة.', linkLabel: 'البريد الإلكتروني' },
        { title: 'بوابة الموردين', desc: 'تسجيل الموردين، ومستندات التأهيل المسبق، والرد على طلبات عروض الأسعار.', linkLabel: 'erp.egc-me.com' },
        { title: 'الوظائف', desc: 'طلبات التوظيف وتقديم السير الذاتية المفتوحة للوظائف المستقبلية.', linkLabel: 'عرض الوظائف الشاغرة' },
      ],
    },
  },
};
