/* Page-level copy for the supporting pages. Structured data used on the same
 * pages (projects, careers, suppliers…) lives in its own module. */
export const COPY = {
  projects: {
    en: {
      h1: 'Projects across the Kingdom',
      lead: 'Healthcare room preparation, manufacturing and specialist fabrication, delivered by EGC’s own crews. Select a city on the map to see its projects.',
      notice: 'Project entries are illustrative while verified case studies are being prepared.',
      statDelivered: 'Projects delivered',
      statActive: 'Active now',
      statCities: 'Cities',
      statRegions: 'Regions served',
      mapLabel: 'Map of Saudi Arabia with EGC project locations',
      hintTitle: 'Select a city',
      hintText: 'Choose a numbered pin on the map to see the projects delivered there.',
      projectSingular: 'project',
      projectPlural: 'projects',
      inThisCity: 'in this city',
      noneFor: 'No projects match this filter in',
      close: 'Close',
      allProjects: 'All projects',
      inCity: 'in',
      clearCity: 'Clear city filter',
      empty: 'No projects match the current filters.',
      ctaTitle: 'Discuss your scope with our team',
      ctaText: 'Whether you have tender documents or just a concept, we can tell you how EGC would deliver it.',
    },
    ar: {
      h1: 'مشاريع في أنحاء المملكة',
      lead: 'تجهيز الغرف الطبية والتصنيع والأعمال المتخصصة، تنفذها كوادر EGC الخاصة. اختر مدينة على الخريطة لتعرض مشاريعها.',
      notice: 'بيانات المشاريع توضيحية إلى حين اكتمال دراسات الحالة الموثّقة.',
      statDelivered: 'مشروعًا منجزًا',
      statActive: 'قيد التنفيذ الآن',
      statCities: 'مدن',
      statRegions: 'مناطق مخدومة',
      mapLabel: 'خريطة المملكة العربية السعودية بمواقع مشاريع EGC',
      hintTitle: 'اختر مدينة',
      hintText: 'اختر دبوسًا مرقّمًا على الخريطة لتعرض المشاريع المنفذة هناك.',
      projectSingular: 'مشروع',
      projectPlural: 'مشاريع',
      inThisCity: 'في هذه المدينة',
      noneFor: 'لا توجد مشاريع تطابق هذا الفلتر في',
      close: 'إغلاق',
      allProjects: 'جميع المشاريع',
      inCity: 'في',
      clearCity: 'مسح فلتر المدينة',
      empty: 'لا توجد مشاريع تطابق الفلاتر الحالية.',
      ctaTitle: 'ناقش نطاق عملك مع فريقنا',
      ctaText: 'سواء كانت لديك مستندات مناقصة أو مجرد فكرة، نوضح لك كيف ستنفذها EGC.',
    },
  },

  careers: {
    en: {
      h1: 'Build the rooms that matter',
      lead: 'Open roles across healthcare projects, the Wood & Corian factory, software engineering and corporate functions.',
      whyTitle: 'Why EGC',
      positionsTitle: 'Open positions',
      apply: 'Apply by email',
      openAppTitle: 'Don’t see the right role?',
      openAppText: 'Send an open application. We review CVs against upcoming openings across all our businesses.',
      openAppButton: 'Send an open application',
      mailSubject: 'Open application — EGC Careers',
      mailBody: 'Hello EGC team,\n\nI would like to submit my CV for future opportunities.\n\n',
      applySubject: 'Application — ',
      applyBody: 'Hello EGC team,\n\nI would like to apply for the following position: ',
    },
    ar: {
      h1: 'ابنِ الغرف التي تُحدث فرقًا',
      lead: 'وظائف شاغرة في المشاريع الطبية ومصنع الخشب والكوريان وهندسة البرمجيات والوظائف الإدارية.',
      whyTitle: 'لماذا EGC',
      positionsTitle: 'الوظائف الشاغرة',
      apply: 'قدّم عبر البريد',
      openAppTitle: 'لم تجد الوظيفة المناسبة؟',
      openAppText: 'أرسل طلبًا مفتوحًا. نراجع السير الذاتية مقابل الشواغر القادمة في جميع أعمالنا.',
      openAppButton: 'أرسل طلبًا مفتوحًا',
      mailSubject: 'طلب مفتوح — وظائف EGC',
      mailBody: 'مرحبًا فريق EGC،\n\nأرغب في تقديم سيرتي الذاتية للفرص المستقبلية.\n\n',
      applySubject: 'طلب توظيف — ',
      applyBody: 'مرحبًا فريق EGC،\n\nأرغب في التقديم على الوظيفة التالية: ',
    },
  },

  suppliers: {
    en: {
      h1: 'Become an approved EGC supplier',
      lead: 'EGC sources materials, products and services across healthcare construction, manufacturing and software through one vendor network on our ERP platform. Register once and receive RFQs across our active projects.',
      sourceTitle: 'What we source',
      sourceLead: 'We buy materials, products and services across four categories all year.',
      regTitle: 'How to register',
      regLead: 'Registration takes under 30 minutes. Complete it on the EGC ERP portal and our procurement team will review your submission.',
      portalLabel: 'EGC ERP supplier portal',
      portalTitle: 'Register or sign in',
      portalText: 'Create your vendor profile, submit prequalification documents and respond to RFQs in one place.',
      portalRegister: 'Register on the portal',
      portalSignin: 'Already registered? Sign in',
      portalHelp: 'For portal access issues, contact',
      reqTitle: 'Registration requirements',
      reqLead: 'Prepare these documents first. Incomplete submissions delay prequalification.',
    },
    ar: {
      h1: 'كن موردًا معتمدًا لدى EGC',
      lead: 'تشتري EGC المواد والمنتجات والخدمات عبر الإنشاءات الطبية والتصنيع والبرمجيات من خلال شبكة موردين واحدة على منصة تخطيط الموارد لدينا. سجّل مرة واحدة واستلم طلبات عروض الأسعار عبر مشاريعنا النشطة.',
      sourceTitle: 'ما نشتريه',
      sourceLead: 'نشتري المواد والمنتجات والخدمات عبر أربع فئات على مدار العام.',
      regTitle: 'كيفية التسجيل',
      regLead: 'يستغرق التسجيل أقل من 30 دقيقة. أكمله على بوابة EGC ERP وسيراجع فريق المشتريات طلبك.',
      portalLabel: 'بوابة موردي EGC ERP',
      portalTitle: 'سجّل أو سجّل الدخول',
      portalText: 'أنشئ ملف المورد وقدّم مستندات التأهيل المسبق وردّ على طلبات عروض الأسعار في مكان واحد.',
      portalRegister: 'سجّل في البوابة',
      portalSignin: 'مسجل بالفعل؟ سجّل الدخول',
      portalHelp: 'لمشاكل الدخول إلى البوابة تواصل مع',
      reqTitle: 'متطلبات التسجيل',
      reqLead: 'جهّز هذه المستندات أولًا. الطلبات غير المكتملة تؤخر التأهيل المسبق.',
    },
  },

  contact: {
    en: {
      h1: 'Tell us about your project',
      lead: 'Our business development team replies within one to two working days. For anything urgent, call us.',
      formTitle: 'Project enquiry',
      formNote: 'Submitting opens your email app with the enquiry ready to send to info@egc-me.com.',
      name: 'Full name',
      company: 'Company',
      email: 'Email',
      phone: 'Phone',
      sector: 'Sector',
      service: 'Area of interest',
      message: 'Message',
      messagePlaceholder: 'Equipment model, location, programme, anything we should know.',
      submit: 'Send enquiry',
      required: 'required',
      sectors: ['Government', 'Private healthcare', 'Industrial', 'Commercial', 'Other'],
      services: ['Healthcare construction', 'Manufacturing (Corian / joinery)', 'Software engineering', 'Nurse call / turnkey systems', 'Several of the above', 'Not sure yet'],
      sentTitle: 'Your email app should have opened',
      sentText: 'If it did not, write to us directly at info@egc-me.com and include the same details.',
      sentAgain: 'Edit and send again',
      subjectPrefix: 'Project enquiry — ',
      officeTitle: 'Head office',
      altTitle: 'Other ways to reach us',
    },
    ar: {
      h1: 'أخبرنا عن مشروعك',
      lead: 'يرد فريق تطوير الأعمال خلال يوم إلى يومي عمل. وللأمور العاجلة اتصل بنا.',
      formTitle: 'استفسار عن مشروع',
      formNote: 'عند الإرسال يفتح تطبيق البريد لديك والاستفسار جاهز للإرسال إلى info@egc-me.com.',
      name: 'الاسم الكامل',
      company: 'الشركة',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      sector: 'القطاع',
      service: 'مجال الاهتمام',
      message: 'الرسالة',
      messagePlaceholder: 'طراز الجهاز، الموقع، الجدول الزمني، وأي شيء ينبغي أن نعرفه.',
      submit: 'أرسل الاستفسار',
      required: 'مطلوب',
      sectors: ['حكومي', 'قطاع صحي خاص', 'صناعي', 'تجاري', 'أخرى'],
      services: ['الإنشاءات الطبية', 'التصنيع (كوريان / نجارة)', 'هندسة البرمجيات', 'أنظمة نداء الممرضات / التسليم الشامل', 'أكثر من مجال', 'لم أحدد بعد'],
      sentTitle: 'يُفترض أن يكون تطبيق البريد قد فُتح',
      sentText: 'إن لم يُفتح فراسلنا مباشرة على info@egc-me.com مع التفاصيل نفسها.',
      sentAgain: 'عدّل وأرسل مجددًا',
      subjectPrefix: 'استفسار عن مشروع — ',
      officeTitle: 'المقر الرئيسي',
      altTitle: 'طرق أخرى للتواصل',
    },
  },
};
