/* The four Healthcare Construction pillars ("What We Build"). Same card
 * shape the old SERVICES/DIVISIONS export used (num/label/tag/summary/desc/
 * capabilities/image/thumb), so WhatWeBuild.jsx and Home.jsx's existing
 * mapping logic is reused as-is — only the content changed. */
export const SERVICES = {
  en: [
    {
      id: 'shielding',
      num: '01',
      label: 'Structural Radiation & Magnetic Shielding',
      shortLabel: 'Shielding',
      tag: 'MRI · CT · PET-CT · X-Ray · Nuclear Medicine',
      summary: 'Structural shielding for MRI, CT, PET-CT, X-ray and nuclear medicine rooms — magnetic, RF and radiation containment built to OEM and physicist specification.',
      desc: "EGC engineers and constructs the shielding layer that makes a diagnostic or therapy room safe to operate — from the magnetic and RF (Faraday cage) shielding an MRI suite requires, to the lead-lined structural shielding for CT, PET-CT, X-ray and nuclear medicine rooms. We work directly against OEM equipment specifications (Siemens Healthineers, Philips Healthcare, GE Healthcare) and alongside radiation physicists so rooms pass attenuation and leakage compliance testing on the first attempt.",
      capabilities: [
        'MRI suite construction with full magnetic (Faraday cage) and RF shielding',
        'CT, PET-CT and X-ray room lead-lined radiation shielding',
        'Nuclear medicine and radiation therapy (LINAC) vault construction',
        'Shielding design coordination with radiation physicists',
        'Attenuation and leakage compliance testing support',
        'Retrofit shielding for existing diagnostic rooms',
      ],
      image: '/images/healthcare-xray.jpg',
      thumb: '/images/healthcare-xray.jpg',
    },
    {
      id: 'doors',
      num: '02',
      label: 'Medical Doors & Access Systems',
      shortLabel: 'Doors',
      tag: 'Radiation-Shielded · RF-Shielded · Hermetic · Access Control',
      summary: 'Lead-lined and RF-shielded doors, hermetic sliding doors, and access control systems fabricated and installed to seal controlled clinical environments.',
      desc: 'A shielded room is only as effective as its doors. EGC fabricates and installs lead-lined radiation-shielded doors, RF-shielded doors integrated into an MRI suite\'s Faraday cage, and hermetic sliding doors for controlled clinical areas — built to the tolerances the equipment and the room\'s shielding design demand, with access control and interlock integration where the space requires it.',
      capabilities: [
        'Lead-lined radiation-shielded doors (manual and motorized)',
        'RF-shielded doors and Faraday cage door integration for MRI suites',
        'Hermetic sliding doors for controlled clinical areas',
        'Access control and interlock integration for radiation rooms',
        'Door leaf and frame fabrication to OEM equipment specifications',
        'Site installation, sealing and commissioning',
      ],
      image: null,
      thumb: null,
    },
    {
      id: 'mep',
      num: '03',
      label: 'Specialized MEP',
      shortLabel: 'MEP',
      tag: 'Medical Gases · Electrical · Grounding · Controlled HVAC',
      summary: 'Mechanical, electrical and plumbing works engineered specifically for imaging equipment — medical gases, grounding, EMI/RFI-aware routing, and controlled-environment HVAC.',
      desc: "Imaging equipment has MEP requirements a general contractor's standard scope doesn't cover — dedicated grounding, EMI/RFI-aware cable containment, medical gas pipelines, and HVAC engineered to hold the temperature and humidity tolerances diagnostic and therapy equipment need. EGC delivers this scope in coordination with the OEM's own installation and commissioning teams.",
      capabilities: [
        'Medical gas pipeline systems (oxygen, medical air, vacuum)',
        'Electrical infrastructure and grounding for imaging equipment',
        'EMI/RFI-aware cable routing and containment',
        'HVAC design and installation for controlled clinical environments',
        "Coordination with OEM installation teams during equipment commissioning",
        'MEP shop drawings and as-built documentation',
      ],
      image: null,
      thumb: null,
    },
    {
      id: 'surfaces',
      num: '04',
      label: 'Infection Controlled Surfaces & Joinery',
      shortLabel: 'Surfaces',
      tag: 'Corian · Clinical Countertops · Nurse Stations · Medical Joinery',
      summary: 'Seamless, non-porous solid-surface fabrication and medical-grade joinery engineered for clinical cleaning and infection-control protocols.',
      desc: "Everything that gets touched, cleaned, and disinfected in a clinical environment runs through EGC's own Corian and joinery workshop. We fabricate seamless solid-surface countertops, nurse stations, and vanities, plus antimicrobial panelling and medical-grade cabinetry — built without the seams and joints that trap contamination, and finished to the standard infection-control protocols demand.",
      capabilities: [
        'Corian and solid-surface clinical countertops and vanities',
        'Seamless nurse stations and reception counters',
        'Antimicrobial wall panelling and cladding',
        'Medical-grade cabinetry and clinical storage joinery',
        'Laboratory and workstation surface fabrication',
        'Custom profiles engineered for infection-control cleaning protocols',
      ],
      image: '/images/corian-surfaces.jpg',
      thumb: '/images/joinery-doors.jpg',
    },
  ],
  ar: [
    {
      id: 'shielding',
      num: '01',
      label: 'التدريع الإنشائي للإشعاع والمجال المغناطيسي',
      shortLabel: 'التدريع',
      tag: 'الرنين المغناطيسي · الأشعة المقطعية · PET-CT · الأشعة السينية · الطب النووي',
      summary: 'تدريع إنشائي لغرف الرنين المغناطيسي والأشعة المقطعية وPET-CT والأشعة السينية والطب النووي — احتواء مغناطيسي وترددي وإشعاعي وفق مواصفات الشركات المصنّعة والفيزيائي الإشعاعي.',
      desc: 'تصمم EGC وتنفذ طبقة التدريع التي تجعل غرفة التشخيص أو العلاج آمنة للتشغيل — من التدريع المغناطيسي والترددي (قفص فاراداي) الذي تتطلبه غرفة الرنين المغناطيسي، إلى التدريع الإنشائي المُبطّن بالرصاص لغرف الأشعة المقطعية وPET-CT والأشعة السينية والطب النووي. نعمل مباشرة وفق مواصفات معدات الشركات المصنّعة (Siemens Healthineers وPhilips Healthcare وGE Healthcare) وبالتنسيق مع الفيزيائيين الإشعاعيين حتى تجتاز الغرف اختبارات التوهين والتسرب الإشعاعي من أول محاولة.',
      capabilities: [
        'إنشاء غرف الرنين المغناطيسي بتدريع مغناطيسي كامل (قفص فاراداي) وترددي',
        'تدريع إشعاعي مُبطّن بالرصاص لغرف الأشعة المقطعية وPET-CT والأشعة السينية',
        'إنشاء غرف الطب النووي والعلاج الإشعاعي (مسرعات الخطي LINAC)',
        'تنسيق تصميم التدريع مع الفيزيائيين الإشعاعيين',
        'دعم اختبارات التوهين والتسرب الإشعاعي والامتثال',
        'أعمال تدريع لتحديث الغرف التشخيصية القائمة',
      ],
      image: '/images/healthcare-xray.jpg',
      thumb: '/images/healthcare-xray.jpg',
    },
    {
      id: 'doors',
      num: '02',
      label: 'الأبواب الطبية وأنظمة التحكم بالدخول',
      shortLabel: 'الأبواب',
      tag: 'مدرّعة إشعاعيًا · مدرّعة ترددياً · هرمتيكية · تحكم بالدخول',
      summary: 'أبواب مُبطّنة بالرصاص ومدرّعة ترددياً، وأبواب انزلاقية هرمتيكية، وأنظمة تحكم بالدخول — تُصنّع وتُركّب لإحكام غلق البيئات السريرية المتحكم بها.',
      desc: 'فعالية الغرفة المدرّعة تتوقف على أبوابها بقدر ما تتوقف على جدرانها. تصنّع EGC وتركّب أبوابًا مُبطّنة بالرصاص للتدريع الإشعاعي، وأبوابًا مدرّعة ترددياً مدمجة ضمن قفص فاراداي لغرفة الرنين المغناطيسي، وأبوابًا انزلاقية هرمتيكية للمناطق السريرية المتحكم بها — تُصنّع وفق التفاوتات التي تتطلبها المعدات وتصميم تدريع الغرفة، مع دمج أنظمة التحكم بالدخول والقفل التأميني حيثما يتطلب ذلك.',
      capabilities: [
        'أبواب مُبطّنة بالرصاص للتدريع الإشعاعي (يدوية ومؤتمتة)',
        'أبواب مدرّعة ترددياً ودمجها ضمن قفص فاراداي لغرف الرنين المغناطيسي',
        'أبواب انزلاقية هرمتيكية للمناطق السريرية المتحكم بها',
        'دمج أنظمة التحكم بالدخول والقفل التأميني لغرف الإشعاع',
        'تصنيع ألواح وإطارات الأبواب وفق مواصفات معدات الشركات المصنّعة',
        'التركيب الميداني والإحكام والتشغيل',
      ],
      image: null,
      thumb: null,
    },
    {
      id: 'mep',
      num: '03',
      label: 'الأعمال الكهروميكانيكية المتخصصة',
      shortLabel: 'الكهروميكانيكية',
      tag: 'الغازات الطبية · الأعمال الكهربائية · التأريض · تكييف متحكم به',
      summary: 'أعمال ميكانيكية وكهربائية وسباكة مصممة خصيصًا لمعدات التصوير — غازات طبية، تأريض، توجيه كابلات واعٍ بالتداخل الكهرومغناطيسي، وتكييف للبيئات المتحكم بها.',
      desc: 'لمعدات التصوير متطلبات كهروميكانيكية لا يغطيها النطاق القياسي لمقاول عام — تأريض مخصص، توجيه كابلات واعٍ بالتداخل الكهرومغناطيسي والترددي، خطوط غازات طبية، وتكييف مصمم للحفاظ على تفاوتات الحرارة والرطوبة التي تحتاجها معدات التشخيص والعلاج. تنفذ EGC هذا النطاق بالتنسيق مع فرق التركيب والتشغيل الخاصة بالشركة المصنّعة.',
      capabilities: [
        'أنظمة خطوط الغازات الطبية (الأكسجين، الهواء الطبي، الشفط)',
        'البنية التحتية الكهربائية والتأريض لمعدات التصوير',
        'توجيه واحتواء الكابلات بوعي للتداخل الكهرومغناطيسي والترددي',
        'تصميم وتركيب التكييف للبيئات السريرية المتحكم بها',
        'التنسيق مع فرق تركيب الشركة المصنّعة أثناء تشغيل المعدات',
        'مخططات التنفيذ والتوثيق وفق ما نُفّذ فعليًا',
      ],
      image: null,
      thumb: null,
    },
    {
      id: 'surfaces',
      num: '04',
      label: 'الأسطح والنجارة المقاومة للعدوى',
      shortLabel: 'الأسطح',
      tag: 'كوريان · أسطح سريرية · محطات تمريض · نجارة طبية',
      summary: 'تصنيع أسطح صلبة متصلة وغير مسامية، ونجارة طبية مصممة وفق بروتوكولات التنظيف والتحكم بالعدوى السريرية.',
      desc: 'كل ما يُلمس ويُنظّف ويُعقّم في البيئة السريرية يمر عبر ورشة الكوريان والنجارة الخاصة بشركة EGC. نصنّع أسطحًا صلبة متصلة الأجزاء لمنضدات العمل ومحطات التمريض والمغاسل، إضافة إلى ألواح جدارية مضادة للميكروبات وخزائن طبية — دون الفواصل والوصلات التي تحتجز التلوث، وبتشطيب يرقى إلى مستوى بروتوكولات التحكم بالعدوى.',
      capabilities: [
        'أسطح كوريان صلبة لمنضدات العمل والمغاسل السريرية',
        'محطات تمريض ومكاتب استقبال متصلة الأجزاء',
        'ألواح جدارية وكسوات مضادة للميكروبات',
        'خزائن طبية ونجارة تخزين سريرية',
        'تصنيع أسطح المختبرات ومحطات العمل',
        'مقاطع مخصصة مصممة وفق بروتوكولات التنظيف والتحكم بالعدوى',
      ],
      image: '/images/corian-surfaces.jpg',
      thumb: '/images/joinery-doors.jpg',
    },
  ],
};
