/* The four Healthcare Construction disciplines. Each entry powers the row
 * everywhere it is listed and its own landing page (ServicePage).
 * `id` equals the route key. */
export const SERVICES = {
  en: [
    {
      id: 'shielding',
      icon: 'shield',
      label: 'Radiation & magnetic shielding',
      full: 'Structural radiation & magnetic shielding',
      short: 'Shielding',
      summary: 'Lead lining for CT, PET-CT and X-ray rooms; RF and magnetic shielding for MRI suites — built to the OEM and physicist specification.',
      h1: 'Radiation and magnetic shielding contractor in Saudi Arabia',
      lead: 'We build the protective envelope around diagnostic and therapy rooms: lead lining for ionising radiation, and RF (Faraday cage) and magnetic shielding for MRI. Every layer is built to the OEM site-planning guide and the radiation protection physicist’s report.',
      image: 'hero-bg',
      imageAlt: 'EGC crew installing shielding panels in an MRI suite',
      rooms: ['MRI suites', 'CT rooms', 'PET-CT suites', 'X-ray and fluoroscopy rooms', 'Nuclear medicine rooms', 'Radiation therapy vaults'],
      deliver: [
        'MRI suites with RF (Faraday cage) and magnetic shielding',
        'Lead-lined walls, ceilings and floors for CT, PET-CT and X-ray rooms',
        'Nuclear medicine rooms and radiation therapy vaults',
        'Lead-glass viewing windows and RF windows',
        'Continuous-lining details at junctions, boxes and penetrations',
        'Retrofit shielding for existing diagnostic rooms',
      ],
      explainTitle: 'Two different problems, two different shields',
      explain: [
        'Radiation shielding contractors build the rooms that keep an imaging scanner’s energy where it belongs. In CT, PET-CT and X-ray rooms the hazard is ionising radiation, which is stopped by dense material, usually lead; a radiation protection physicist calculates how much each wall, floor, ceiling, door and window needs and records it in a shielding report. In an MRI suite the problem is different: the room is shielded from radio-frequency interference by a continuous conductive envelope, usually copper, aluminium or galvanised steel, and sometimes the magnet’s fringe field is contained with steel plate, as the manufacturer’s site-planning guide specifies. EGC builds both kinds of room from those two documents. We detail every junction, door, window and penetration on shop drawings before work starts, install the shielding with our own crews, and support the RF attenuation test or radiation survey before the room is released to the equipment manufacturer’s installation team.',
        'The weak points are always the same: [doors](healthcare-contractor/medical-doors), windows, junctions and every pipe, duct and cable that crosses the shield. That is why we coordinate shielding with the door and [healthcare MEP](healthcare-contractor/healthcare-mep) packages instead of treating it as a separate trade.',
      ],
      compare: {
        title: 'MRI and CT shielding compared',
        head: ['', 'MRI suite', 'CT, PET-CT and X-ray rooms'],
        rows: [
          ['What it controls', 'Radio-frequency interference getting in, and the magnet’s fringe field reaching outside', 'Ionising radiation (X-rays, or the 511 keV photons from PET tracers) escaping the room'],
          ['Typical material', 'A continuous conductive envelope of copper, aluminium or galvanised steel, plus steel plate where the manufacturer specifies it', 'Dense material, usually lead sheet or lead-lined board'],
          ['Who sets the amount', 'The manufacturer’s site-planning guide', 'The radiation protection physicist’s shielding report'],
          ['Usual weak points', 'Door, window, waveguides and filters, any unsealed seam', 'Door, viewing window, junctions, boxes and penetrations'],
          ['How it is checked', 'RF attenuation test', 'Radiation survey once the room is built'],
        ],
      },
      roles: {
        title: 'Who specifies what, and who builds it',
        head: ['Who', 'What they do'],
        rows: [
          ['Equipment manufacturer', 'Publishes the site-planning guide for the exact model: room size, RF and fringe-field limits, services and penetrations.'],
          ['Radiation protection physicist', 'Calculates the shielding each surface needs and issues the shielding report.'],
          ['Hospital design team and main contractor', 'Provide the structure, the layout and the programme the shielding has to fit into.'],
          ['EGC', 'Reads both documents together, builds and inspects the shielding, and supports RF and radiation testing before handover.'],
        ],
      },
      process: [
        { t: 'Review the specification', d: 'We read the OEM site-planning guide and the physicist’s shielding report side by side and resolve conflicts before drawings are issued.' },
        { t: 'Detail the envelope', d: 'Shop drawings show every lining layer, seam, junction and penetration, so nothing is improvised on site.' },
        { t: 'Build and inspect', d: 'Our own crews install the shielding, and continuity is checked before finishes close it in.' },
        { t: 'Test and hand over', d: 'We support the RF attenuation test or the radiation survey, then release the room to the OEM installation team.' },
      ],
    },
    {
      id: 'doors',
      icon: 'door',
      label: 'Medical doors & access',
      full: 'Medical doors & access systems',
      short: 'Doors',
      summary: 'Lead-lined and RF-shielded doors, hermetic sliding doors and access control — fabricated and fitted to seal controlled clinical areas.',
      h1: 'Lead-lined and RF-shielded medical doors in Saudi Arabia',
      lead: 'A shielded room is only as good as its doors. We fabricate and install lead-lined doors for CT, PET-CT and X-ray rooms, RF-shielded doors for MRI, and hermetic sliding doors for controlled areas — with interlocks and access control where the room calls for them.',
      image: 'healthcare-xray',
      imageAlt: 'Lead-lined X-ray room door with warning sign, installed by EGC',
      imagePosition: '85% 50%',
      rooms: ['MRI suites', 'CT and PET-CT rooms', 'X-ray and fluoroscopy rooms', 'Radiation therapy rooms', 'Controlled clinical areas'],
      deliver: [
        'Lead-lined radiation-shielded doors, manual and motorised',
        'RF-shielded doors integrated into the MRI Faraday cage',
        'Hermetic sliding doors for controlled clinical areas',
        'Access control and interlock integration for radiation rooms',
        'Leaf and frame fabrication to the OEM equipment specification',
        'Site installation, sealing and commissioning',
      ],
      explainTitle: 'Why doors are where shielding usually fails',
      explain: [
        'A medical shielding door is a door built to be part of the room’s shield. In CT, PET-CT, X-ray and radiation therapy rooms it is lead-lined, so the leaf and frame match the lead equivalence of the surrounding wall, with the leaf overlapping the wall lining so there is no gap where the lining stops. In an MRI suite it is an RF-shielded door that makes continuous electrical contact all the way around the leaf, keeping radio-frequency interference out of the scan room. Hermetic sliding doors serve controlled clinical areas where the opening has to be sealed. EGC fabricates leaves, frames and ironmongery in-house to the equipment specification, hangs and seals them with our own crews, and commissions closers, interlocks, warning signage and contacts before handover. Because a door performs only as well as its frame was set out when the wall was built, we coordinate it with the shielding package.',
        'A door is the one moving part in the envelope, which is why it is where [radiation and magnetic shielding](healthcare-contractor/radiation-shielding) most often fails. Wall and door packages are best coordinated by one contractor.',
      ],
      compare: {
        title: 'Door types compared',
        head: ['Door type', 'Used in', 'What it has to do', 'Detail that matters'],
        rows: [
          ['Lead-lined radiation door', 'CT, PET-CT, X-ray and radiation therapy rooms', 'Match the lead equivalence of the surrounding wall', 'The leaf overlaps the wall lining at the frame, so no gap is left where the lining stops'],
          ['RF-shielded door', 'MRI scan rooms', 'Keep radio-frequency interference out of the scan room', 'Continuous electrical contact all the way around the leaf'],
          ['Hermetic sliding door', 'Controlled clinical areas', 'Seal the opening for pressure and cleanliness control', 'Sealed leaf and track, with automatic operation where the room needs it'],
        ],
      },
      roles: {
        title: 'Who specifies what, and who builds it',
        head: ['Who', 'What they do'],
        rows: [
          ['Equipment manufacturer', 'Defines the opening, any RF-door requirement and the interlock or signal needs of the equipment.'],
          ['Radiation protection physicist', 'Specifies the lead equivalence the leaf and frame must match.'],
          ['Architect and main contractor', 'Set out the opening and carry the fire, access and ironmongery requirements.'],
          ['EGC', 'Fabricates the leaf and frame in-house, installs and seals them, and commissions closers, interlocks, signage and contacts.'],
        ],
      },
      process: [
        { t: 'Survey the opening', d: 'Frames are set out against the wall build-up so the lining and the door overlap exactly.' },
        { t: 'Fabricate in-house', d: 'Leaves, frames and ironmongery are made to the equipment specification, not adapted from catalogue doors.' },
        { t: 'Install and seal', d: 'Doors are hung, sealed and aligned by our own crews.' },
        { t: 'Adjust and commission', d: 'Closers, interlocks, signage and contacts are tested before handover.' },
      ],
    },
    {
      id: 'mep',
      icon: 'cable',
      label: 'Healthcare MEP',
      full: 'Specialized MEP',
      short: 'MEP',
      summary: 'Mechanical, electrical and plumbing works engineered for imaging equipment — medical gases, earthing, EMI-aware routing and controlled-environment HVAC.',
      h1: 'Healthcare MEP contractor for imaging and clinical rooms',
      lead: 'Imaging equipment has MEP demands that a standard scope does not cover: dedicated earthing, EMI-aware cable routes, medical gases, and HVAC that holds tight temperature and humidity limits. We deliver them in step with the shielding, so every penetration is planned once.',
      image: null,
      rooms: ['MRI suites', 'CT and PET-CT rooms', 'X-ray rooms', 'Controlled clinical environments'],
      deliver: [
        'Medical gas pipeline systems: oxygen, medical air and vacuum',
        'Electrical infrastructure and earthing for imaging equipment',
        'EMI/RFI-aware cable routing and containment',
        'HVAC design and installation for controlled clinical environments',
        'Coordination with OEM installation teams during commissioning',
        'MEP shop drawings and as-built documentation',
      ],
      explainTitle: 'Why MEP and shielding belong together',
      explain: [
        'Healthcare MEP for imaging rooms is mechanical, electrical and plumbing work engineered around the equipment and its shield. The equipment sets dedicated requirements: earthing, power, cooling and humidity limits, medical gas outlets and cable routes that avoid electromagnetic interference. The shield sets the rule for everything that crosses it: in an MRI suite pipes pass through waveguides, ducts through honeycomb waveguide vents and electrical cables through RF filters, while in a lead-lined room each crossing needs a lead-backed sleeve or box. EGC plans every penetration on the drawings before anything is cut, in step with the shielding, then installs, pressure-tests and balances the services to the specified conditions and hands over as-built drawings and test records with the room. Doing both under one contractor means the details that normally fall between packages are drawn once instead of being found on site.',
        'When [shielding](healthcare-contractor/radiation-shielding) and MEP are separate packages, those crossings are discovered late and fixed on site. Under one contractor they are drawn once, before anything is cut.',
      ],
      compare: {
        title: 'What crosses the shield, and how',
        head: ['Service', 'In an MRI suite', 'In a lead-lined room'],
        rows: [
          ['Pipes (medical gases, water)', 'Pass through a waveguide in the RF shield', 'Pass through a lead-backed sleeve'],
          ['Air ducts', 'Pass through a honeycomb waveguide vent in the RF shield', 'Cross through a lead-lined section or baffle'],
          ['Power and data cables', 'Enter through RF filters, routed to the manufacturer’s requirements', 'Run in lead-backed boxes and containment'],
          ['Earthing', 'Dedicated earthing as the manufacturer specifies', 'Earthing to the equipment specification'],
        ],
      },
      roles: {
        title: 'Who specifies what, and who builds it',
        head: ['Who', 'What they do'],
        rows: [
          ['Equipment manufacturer', 'States the heat load, power, cooling, humidity, gas and earthing the equipment needs.'],
          ['Building services designer', 'Designs the building services and plant that serve the room.'],
          ['Shielding specification', 'Defines where and how services may cross the shield.'],
          ['EGC', 'Plans every penetration with the shielding, installs, pressure-tests and balances the services, and hands over as-built drawings and test records.'],
        ],
      },
      process: [
        { t: 'Agree loads and routes', d: 'We take heat loads, power and service requirements from the OEM and agree routes with the design team.' },
        { t: 'Plan every penetration', d: 'Each crossing of the shielded envelope is located, detailed and sealed on the drawings first.' },
        { t: 'Install and test', d: 'Services are installed, pressure-tested and balanced to the specified conditions.' },
        { t: 'Document', d: 'As-built drawings and test records are handed over with the room.' },
      ],
    },
    {
      id: 'surfaces',
      icon: 'layers',
      label: 'Infection-control surfaces & joinery',
      full: 'Infection controlled surfaces & joinery',
      short: 'Surfaces',
      summary: 'Seamless, non-porous Corian solid surfaces and medical-grade joinery from our own factory, made for clinical cleaning protocols.',
      h1: 'Infection-control surfaces and Corian joinery for hospitals',
      lead: 'Everything that is touched, cleaned and disinfected in a clinical space comes out of our own Corian and joinery factory in Jeddah: seamless solid-surface counters, nurse stations, scrub sinks and medical-grade cabinetry.',
      image: 'corian-surfaces',
      imageAlt: 'Seamless Corian nurse station with integrated sink',
      rooms: ['Nurse stations and reception counters', 'Scrub and hand-wash sinks', 'Laboratory benches', 'Clinical cabinetry and storage', 'Wall cladding and panelling'],
      deliver: [
        'Corian and solid-surface clinical counters and vanities',
        'Seamless nurse stations and reception counters',
        'Antimicrobial wall panelling and cladding',
        'Medical-grade cabinetry and clinical storage joinery',
        'Laboratory and workstation surface fabrication',
        'Custom profiles engineered for infection-control cleaning protocols',
      ],
      explainTitle: 'Seamless is the point',
      explain: [
        'Infection-control surfaces are the counters, nurse stations, sinks, cabinetry and wall finishes that are touched and cleaned all day in a clinical space. What makes a surface suitable is that it is non-porous, so contamination cannot soak in, and seamless, so there are no joints or cracks for it to hide in. Solid surface such as Corian meets both: seams are bonded and sanded flush, and counters, upstands and integrated sinks read as one piece that can be wiped down end to end. EGC makes these pieces in its own Wood & Corian factory in Jeddah: we template the finished room, cut and thermoform the parts in the workshop, then install, join and polish them on site with the same team. Fabricating in-house means there is no gap between a supplier’s drawing and the wall, and the surfaces are made to fit the room as it was actually built.',
        'Because [our Wood & Corian factory](manufacturing) makes every piece, counters and cabinetry are templated to the room, fabricated to tolerance and installed by the same team.',
      ],
      compare: {
        title: 'What makes a surface suitable for clinical cleaning',
        head: ['Property', 'Why it matters', 'How solid surface delivers it'],
        rows: [
          ['Non-porous', 'Contamination cannot soak into the material', 'Solid surface is non-porous all the way through'],
          ['Seamless joints', 'Joints and cracks give contamination somewhere to hide', 'Seams are bonded and sanded flush, so the surface reads as one piece'],
          ['Integrated sinks and upstands', 'Fewer edges and junctions to clean around', 'Sinks, splashbacks and upstands are formed as part of the counter'],
          ['Repairable', 'Clinical surfaces are used hard every day', 'Surface damage can be sanded out, rather than the piece being replaced'],
        ],
      },
      roles: {
        title: 'Who specifies what, and who builds it',
        head: ['Who', 'What they do'],
        rows: [
          ['Architect and interior designer', 'Specify the layout, profiles and finishes.'],
          ['Hospital infection prevention team', 'Sets the cleaning and disinfection protocols the surfaces have to withstand.'],
          ['Main contractor', 'Provides the programme and access to the finished room for templating.'],
          ['EGC', 'Templates the room, fabricates in our own factory, then installs, joins and finishes the surfaces.'],
        ],
      },
      process: [
        { t: 'Template on site', d: 'We measure the finished room so every piece fits the wall as built.' },
        { t: 'Fabricate in the factory', d: 'CNC cutting, thermoforming and seaming in our Jeddah Corian and joinery workshop.' },
        { t: 'Install and join', d: 'Pieces are fixed, seams bonded and sinks integrated on site.' },
        { t: 'Polish and hand over', d: 'Surfaces are finished to the specified sheen and cleaned for use.' },
      ],
    },
  ],
  ar: [
    {
      id: 'shielding',
      icon: 'shield',
      label: 'التدريع الإشعاعي والمغناطيسي',
      full: 'التدريع الإنشائي للإشعاع والمجال المغناطيسي',
      short: 'التدريع',
      summary: 'تبطين بالرصاص لغرف الأشعة المقطعية وPET-CT والأشعة السينية، وتدريع ضد الترددات الراديوية والمجال المغناطيسي لغرف الرنين — وفق مواصفات الشركة المصنِّعة والفيزيائي الإشعاعي.',
      h1: 'مقاول تدريع إشعاعي ومغناطيسي لغرف الرنين والأشعة في السعودية',
      lead: 'نبني الغلاف الواقي لغرف التشخيص والعلاج: تبطين بالرصاص ضد الإشعاع المؤيِّن، وتدريع ضد الترددات الراديوية (قفص فاراداي) والمجال المغناطيسي لغرف الرنين. كل طبقة تُنفَّذ وفق دليل تخطيط الموقع الصادر عن الشركة المصنِّعة وتقرير الفيزيائي المختص بالوقاية الإشعاعية.',
      image: 'hero-bg',
      imageAlt: 'فريق EGC أثناء تركيب ألواح التدريع في غرفة رنين مغناطيسي',
      rooms: ['غرف الرنين المغناطيسي', 'غرف الأشعة المقطعية', 'غرف PET-CT', 'غرف الأشعة السينية والتنظير الفلوري', 'غرف الطب النووي', 'غرف العلاج الإشعاعي'],
      deliver: [
        'غرف رنين مغناطيسي بتدريع ضد الترددات الراديوية (قفص فاراداي) والمجال المغناطيسي',
        'جدران وأسقف وأرضيات مبطنة بالرصاص لغرف الأشعة المقطعية وPET-CT والأشعة السينية',
        'غرف الطب النووي وغرف العلاج الإشعاعي',
        'نوافذ مراقبة من الزجاج الرصاصي ونوافذ مدرّعة ضد الترددات الراديوية',
        'تفاصيل تبطين متصل عند التقاطعات والصناديق ونقاط الاختراق',
        'تدريع تحديثي للغرف التشخيصية القائمة',
      ],
      explainTitle: 'مشكلتان مختلفتان، وتدريعان مختلفان',
      explain: [
        'يبني مقاول التدريع الإشعاعي الغرف التي تُبقي طاقة جهاز التصوير داخل حدودها. ففي غرف الأشعة المقطعية وPET-CT والأشعة السينية يكون الخطر هو الإشعاع المؤيِّن، وتوقفه المواد الكثيفة وأشهرها الرصاص، ويحسب الفيزيائي المختص بالوقاية الإشعاعية ما يحتاجه كل جدار وأرضية وسقف وباب ونافذة ويدوّنه في تقرير التدريع. أما غرفة الرنين المغناطيسي فمشكلتها مختلفة: تُحمى الغرفة من تداخل الترددات الراديوية بغلاف موصل متصل، عادةً من النحاس أو الألومنيوم أو الصلب المجلفن، وقد يُحتوى المجال المغناطيسي المتسرب حول المغناطيس بألواح من الصلب وفق دليل تخطيط الموقع الصادر عن الشركة المصنِّعة. وتبني EGC النوعين من الغرف اعتمادًا على هاتين الوثيقتين: نفصّل كل وصلة وباب ونافذة واختراق في المخططات التنفيذية قبل بدء العمل، وتركّب كوادرنا التدريع بنفسها، وندعم اختبار توهين الترددات الراديوية أو المسح الإشعاعي قبل تسليم الغرفة لفريق تركيب الشركة المصنِّعة للجهاز.',
        'ونقاط الضعف هي نفسها دائمًا: [الأبواب](healthcare-contractor/medical-doors) والنوافذ والوصلات وكل أنبوب ومجرى وكابل يخترق الدرع. ولذلك ننسّق التدريع مع حزمتي الأبواب و[الأعمال الكهروميكانيكية الطبية](healthcare-contractor/healthcare-mep) بدلًا من التعامل معه كأعمال منفصلة.',
      ],
      compare: {
        title: 'مقارنة بين تدريع الرنين وتدريع الأشعة المقطعية',
        head: ['', 'غرفة الرنين المغناطيسي', 'غرف الأشعة المقطعية وPET-CT والأشعة السينية'],
        rows: [
          ['ما الذي يضبطه', 'منع تداخل الترددات الراديوية من الدخول، واحتواء المجال المغناطيسي المتسرب حول المغناطيس', 'منع الإشعاع المؤيِّن (الأشعة السينية أو فوتونات 511 كيلو إلكترون فولت الصادرة عن مواد PET) من الخروج من الغرفة'],
          ['المادة المعتادة', 'غلاف موصل متصل من النحاس أو الألومنيوم أو الصلب المجلفن، مع ألواح صلب عند اشتراط الشركة المصنِّعة', 'مادة كثيفة، وغالبًا صفائح أو ألواح مبطنة بالرصاص'],
          ['من يحدد المقدار', 'دليل تخطيط الموقع الصادر عن الشركة المصنِّعة', 'تقرير التدريع الصادر عن الفيزيائي المختص بالوقاية الإشعاعية'],
          ['نقاط الضعف المعتادة', 'الباب والنافذة والموجّهات الموجية والمرشحات وأي وصلة غير محكمة', 'الباب ونافذة المراقبة والوصلات والصناديق والاختراقات'],
          ['طريقة التحقق', 'اختبار توهين الترددات الراديوية', 'مسح إشعاعي بعد اكتمال الغرفة'],
        ],
      },
      roles: {
        title: 'من يحدد ماذا، ومن ينفذ',
        head: ['الجهة', 'دورها'],
        rows: [
          ['الشركة المصنِّعة للجهاز', 'تصدر دليل تخطيط الموقع للطراز المحدد: مقاس الغرفة وحدود الترددات الراديوية والمجال المتسرب والخدمات والاختراقات.'],
          ['الفيزيائي المختص بالوقاية الإشعاعية', 'يحسب التدريع المطلوب لكل سطح ويصدر تقرير التدريع.'],
          ['فريق التصميم والمقاول الرئيسي', 'يوفران الهيكل والمخطط والبرنامج الزمني الذي يجب أن يتوافق معه التدريع.'],
          ['EGC', 'تقرأ الوثيقتين معًا، وتنفذ التدريع وتفحصه، وتدعم اختبارات الترددات الراديوية والإشعاع قبل التسليم.'],
        ],
      },
      process: [
        { t: 'مراجعة المواصفات', d: 'نقرأ دليل تخطيط الموقع وتقرير التدريع من الفيزيائي جنبًا إلى جنب، ونحسم أي تعارض قبل إصدار المخططات.' },
        { t: 'تفصيل الغلاف الواقي', d: 'تُظهر مخططات التنفيذ كل طبقة تبطين وكل وصلة وتقاطع ونقطة اختراق، فلا يُرتجل شيء في الموقع.' },
        { t: 'التنفيذ والفحص', d: 'تركّب فرقنا التدريع بنفسها، ويُفحص اتصال الطبقات قبل أن تغطيه التشطيبات.' },
        { t: 'الاختبار والتسليم', d: 'ندعم اختبار توهين الترددات الراديوية أو المسح الإشعاعي، ثم نسلّم الغرفة لفريق التركيب التابع للشركة المصنِّعة.' },
      ],
    },
    {
      id: 'doors',
      icon: 'door',
      label: 'الأبواب الطبية والتحكم بالدخول',
      full: 'الأبواب الطبية وأنظمة التحكم بالدخول',
      short: 'الأبواب',
      summary: 'أبواب مبطنة بالرصاص وأخرى مدرّعة ضد الترددات الراديوية، وأبواب انزلاقية محكمة الغلق، وأنظمة تحكم بالدخول — تُصنَّع وتُركَّب لعزل المناطق السريرية المتحكَّم بها.',
      h1: 'أبواب طبية مبطنة بالرصاص ومدرّعة ضد الترددات الراديوية في السعودية',
      lead: 'فعالية الغرفة المدرّعة تتوقف على أبوابها. نصنّع ونركّب أبوابًا مبطنة بالرصاص لغرف الأشعة المقطعية وPET-CT والأشعة السينية، وأبوابًا مدرّعة ضد الترددات الراديوية لغرف الرنين المغناطيسي، وأبوابًا انزلاقية محكمة الغلق للمناطق المتحكَّم بها — مع أنظمة قفل تبادلي وتحكم بالدخول عند الحاجة.',
      image: 'healthcare-xray',
      imageAlt: 'باب غرفة أشعة مبطن بالرصاص مع لوحة تحذير، من تنفيذ EGC',
      imagePosition: '85% 50%',
      rooms: ['غرف الرنين المغناطيسي', 'غرف الأشعة المقطعية وPET-CT', 'غرف الأشعة السينية والتنظير الفلوري', 'غرف العلاج الإشعاعي', 'المناطق السريرية المتحكَّم بها'],
      deliver: [
        'أبواب مبطنة بالرصاص للتدريع الإشعاعي، يدوية ومؤتمتة',
        'أبواب مدرّعة ضد الترددات الراديوية مدمجة في قفص فاراداي لغرفة الرنين',
        'أبواب انزلاقية محكمة الغلق للمناطق السريرية المتحكَّم بها',
        'دمج أنظمة التحكم بالدخول والقفل التبادلي لغرف الإشعاع',
        'تصنيع الضلفة والإطار وفق مواصفات معدات الشركة المصنِّعة',
        'التركيب الميداني والإحكام والتشغيل',
      ],
      explainTitle: 'لماذا تُعدّ الأبواب أضعف نقطة في التدريع عادةً',
      explain: [
        'الباب الطبي المدرّع هو باب مصنوع ليكون جزءًا من درع الغرفة. ففي غرف الأشعة المقطعية وPET-CT والأشعة السينية والعلاج الإشعاعي يكون مبطنًا بالرصاص، فيطابق الباب، ضلفةً وإطارًا، ما في الجدار المحيط من رصاص مكافئ، وتتداخل الضلفة مع تبطين الجدار فلا تبقى فجوة حيث ينتهي التبطين. وفي غرفة الرنين المغناطيسي يكون الباب مدرّعًا ضد الترددات الراديوية ويصنع تلامسًا كهربائيًا متصلًا حول الضلفة بالكامل، فيمنع تداخل الترددات الراديوية من دخول غرفة الفحص. وتخدم الأبواب الانزلاقية محكمة الغلق المناطق السريرية المتحكَّم بها التي يجب إحكام فتحتها. وتصنّع EGC الضلف والإطارات والإكسسوارات في مصنعها وفق مواصفات الجهاز، وتركّبها وتحكم عزلها بكوادرها، وتختبر المغلقات والأقفال التبادلية ولوحات التحذير والتلامسات قبل التسليم. ولأن أداء الباب مرهون بدقة تحديد مكان إطاره عند بناء الجدار، ننسّقه مع حزمة التدريع.',
        'والباب هو الجزء المتحرك الوحيد في الغلاف، ولهذا هو أكثر مواضع [التدريع الإشعاعي والمغناطيسي](healthcare-contractor/radiation-shielding) تعرضًا للقصور. وتُنسَّق حزمتا الجدار والباب على أفضل وجه عبر مقاول واحد.',
      ],
      compare: {
        title: 'مقارنة بين أنواع الأبواب',
        head: ['نوع الباب', 'مكان استخدامه', 'وظيفته', 'التفصيل الحاسم'],
        rows: [
          ['باب إشعاعي مبطن بالرصاص', 'غرف الأشعة المقطعية وPET-CT والأشعة السينية والعلاج الإشعاعي', 'مطابقة ما في الجدار المحيط من رصاص مكافئ', 'تتداخل الضلفة مع تبطين الجدار عند الإطار فلا تبقى فجوة حيث ينتهي التبطين'],
          ['باب مدرّع ضد الترددات الراديوية', 'غرف فحص الرنين المغناطيسي', 'منع تداخل الترددات الراديوية من دخول غرفة الفحص', 'تلامس كهربائي متصل حول الضلفة بالكامل'],
          ['باب انزلاقي محكم الغلق', 'المناطق السريرية المتحكَّم بها', 'إحكام الفتحة للتحكم بالضغط والنظافة', 'ضلفة ومسار محكمان، مع تشغيل آلي حيث تتطلب الغرفة ذلك'],
        ],
      },
      roles: {
        title: 'من يحدد ماذا، ومن ينفذ',
        head: ['الجهة', 'دورها'],
        rows: [
          ['الشركة المصنِّعة للجهاز', 'تحدد الفتحة وأي اشتراط لباب مدرّع ضد الترددات الراديوية واحتياجات القفل التبادلي والإشارات للجهاز.'],
          ['الفيزيائي المختص بالوقاية الإشعاعية', 'يحدد الرصاص المكافئ الذي يجب أن تطابقه الضلفة والإطار.'],
          ['المعماري والمقاول الرئيسي', 'يحددان موقع الفتحة ويحملان متطلبات الحريق والدخول والإكسسوارات.'],
          ['EGC', 'تصنّع الضلفة والإطار في مصنعها، وتركّبهما وتحكم عزلهما، وتشغّل المغلقات والأقفال التبادلية ولوحات التحذير والتلامسات.'],
        ],
      },
      process: [
        { t: 'مسح الفتحة', d: 'تُضبط الأطر وفق تركيب الجدار ليتطابق التبطين مع الباب بدقة.' },
        { t: 'التصنيع داخليًا', d: 'تُصنَّع الضلف والأطر والإكسسوارات وفق مواصفات الجهاز، لا تعديلًا على أبواب جاهزة.' },
        { t: 'التركيب والإحكام', d: 'تعلّق فرقنا الأبواب وتحكم عزلها وتضبط محاذاتها.' },
        { t: 'الضبط والتشغيل', d: 'تُختبر المغاليق والقفل التبادلي واللوحات الإرشادية وملامسات التوصيل قبل التسليم.' },
      ],
    },
    {
      id: 'mep',
      icon: 'cable',
      label: 'الأعمال الكهروميكانيكية الطبية',
      full: 'الأعمال الكهروميكانيكية المتخصصة',
      short: 'الكهروميكانيكية',
      summary: 'أعمال ميكانيكية وكهربائية وسباكة مصممة لمعدات التصوير — غازات طبية وتأريض وتمديدات واعية بالتداخل الكهرومغناطيسي وتكييف للبيئات المتحكَّم بها.',
      h1: 'مقاول أعمال كهروميكانيكية للمنشآت الصحية وغرف التصوير',
      lead: 'لمعدات التصوير متطلبات كهروميكانيكية لا يغطيها النطاق المعتاد: تأريض مخصص، ومسارات كابلات واعية بالتداخل الكهرومغناطيسي، وغازات طبية، وتكييف يحافظ على حدود دقيقة للحرارة والرطوبة. ننفذها بالتوازي مع التدريع، فتُخطَّط كل نقطة اختراق مرة واحدة.',
      image: null,
      rooms: ['غرف الرنين المغناطيسي', 'غرف الأشعة المقطعية وPET-CT', 'غرف الأشعة السينية', 'البيئات السريرية المتحكَّم بها'],
      deliver: [
        'أنظمة خطوط الغازات الطبية: الأكسجين والهواء الطبي والشفط',
        'البنية الكهربائية والتأريض لمعدات التصوير',
        'تمديد واحتواء الكابلات بوعي للتداخل الكهرومغناطيسي والترددي',
        'تصميم وتركيب التكييف للبيئات السريرية المتحكَّم بها',
        'التنسيق مع فرق تركيب الشركة المصنِّعة أثناء التشغيل',
        'مخططات التنفيذ ومخططات ما بعد التنفيذ',
      ],
      explainTitle: 'لماذا يجب أن تعمل الأعمال الكهروميكانيكية والتدريع معًا',
      explain: [
        'الأعمال الكهروميكانيكية الطبية لغرف التصوير هي أعمال ميكانيكية وكهربائية وسباكة مصممة حول الجهاز ودرعه. فالجهاز يفرض متطلبات خاصة: تأريضًا وطاقة وحدودًا لدرجة الحرارة والرطوبة ومخارج غازات طبية ومسارات كابلات تتجنب التداخل الكهرومغناطيسي. والدرع يفرض قاعدة على كل ما يخترقه: ففي غرفة الرنين المغناطيسي تمر الأنابيب عبر موجّهات موجية والمجاري عبر فتحات تهوية بموجّهات موجية على شكل خلية نحل والكابلات الكهربائية عبر مرشحات للترددات الراديوية، وفي الغرفة المبطنة بالرصاص يحتاج كل اختراق إلى غلاف أو صندوق مبطن بالرصاص. وتخطط EGC كل اختراق على المخططات قبل أي قص، بالتنسيق مع التدريع، ثم تركّب الخدمات وتختبر ضغطها وتوازنها وفق الظروف المحددة، وتسلّم مخططات ما بعد التنفيذ وسجلات الاختبار مع الغرفة. وتنفيذ الأمرين عبر مقاول واحد يعني أن التفاصيل التي تقع عادةً بين الحزم تُرسم مرة واحدة بدل اكتشافها في الموقع.',
        'وحين تكون أعمال [التدريع](healthcare-contractor/radiation-shielding) والأعمال الكهروميكانيكية حزمتين منفصلتين تُكتشف هذه الاختراقات متأخرًا وتُعالَج في الموقع. أما مع مقاول واحد فتُرسم مرة واحدة قبل أي قص.',
      ],
      compare: {
        title: 'ما الذي يخترق الدرع وكيف',
        head: ['الخدمة', 'في غرفة الرنين المغناطيسي', 'في الغرفة المبطنة بالرصاص'],
        rows: [
          ['الأنابيب (الغازات الطبية والمياه)', 'تمر عبر موجّه موجي في درع الترددات الراديوية', 'تمر عبر غلاف مبطن بالرصاص'],
          ['مجاري الهواء', 'تمر عبر فتحة تهوية بموجّهات موجية على شكل خلية نحل في درع الترددات الراديوية', 'تعبر عبر قطعة أو حاجز مبطن بالرصاص'],
          ['كابلات الطاقة والبيانات', 'تدخل عبر مرشحات للترددات الراديوية وفق متطلبات الشركة المصنِّعة', 'تمر في صناديق ومجاري مبطنة بالرصاص'],
          ['التأريض', 'تأريض مخصص وفق ما تحدده الشركة المصنِّعة', 'تأريض وفق مواصفات الجهاز'],
        ],
      },
      roles: {
        title: 'من يحدد ماذا، ومن ينفذ',
        head: ['الجهة', 'دورها'],
        rows: [
          ['الشركة المصنِّعة للجهاز', 'تحدد الحمل الحراري والطاقة والتبريد والرطوبة والغازات والتأريض التي يحتاجها الجهاز.'],
          ['مصمم الخدمات الهندسية للمبنى', 'يصمم الخدمات والمحطات التي تخدم الغرفة.'],
          ['مواصفات التدريع', 'تحدد أين وكيف يجوز للخدمات أن تخترق الدرع.'],
          ['EGC', 'تخطط كل اختراق مع التدريع، وتركّب الخدمات وتختبر ضغطها وتوازنها، وتسلّم مخططات ما بعد التنفيذ وسجلات الاختبار.'],
        ],
      },
      process: [
        { t: 'الاتفاق على الأحمال والمسارات', d: 'نأخذ الأحمال الحرارية ومتطلبات الطاقة والخدمات من الشركة المصنِّعة ونتفق على المسارات مع فريق التصميم.' },
        { t: 'تخطيط كل نقطة اختراق', d: 'تُحدَّد كل نقطة عبور للغلاف المدرّع وتُفصَّل وتُحكَم على المخططات أولًا.' },
        { t: 'التركيب والاختبار', d: 'تُركَّب الخدمات وتُختبر ضغطيًا وتُوازَن وفق الظروف المحددة.' },
        { t: 'التوثيق', d: 'تُسلَّم مخططات ما بعد التنفيذ وسجلات الاختبار مع الغرفة.' },
      ],
    },
    {
      id: 'surfaces',
      icon: 'layers',
      label: 'الأسطح والنجارة المقاومة للعدوى',
      full: 'الأسطح والنجارة المقاومة للعدوى',
      short: 'الأسطح',
      summary: 'أسطح كوريان صلبة متصلة وغير مسامية ونجارة طبية من مصنعنا، مصممة وفق بروتوكولات التنظيف السريري.',
      h1: 'أسطح كوريان ونجارة طبية مقاومة للعدوى للمستشفيات في السعودية',
      lead: 'كل ما يُلمس ويُنظَّف ويُعقَّم في المساحات السريرية يخرج من مصنع الكوريان والنجارة الخاص بنا في جدة: منضدات أسطح صلبة متصلة، ومحطات تمريض، ومغاسل جراحية، وخزائن طبية.',
      image: 'corian-surfaces',
      imageAlt: 'محطة تمريض من الكوريان بوصلات غير مرئية ومغسلة مدمجة',
      rooms: ['محطات التمريض ومكاتب الاستقبال', 'مغاسل الجراحة وغسل اليدين', 'طاولات المختبرات', 'الخزائن والتخزين السريري', 'كسوة الجدران والألواح'],
      deliver: [
        'منضدات ومغاسل سريرية من الكوريان والأسطح الصلبة',
        'محطات تمريض ومكاتب استقبال متصلة بلا فواصل',
        'ألواح وكسوات جدارية مضادة للميكروبات',
        'خزائن طبية ونجارة تخزين سريرية',
        'تصنيع أسطح المختبرات ومحطات العمل',
        'مقاطع مخصصة مصممة وفق بروتوكولات التنظيف ومكافحة العدوى',
      ],
      explainTitle: 'الاتصال بلا فواصل هو الهدف',
      explain: [
        'الأسطح المقاومة للعدوى هي المنضدات ومحطات التمريض والأحواض والخزائن وتشطيبات الجدران التي تُلمس وتُنظَّف طوال اليوم في الحيّز السريري. وما يجعل السطح مناسبًا هو أن يكون غير مسامي فلا تتغلغل فيه الملوثات، ومتصلًا بلا فواصل فلا تجد مكانًا تختبئ فيه. والأسطح الصلبة مثل الكوريان تحقق الأمرين: تُلصق الوصلات وتُصقل لتصبح مستوية تمامًا، فتبدو المنضدات والحواف والأحواض المدمجة قطعة واحدة يمكن مسحها من طرفها إلى طرفها. وتصنع EGC هذه القطع في مصنع الخشب والكوريان التابع لها في جدة: نأخذ مقاسات الغرفة بعد اكتمالها، ونقص الأجزاء ونشكّلها حراريًا في الورشة، ثم نركّبها ونصل وصلاتها ونصقلها في الموقع بالفريق نفسه. والتصنيع داخل مصنعنا يعني ألا فجوة بين مخطط المورّد والجدار، وأن الأسطح تُصنع لتناسب الغرفة كما بُنيت فعلًا.',
        'ولأن [مصنعنا للخشب والكوريان](manufacturing) يصنع كل قطعة، تُؤخذ مقاسات المنضدات والخزائن من الغرفة نفسها وتُصنَّع بدقة وتُركَّب بالفريق نفسه.',
      ],
      compare: {
        title: 'ما الذي يجعل السطح مناسبًا للتنظيف السريري',
        head: ['الخاصية', 'لماذا تهم', 'كيف يحققها السطح الصلب'],
        rows: [
          ['غير مسامي', 'لا تتغلغل الملوثات في المادة', 'السطح الصلب غير مسامي في كامل سماكته'],
          ['وصلات متصلة', 'الوصلات والشقوق تمنح الملوثات مكانًا للاختباء', 'تُلصق الوصلات وتُصقل لتستوي، فيبدو السطح قطعة واحدة'],
          ['أحواض وحواف مدمجة', 'حواف وتقاطعات أقل يجب التنظيف حولها', 'تُشكَّل الأحواض والحواف الخلفية والرافعة ضمن المنضدة نفسها'],
          ['قابل للإصلاح', 'تُستخدم الأسطح السريرية بقوة كل يوم', 'يمكن صقل التلف السطحي بدل استبدال القطعة'],
        ],
      },
      roles: {
        title: 'من يحدد ماذا، ومن ينفذ',
        head: ['الجهة', 'دورها'],
        rows: [
          ['المعماري ومصمم الديكور الداخلي', 'يحددان التخطيط والمقاطع والتشطيبات.'],
          ['فريق مكافحة العدوى في المستشفى', 'يحدد بروتوكولات التنظيف والتطهير التي يجب أن تتحملها الأسطح.'],
          ['المقاول الرئيسي', 'يوفر البرنامج الزمني ودخول الغرفة المنجزة لأخذ المقاسات.'],
          ['EGC', 'تأخذ مقاسات الغرفة، وتصنّع في مصنعها، ثم تركّب وتصل وتشطّب الأسطح.'],
        ],
      },
      process: [
        { t: 'أخذ المقاسات في الموقع', d: 'نقيس الغرفة بعد اكتمالها لتناسب كل قطعة الجدار كما نُفِّذ.' },
        { t: 'التصنيع في المصنع', d: 'قطع بتقنية CNC وتشكيل حراري ولحام وصلات في ورشة الكوريان والنجارة بجدة.' },
        { t: 'التركيب والوصل', d: 'تُثبَّت القطع وتُلصق الوصلات وتُدمج المغاسل في الموقع.' },
        { t: 'التلميع والتسليم', d: 'تُشطَّب الأسطح بدرجة اللمعان المحددة وتُنظَّف للاستخدام.' },
      ],
    },
  ],
};
