/* The four Healthcare Construction disciplines. Each entry powers three things:
 * the card/row everywhere it is listed, its own landing page (ServicePage),
 * and its FAQPage structured data (via content/faq.js). `id` equals the route key. */
export const SERVICES = {
  en: [
    {
      id: 'shielding',
      icon: 'shield',
      label: 'Radiation & magnetic shielding',
      full: 'Structural radiation & magnetic shielding',
      short: 'Shielding',
      summary: 'Lead lining for CT, PET-CT and X-ray rooms; RF and magnetic shielding for MRI suites — built to the OEM and physicist specification.',
      h1: 'Radiation and magnetic shielding contractor in Saudi Arabia',
      lead: 'We build the protective envelope around diagnostic and therapy rooms: lead lining for ionising radiation, and RF (Faraday cage) and magnetic shielding for MRI. Every layer is built to the OEM site-planning guide and the radiation protection physicist’s report.',
      image: 'hero-bg',
      imageAlt: 'EGC crew installing shielding panels in an MRI suite',
      rooms: ['MRI suites', 'CT rooms', 'PET-CT suites', 'X-ray and fluoroscopy rooms', 'Nuclear medicine rooms', 'Radiation therapy vaults'],
      deliver: [
        'MRI suites with RF (Faraday cage) and magnetic shielding',
        'Lead-lined walls, ceilings and floors for CT, PET-CT and X-ray rooms',
        'Nuclear medicine rooms and radiation therapy vaults',
        'Lead-glass viewing windows and RF windows',
        'Continuous-lining details at junctions, boxes and penetrations',
        'Retrofit shielding for existing diagnostic rooms',
      ],
      explainTitle: 'Two different problems, two different shields',
      explain: [
        'Ionising radiation — from CT, PET-CT and X-ray equipment — is stopped by dense material, usually lead. How much is needed is calculated by a radiation protection physicist for each wall, floor, ceiling, door and window.',
        'MRI uses no ionising radiation. Its room is shielded against radio-frequency interference by a continuous conductive envelope, and sometimes against the magnet’s fringe field with steel. The OEM’s site-planning guide defines both.',
      ],
      process: [
        { t: 'Review the specification', d: 'We read the OEM site-planning guide and the physicist’s shielding report side by side and resolve conflicts before drawings are issued.' },
        { t: 'Detail the envelope', d: 'Shop drawings show every lining layer, seam, junction and penetration, so nothing is improvised on site.' },
        { t: 'Build and inspect', d: 'Our own crews install the shielding, and continuity is checked before finishes close it in.' },
        { t: 'Test and hand over', d: 'We support the RF attenuation test or the radiation survey, then release the room to the OEM installation team.' },
      ],
      faqs: [
        { q: 'Does an MRI room need lead?', a: 'Not for the magnet itself — MRI uses no ionising radiation. An MRI room needs RF shielding to keep outside interference out of the image, and sometimes magnetic shielding. Lead may still be specified where the room borders an X-ray or CT room.' },
        { q: 'Who decides how thick the lead lining must be?', a: 'A qualified radiation protection physicist, based on the equipment’s workload, how the surrounding spaces are occupied and their distance from the source. The contractor builds exactly to the resulting shielding report.' },
        { q: 'Can you add shielding to an existing room?', a: 'Yes, subject to the structure and the physicist’s review. Retrofit shielding is common when a department is upgraded to a new scanner.' },
      ],
    },
    {
      id: 'doors',
      icon: 'door',
      label: 'Medical doors & access',
      full: 'Medical doors & access systems',
      short: 'Doors',
      summary: 'Lead-lined and RF-shielded doors, hermetic sliding doors and access control — fabricated and fitted to seal controlled clinical areas.',
      h1: 'Lead-lined and RF-shielded medical doors in Saudi Arabia',
      lead: 'A shielded room is only as good as its doors. We fabricate and install lead-lined doors for CT, PET-CT and X-ray rooms, RF-shielded doors for MRI, and hermetic sliding doors for controlled areas — with interlocks and access control where the room calls for them.',
      image: 'healthcare-xray',
      imageAlt: 'Lead-lined X-ray room door with warning sign, installed by EGC',
      imagePosition: '85% 50%',
      rooms: ['MRI suites', 'CT and PET-CT rooms', 'X-ray and fluoroscopy rooms', 'Radiation therapy rooms', 'Controlled clinical areas'],
      deliver: [
        'Lead-lined radiation-shielded doors, manual and motorised',
        'RF-shielded doors integrated into the MRI Faraday cage',
        'Hermetic sliding doors for controlled clinical areas',
        'Access control and interlock integration for radiation rooms',
        'Leaf and frame fabrication to the OEM equipment specification',
        'Site installation, sealing and commissioning',
      ],
      explainTitle: 'Why doors are where shielding usually fails',
      explain: [
        'A door is the one moving part in the envelope. A lead-lined leaf must overlap the wall lining at the frame; an RF door must make continuous electrical contact all the way round.',
        'Both depend on the frame being set out correctly when the wall is built, which is why the door and wall packages are best coordinated by one contractor.',
      ],
      process: [
        { t: 'Survey the opening', d: 'Frames are set out against the wall build-up so the lining and the door overlap exactly.' },
        { t: 'Fabricate in-house', d: 'Leaves, frames and ironmongery are made to the equipment specification, not adapted from catalogue doors.' },
        { t: 'Install and seal', d: 'Doors are hung, sealed and aligned by our own crews.' },
        { t: 'Adjust and commission', d: 'Closers, interlocks, signage and contacts are tested before handover.' },
      ],
      faqs: [
        { q: 'What is the difference between a lead-lined door and an RF-shielded door?', a: 'A lead-lined door stops ionising radiation and is used for CT, PET-CT and X-ray rooms. An RF-shielded door keeps radio-frequency interference out of an MRI room and relies on continuous electrical contact around the leaf.' },
        { q: 'Can shielded doors be motorised?', a: 'Yes. We supply both manual and motorised doors, with interlocks or access control when the room requires them.' },
        { q: 'Do shielded doors need maintenance?', a: 'They benefit from periodic checks of seals, contact fingers, hinges and closers, because a door that no longer closes true can compromise the room’s shielding.' },
      ],
    },
    {
      id: 'mep',
      icon: 'cable',
      label: 'Healthcare MEP',
      full: 'Specialized MEP',
      short: 'MEP',
      summary: 'Mechanical, electrical and plumbing works engineered for imaging equipment — medical gases, earthing, EMI-aware routing and controlled-environment HVAC.',
      h1: 'Healthcare MEP contractor for imaging and clinical rooms',
      lead: 'Imaging equipment has MEP demands that a standard scope does not cover: dedicated earthing, EMI-aware cable routes, medical gases, and HVAC that holds tight temperature and humidity limits. We deliver them in step with the shielding, so every penetration is planned once.',
      image: null,
      rooms: ['MRI suites', 'CT and PET-CT rooms', 'X-ray rooms', 'Controlled clinical environments'],
      deliver: [
        'Medical gas pipeline systems: oxygen, medical air and vacuum',
        'Electrical infrastructure and earthing for imaging equipment',
        'EMI/RFI-aware cable routing and containment',
        'HVAC design and installation for controlled clinical environments',
        'Coordination with OEM installation teams during commissioning',
        'MEP shop drawings and as-built documentation',
      ],
      explainTitle: 'Why MEP and shielding belong together',
      explain: [
        'Every pipe, duct and cable that crosses a shielded wall is a potential leak in the shield. On an MRI suite it must pass through a waveguide or filter; in a lead-lined room it needs a lead-backed sleeve or box.',
        'When shielding and MEP are separate packages, those details are discovered late and fixed on site. Under one contractor they are drawn once, before anything is cut.',
      ],
      process: [
        { t: 'Agree loads and routes', d: 'We take heat loads, power and service requirements from the OEM and agree routes with the design team.' },
        { t: 'Plan every penetration', d: 'Each crossing of the shielded envelope is located, detailed and sealed on the drawings first.' },
        { t: 'Install and test', d: 'Services are installed, pressure-tested and balanced to the specified conditions.' },
        { t: 'Document', d: 'As-built drawings and test records are handed over with the room.' },
      ],
      faqs: [
        { q: 'What is a waveguide?', a: 'A short metal tube fitted through an MRI room’s RF shield. Its length relative to its diameter blocks radio-frequency signals, so a pipe or duct can pass through the wall without breaking the Faraday cage.' },
        { q: 'Why do imaging rooms need special HVAC?', a: 'Scanners give off significant heat and must run within manufacturer-specified temperature and humidity limits. The system also has to respect the shielding, with penetrations detailed and non-magnetic components inside an MRI room.' },
        { q: 'Does EGC install medical gas?', a: 'Yes — oxygen, medical air and vacuum pipeline systems form part of our specialised MEP scope.' },
      ],
    },
    {
      id: 'surfaces',
      icon: 'layers',
      label: 'Infection-control surfaces & joinery',
      full: 'Infection controlled surfaces & joinery',
      short: 'Surfaces',
      summary: 'Seamless, non-porous Corian solid surfaces and medical-grade joinery from our own factory, made for clinical cleaning protocols.',
      h1: 'Infection-control surfaces and Corian joinery for hospitals',
      lead: 'Everything that is touched, cleaned and disinfected in a clinical space comes out of our own Corian and joinery factory in Jeddah: seamless solid-surface counters, nurse stations, scrub sinks and medical-grade cabinetry.',
      image: 'corian-surfaces',
      imageAlt: 'Seamless Corian nurse station with integrated sink',
      rooms: ['Nurse stations and reception counters', 'Scrub and hand-wash sinks', 'Laboratory benches', 'Clinical cabinetry and storage', 'Wall cladding and panelling'],
      deliver: [
        'Corian and solid-surface clinical counters and vanities',
        'Seamless nurse stations and reception counters',
        'Antimicrobial wall panelling and cladding',
        'Medical-grade cabinetry and clinical storage joinery',
        'Laboratory and workstation surface fabrication',
        'Custom profiles engineered for infection-control cleaning protocols',
      ],
      explainTitle: 'Seamless is the point',
      explain: [
        'Joints, cracks and porous materials give contamination somewhere to hide. Solid surface is non-porous and its seams are bonded and sanded flush, so counters, upstands and sinks read as a single piece that can be wiped down end to end.',
        'Because we make the pieces ourselves, they are templated to the room, fabricated to tolerance and installed by the same team — with no gaps between a supplier’s drawing and the wall.',
      ],
      process: [
        { t: 'Template on site', d: 'We measure the finished room so every piece fits the wall as built.' },
        { t: 'Fabricate in the factory', d: 'CNC cutting, thermoforming and seaming in our Jeddah Corian and joinery workshop.' },
        { t: 'Install and join', d: 'Pieces are fixed, seams bonded and sinks integrated on site.' },
        { t: 'Polish and hand over', d: 'Surfaces are finished to the specified sheen and cleaned for use.' },
      ],
      faqs: [
        { q: 'What is Corian?', a: 'Corian is a brand of solid-surface material — a mineral-filled acrylic. It is non-porous, can be joined with invisible seams and can be formed around integrated sinks and coved edges.' },
        { q: 'Is solid surface a substitute for cleaning protocols?', a: 'No. It removes places where contamination can lodge, which makes cleaning more effective, but the hospital’s disinfection protocol still applies. Check disinfectant compatibility with the manufacturer’s guidance.' },
        { q: 'Can scratches be repaired on site?', a: 'Light marks in solid surface can usually be sanded and polished out on site, which is one reason it suits busy clinical counters.' },
      ],
    },
  ],
  ar: [
    {
      id: 'shielding',
      icon: 'shield',
      label: 'التدريع الإشعاعي والمغناطيسي',
      full: 'التدريع الإنشائي للإشعاع والمجال المغناطيسي',
      short: 'التدريع',
      summary: 'تبطين بالرصاص لغرف الأشعة المقطعية وPET-CT والأشعة السينية، وتدريع ضد الترددات الراديوية والمجال المغناطيسي لغرف الرنين — وفق مواصفات الشركة المصنِّعة والفيزيائي الإشعاعي.',
      h1: 'مقاول تدريع إشعاعي ومغناطيسي لغرف الرنين والأشعة في السعودية',
      lead: 'نبني الغلاف الواقي لغرف التشخيص والعلاج: تبطين بالرصاص ضد الإشعاع المؤيِّن، وتدريع ضد الترددات الراديوية (قفص فاراداي) والمجال المغناطيسي لغرف الرنين. كل طبقة تُنفَّذ وفق دليل تخطيط الموقع الصادر عن الشركة المصنِّعة وتقرير الفيزيائي المختص بالوقاية الإشعاعية.',
      image: 'hero-bg',
      imageAlt: 'فريق EGC أثناء تركيب ألواح التدريع في غرفة رنين مغناطيسي',
      rooms: ['غرف الرنين المغناطيسي', 'غرف الأشعة المقطعية', 'غرف PET-CT', 'غرف الأشعة السينية والتنظير الفلوري', 'غرف الطب النووي', 'غرف العلاج الإشعاعي'],
      deliver: [
        'غرف رنين مغناطيسي بتدريع ضد الترددات الراديوية (قفص فاراداي) والمجال المغناطيسي',
        'جدران وأسقف وأرضيات مبطنة بالرصاص لغرف الأشعة المقطعية وPET-CT والأشعة السينية',
        'غرف الطب النووي وغرف العلاج الإشعاعي',
        'نوافذ مراقبة من الزجاج الرصاصي ونوافذ مدرّعة ضد الترددات الراديوية',
        'تفاصيل تبطين متصل عند التقاطعات والصناديق ونقاط الاختراق',
        'تدريع تحديثي للغرف التشخيصية القائمة',
      ],
      explainTitle: 'مشكلتان مختلفتان، وتدريعان مختلفان',
      explain: [
        'الإشعاع المؤيِّن الصادر عن أجهزة الأشعة المقطعية وPET-CT والأشعة السينية تحجبه مادة كثيفة، وغالبًا الرصاص. ويحدد الفيزيائي المختص بالوقاية الإشعاعية السماكة المطلوبة لكل جدار وأرضية وسقف وباب ونافذة.',
        'أما الرنين المغناطيسي فلا يستخدم إشعاعًا مؤيِّنًا. وتُدرَّع غرفته ضد التداخل الراديوي بغلاف موصل متصل، وأحيانًا ضد المجال المغناطيسي المتسرب للخارج بصفائح من الفولاذ. ويحدد دليل تخطيط الموقع من الشركة المصنِّعة الأمرين معًا.',
      ],
      process: [
        { t: 'مراجعة المواصفات', d: 'نقرأ دليل تخطيط الموقع وتقرير التدريع من الفيزيائي جنبًا إلى جنب، ونحسم أي تعارض قبل إصدار المخططات.' },
        { t: 'تفصيل الغلاف الواقي', d: 'تُظهر مخططات التنفيذ كل طبقة تبطين وكل وصلة وتقاطع ونقطة اختراق، فلا يُرتجل شيء في الموقع.' },
        { t: 'التنفيذ والفحص', d: 'تركّب فرقنا التدريع بنفسها، ويُفحص اتصال الطبقات قبل أن تغطيه التشطيبات.' },
        { t: 'الاختبار والتسليم', d: 'ندعم اختبار توهين الترددات الراديوية أو المسح الإشعاعي، ثم نسلّم الغرفة لفريق التركيب التابع للشركة المصنِّعة.' },
      ],
      faqs: [
        { q: 'هل تحتاج غرفة الرنين المغناطيسي إلى رصاص؟', a: 'ليس للمغناطيس نفسه، فالرنين المغناطيسي لا يستخدم إشعاعًا مؤيِّنًا. تحتاج الغرفة إلى تدريع ضد الترددات الراديوية لمنع التداخل الخارجي عن الصورة، وأحيانًا إلى تدريع مغناطيسي. وقد يُطلب الرصاص إذا جاورت الغرفة غرفة أشعة سينية أو مقطعية.' },
        { q: 'من يحدد سماكة التبطين بالرصاص؟', a: 'فيزيائي مختص بالوقاية الإشعاعية، بناءً على حجم عمل الجهاز وطريقة إشغال الأماكن المجاورة وبعدها عن المصدر. وينفّذ المقاول وفق تقرير التدريع الناتج تمامًا.' },
        { q: 'هل يمكن إضافة تدريع لغرفة قائمة؟', a: 'نعم، مع مراعاة الهيكل الإنشائي ومراجعة الفيزيائي. والتدريع التحديثي شائع عند ترقية قسم إلى جهاز أحدث.' },
      ],
    },
    {
      id: 'doors',
      icon: 'door',
      label: 'الأبواب الطبية والتحكم بالدخول',
      full: 'الأبواب الطبية وأنظمة التحكم بالدخول',
      short: 'الأبواب',
      summary: 'أبواب مبطنة بالرصاص وأخرى مدرّعة ضد الترددات الراديوية، وأبواب انزلاقية محكمة الغلق، وأنظمة تحكم بالدخول — تُصنَّع وتُركَّب لعزل المناطق السريرية المتحكَّم بها.',
      h1: 'أبواب طبية مبطنة بالرصاص ومدرّعة ضد الترددات الراديوية في السعودية',
      lead: 'فعالية الغرفة المدرّعة تتوقف على أبوابها. نصنّع ونركّب أبوابًا مبطنة بالرصاص لغرف الأشعة المقطعية وPET-CT والأشعة السينية، وأبوابًا مدرّعة ضد الترددات الراديوية لغرف الرنين المغناطيسي، وأبوابًا انزلاقية محكمة الغلق للمناطق المتحكَّم بها — مع أنظمة قفل تبادلي وتحكم بالدخول عند الحاجة.',
      image: 'healthcare-xray',
      imageAlt: 'باب غرفة أشعة مبطن بالرصاص مع لوحة تحذير، من تنفيذ EGC',
      imagePosition: '85% 50%',
      rooms: ['غرف الرنين المغناطيسي', 'غرف الأشعة المقطعية وPET-CT', 'غرف الأشعة السينية والتنظير الفلوري', 'غرف العلاج الإشعاعي', 'المناطق السريرية المتحكَّم بها'],
      deliver: [
        'أبواب مبطنة بالرصاص للتدريع الإشعاعي، يدوية ومؤتمتة',
        'أبواب مدرّعة ضد الترددات الراديوية مدمجة في قفص فاراداي لغرفة الرنين',
        'أبواب انزلاقية محكمة الغلق للمناطق السريرية المتحكَّم بها',
        'دمج أنظمة التحكم بالدخول والقفل التبادلي لغرف الإشعاع',
        'تصنيع الضلفة والإطار وفق مواصفات معدات الشركة المصنِّعة',
        'التركيب الميداني والإحكام والتشغيل',
      ],
      explainTitle: 'لماذا تُعدّ الأبواب أضعف نقطة في التدريع عادةً',
      explain: [
        'الباب هو الجزء المتحرك الوحيد في الغلاف الواقي. يجب أن تتداخل ضلفة الباب المبطنة بالرصاص مع تبطين الجدار عند الإطار، ويجب أن يحافظ باب الترددات الراديوية على تلامس كهربائي متصل على محيطه بالكامل.',
        'وكلاهما يعتمد على ضبط الإطار بدقة عند بناء الجدار، ولذلك يُفضَّل أن يتولى مقاول واحد التنسيق بين حزمتي الباب والجدار.',
      ],
      process: [
        { t: 'مسح الفتحة', d: 'تُضبط الأطر وفق تركيب الجدار ليتطابق التبطين مع الباب بدقة.' },
        { t: 'التصنيع داخليًا', d: 'تُصنَّع الضلف والأطر والإكسسوارات وفق مواصفات الجهاز، لا تعديلًا على أبواب جاهزة.' },
        { t: 'التركيب والإحكام', d: 'تعلّق فرقنا الأبواب وتحكم عزلها وتضبط محاذاتها.' },
        { t: 'الضبط والتشغيل', d: 'تُختبر المغاليق والقفل التبادلي واللوحات الإرشادية وملامسات التوصيل قبل التسليم.' },
      ],
      faqs: [
        { q: 'ما الفرق بين الباب المبطن بالرصاص والباب المدرّع ضد الترددات الراديوية؟', a: 'الباب المبطن بالرصاص يحجب الإشعاع المؤيِّن ويُستخدم لغرف الأشعة المقطعية وPET-CT والأشعة السينية. أما باب الترددات الراديوية فيمنع التداخل الراديوي عن غرفة الرنين المغناطيسي، ويعتمد على تلامس كهربائي متصل حول الضلفة.' },
        { q: 'هل يمكن أتمتة الأبواب المدرّعة؟', a: 'نعم. نوفر أبوابًا يدوية ومؤتمتة، مع قفل تبادلي أو تحكم بالدخول عندما تتطلب الغرفة ذلك.' },
        { q: 'هل تحتاج الأبواب المدرّعة إلى صيانة؟', a: 'تستفيد من فحص دوري لموانع التسرب وأصابع التلامس والمفصلات والمغاليق، فالباب الذي لا يُغلق باستقامة قد يُضعف تدريع الغرفة.' },
      ],
    },
    {
      id: 'mep',
      icon: 'cable',
      label: 'الأعمال الكهروميكانيكية الطبية',
      full: 'الأعمال الكهروميكانيكية المتخصصة',
      short: 'الكهروميكانيكية',
      summary: 'أعمال ميكانيكية وكهربائية وسباكة مصممة لمعدات التصوير — غازات طبية وتأريض وتمديدات واعية بالتداخل الكهرومغناطيسي وتكييف للبيئات المتحكَّم بها.',
      h1: 'مقاول أعمال كهروميكانيكية للمنشآت الصحية وغرف التصوير',
      lead: 'لمعدات التصوير متطلبات كهروميكانيكية لا يغطيها النطاق المعتاد: تأريض مخصص، ومسارات كابلات واعية بالتداخل الكهرومغناطيسي، وغازات طبية، وتكييف يحافظ على حدود دقيقة للحرارة والرطوبة. ننفذها بالتوازي مع التدريع، فتُخطَّط كل نقطة اختراق مرة واحدة.',
      image: null,
      rooms: ['غرف الرنين المغناطيسي', 'غرف الأشعة المقطعية وPET-CT', 'غرف الأشعة السينية', 'البيئات السريرية المتحكَّم بها'],
      deliver: [
        'أنظمة خطوط الغازات الطبية: الأكسجين والهواء الطبي والشفط',
        'البنية الكهربائية والتأريض لمعدات التصوير',
        'تمديد واحتواء الكابلات بوعي للتداخل الكهرومغناطيسي والترددي',
        'تصميم وتركيب التكييف للبيئات السريرية المتحكَّم بها',
        'التنسيق مع فرق تركيب الشركة المصنِّعة أثناء التشغيل',
        'مخططات التنفيذ ومخططات ما بعد التنفيذ',
      ],
      explainTitle: 'لماذا يجب أن تعمل الأعمال الكهروميكانيكية والتدريع معًا',
      explain: [
        'كل أنبوب ومجرى وكابل يعبر جدارًا مدرّعًا هو ثغرة محتملة في الدرع. في غرفة الرنين يجب أن يمر عبر موجّه موجي أو مرشّح، وفي الغرفة المبطنة بالرصاص يحتاج إلى كم أو صندوق مبطن بالرصاص.',
        'عندما تكون حزمتا التدريع والأعمال الكهروميكانيكية منفصلتين تُكتشف هذه التفاصيل متأخرة وتُعالَج في الموقع. أما مع مقاول واحد فتُرسم مرة واحدة قبل أن يُقطع أي شيء.',
      ],
      process: [
        { t: 'الاتفاق على الأحمال والمسارات', d: 'نأخذ الأحمال الحرارية ومتطلبات الطاقة والخدمات من الشركة المصنِّعة ونتفق على المسارات مع فريق التصميم.' },
        { t: 'تخطيط كل نقطة اختراق', d: 'تُحدَّد كل نقطة عبور للغلاف المدرّع وتُفصَّل وتُحكَم على المخططات أولًا.' },
        { t: 'التركيب والاختبار', d: 'تُركَّب الخدمات وتُختبر ضغطيًا وتُوازَن وفق الظروف المحددة.' },
        { t: 'التوثيق', d: 'تُسلَّم مخططات ما بعد التنفيذ وسجلات الاختبار مع الغرفة.' },
      ],
      faqs: [
        { q: 'ما هو الموجّه الموجي (Waveguide)؟', a: 'أنبوب معدني قصير يُركَّب عبر درع الترددات الراديوية لغرفة الرنين. يحجب طوله بالنسبة إلى قطره الإشارات الراديوية، فيمر الأنبوب أو المجرى عبر الجدار دون كسر قفص فاراداي.' },
        { q: 'لماذا تحتاج غرف التصوير إلى تكييف خاص؟', a: 'تُصدر الأجهزة حرارة كبيرة ويجب أن تعمل ضمن حدود حرارة ورطوبة تحددها الشركة المصنِّعة. كما يجب أن يراعي النظام التدريع بتفاصيل نقاط الاختراق ومكونات غير مغناطيسية داخل غرفة الرنين.' },
        { q: 'هل تنفذ EGC الغازات الطبية؟', a: 'نعم، فأنظمة الأكسجين والهواء الطبي والشفط جزء من نطاق أعمالنا الكهروميكانيكية المتخصصة.' },
      ],
    },
    {
      id: 'surfaces',
      icon: 'layers',
      label: 'الأسطح والنجارة المقاومة للعدوى',
      full: 'الأسطح والنجارة المقاومة للعدوى',
      short: 'الأسطح',
      summary: 'أسطح كوريان صلبة متصلة وغير مسامية ونجارة طبية من مصنعنا، مصممة وفق بروتوكولات التنظيف السريري.',
      h1: 'أسطح كوريان ونجارة طبية مقاومة للعدوى للمستشفيات في السعودية',
      lead: 'كل ما يُلمس ويُنظَّف ويُعقَّم في المساحات السريرية يخرج من مصنع الكوريان والنجارة الخاص بنا في جدة: منضدات أسطح صلبة متصلة، ومحطات تمريض، ومغاسل جراحية، وخزائن طبية.',
      image: 'corian-surfaces',
      imageAlt: 'محطة تمريض من الكوريان بوصلات غير مرئية ومغسلة مدمجة',
      rooms: ['محطات التمريض ومكاتب الاستقبال', 'مغاسل الجراحة وغسل اليدين', 'طاولات المختبرات', 'الخزائن والتخزين السريري', 'كسوة الجدران والألواح'],
      deliver: [
        'منضدات ومغاسل سريرية من الكوريان والأسطح الصلبة',
        'محطات تمريض ومكاتب استقبال متصلة بلا فواصل',
        'ألواح وكسوات جدارية مضادة للميكروبات',
        'خزائن طبية ونجارة تخزين سريرية',
        'تصنيع أسطح المختبرات ومحطات العمل',
        'مقاطع مخصصة مصممة وفق بروتوكولات التنظيف ومكافحة العدوى',
      ],
      explainTitle: 'الاتصال بلا فواصل هو الهدف',
      explain: [
        'الفواصل والشقوق والمواد المسامية تمنح التلوث مكانًا يختبئ فيه. السطح الصلب غير مسامي، وتُلصق وصلاته وتُصنفر حتى تتسوى، فتبدو المنضدات والحواف والمغاسل قطعة واحدة يمكن مسحها من طرفها إلى طرفها.',
        'ولأننا نصنع القطع بأنفسنا فإنها تؤخذ مقاساتها من الغرفة نفسها وتُصنَّع بدقة وتُركَّب بالفريق ذاته، فلا فجوة بين مخطط المورد والجدار.',
      ],
      process: [
        { t: 'أخذ المقاسات في الموقع', d: 'نقيس الغرفة بعد اكتمالها لتناسب كل قطعة الجدار كما نُفِّذ.' },
        { t: 'التصنيع في المصنع', d: 'قطع بتقنية CNC وتشكيل حراري ولحام وصلات في ورشة الكوريان والنجارة بجدة.' },
        { t: 'التركيب والوصل', d: 'تُثبَّت القطع وتُلصق الوصلات وتُدمج المغاسل في الموقع.' },
        { t: 'التلميع والتسليم', d: 'تُشطَّب الأسطح بدرجة اللمعان المحددة وتُنظَّف للاستخدام.' },
      ],
      faqs: [
        { q: 'ما هو الكوريان؟', a: 'الكوريان علامة تجارية لمادة الأسطح الصلبة — أكريليك مدعّم بمعادن. وهو غير مسامي ويمكن وصله بوصلات غير مرئية وتشكيله حول مغاسل مدمجة وحواف مقوّسة.' },
        { q: 'هل يغني السطح الصلب عن بروتوكولات التنظيف؟', a: 'لا. فهو يزيل الأماكن التي قد يعلق فيها التلوث فيجعل التنظيف أكثر فعالية، لكن يظل بروتوكول التعقيم في المستشفى ساريًا. تحقق من توافق المطهرات مع إرشادات الشركة المصنِّعة.' },
        { q: 'هل يمكن إصلاح الخدوش في الموقع؟', a: 'يمكن عادةً تنعيم العلامات الخفيفة في السطح الصلب وتلميعها في الموقع، وهذا من أسباب ملاءمته للمنضدات السريرية كثيرة الاستخدام.' },
      ],
    },
  ],
};
