export const SOFTWARE = {
  en: {
    heroOverline: 'Software Engineering',
    heroTitle: 'Built by people who understand hospitals and job sites.',
    heroSubtitle: "EGC's newest sector builds the software layer for the environments and operations we already know best — healthcare information systems, and the ERP and project tooling that runs a contracting business — engineered around Saudi regulatory requirements from day one.",
    pillars: [
      {
        id: 'his-ris',
        num: '01',
        label: 'HIS & RIS',
        tag: 'Hospital & Radiology Information Systems',
        desc: "Hospital Information Systems and Radiology Information Systems for the facilities EGC builds — a natural extension of understanding the rooms these systems run in, not just the software layered on top.",
        points: [
          'Patient scheduling and department workflow',
          'Radiology and imaging workflow integration',
          'Reporting and clinical documentation modules',
          'Integration with imaging equipment data systems',
        ],
      },
      {
        id: 'pims',
        num: '02',
        label: 'PIMS',
        tag: 'Patient Information Management Systems',
        desc: 'Patient records and information management systems built for accuracy, auditability, and Saudi data-protection requirements.',
        points: [
          'Patient record management and history tracking',
          'Role-based access and audit trails',
          'Saudi PDPL-aligned data handling',
        ],
      },
      {
        id: 'erp',
        num: '03',
        label: 'ERP & Managerial Software',
        tag: 'Built for KSA Regulatory Compliance',
        desc: 'Enterprise resource planning and managerial software engineered around Saudi compliance requirements from the ground up — not retrofitted after the fact.',
        points: [
          'ZATCA e-invoicing (Fatoora) compliance',
          'GOSI and Wage Protection System (WPS) integration',
          'Saudi PDPL-aligned data handling',
          'Finance, procurement, HR and operations modules',
        ],
      },
      {
        id: 'pm-platforms',
        num: '04',
        label: 'Construction & Project Management Platforms',
        tag: 'Procore-Style Project Tooling',
        desc: "Project and construction management platforms — credible because EGC runs its own contracting operations on the same kind of tooling it builds for clients.",
        points: [
          'Project scheduling and site documentation',
          'RFI, submittal, and change-order tracking',
          'Vendor and supplier coordination workflows',
        ],
      },
      {
        id: 'websites',
        num: '05',
        label: 'Client-Facing Websites',
        tag: 'Web Design & Development',
        desc: 'Websites designed and built for clients who need a technical partner that also understands compliance and local hosting requirements.',
        points: [
          'Bilingual (Arabic/English) website design and build',
          'Content and CMS integration',
          'SEO and technical performance foundations',
        ],
      },
    ],
    complianceTitle: 'Engineered for Saudi compliance, not bolted on afterward.',
    complianceSubtitle: 'Every system we build accounts for the regulatory environment it will run in.',
    complianceItems: [
      { code: 'ZATCA', name: 'E-Invoicing (Fatoora)', desc: 'Phase 1 & 2 e-invoicing compliance built into financial modules from the start.' },
      { code: 'GOSI / WPS', name: 'Wage Protection System', desc: 'Payroll and HR modules aligned with GOSI and Wage Protection System reporting requirements.' },
      { code: 'PDPL', name: 'Personal Data Protection Law', desc: "Data handling, storage, and access controls designed around Saudi Arabia's PDPL requirements." },
    ],
    ctaTitle: 'Have a system that needs building?',
    ctaSubtitle: 'Whether it\'s a hospital information system, an ERP rollout, or a client-facing website — talk to our software engineering team.',
  },
  ar: {
    heroOverline: 'هندسة البرمجيات',
    heroTitle: 'برمجيات يبنيها من يفهم المستشفيات ومواقع العمل.',
    heroSubtitle: 'أحدث قطاعات EGC يبني الطبقة البرمجية للبيئات والعمليات التي نتقنها بالفعل — أنظمة المعلومات الطبية، وبرمجيات تخطيط الموارد وأدوات إدارة المشاريع التي تُشغّل شركة مقاولات — مصممة وفق المتطلبات التنظيمية السعودية منذ اليوم الأول.',
    pillars: [
      {
        id: 'his-ris',
        num: '01',
        label: 'أنظمة المستشفيات والأشعة',
        tag: 'HIS & RIS',
        desc: 'أنظمة معلومات المستشفيات وأنظمة معلومات الأشعة للمنشآت التي تبنيها EGC — امتداد طبيعي لفهم الغرف التي تعمل بها هذه الأنظمة، وليس فقط طبقة البرمجيات المضافة فوقها.',
        points: [
          'جدولة المرضى وسير العمل بالأقسام',
          'تكامل سير عمل الأشعة والتصوير',
          'وحدات التقارير والتوثيق السريري',
          'التكامل مع أنظمة بيانات معدات التصوير',
        ],
      },
      {
        id: 'pims',
        num: '02',
        label: 'أنظمة إدارة معلومات المرضى',
        tag: 'PIMS',
        desc: 'أنظمة سجلات وإدارة معلومات المرضى مصممة للدقة وقابلية التدقيق والتوافق مع متطلبات حماية البيانات السعودية.',
        points: [
          'إدارة سجلات المرضى وتتبع التاريخ المرضي',
          'صلاحيات وصول قائمة على الأدوار وسجلات تدقيق',
          'معالجة بيانات متوافقة مع نظام حماية البيانات الشخصية',
        ],
      },
      {
        id: 'erp',
        num: '03',
        label: 'تخطيط موارد المؤسسات والبرمجيات الإدارية',
        tag: 'ERP',
        desc: 'برمجيات تخطيط موارد المؤسسات والإدارة مصممة وفق متطلبات الامتثال السعودية منذ التأسيس — لا تُضاف لاحقًا.',
        points: [
          'التوافق مع الفوترة الإلكترونية لهيئة الزكاة والضريبة والجمارك (فاتورة)',
          'التكامل مع التأمينات الاجتماعية ونظام حماية الأجور',
          'معالجة بيانات متوافقة مع نظام حماية البيانات الشخصية',
          'وحدات المالية والمشتريات والموارد البشرية والعمليات',
        ],
      },
      {
        id: 'pm-platforms',
        num: '04',
        label: 'منصات إدارة الإنشاءات والمشاريع',
        tag: 'أدوات مشابهة لـ Procore',
        desc: 'منصات إدارة المشاريع والإنشاءات — تكتسب مصداقيتها من كون EGC تُشغّل عملياتها الخاصة بذات نوع الأدوات التي تبنيها لعملائها.',
        points: [
          'جدولة المشاريع وتوثيق الموقع',
          'تتبع طلبات المعلومات والمستندات وأوامر التغيير',
          'سير عمل التنسيق مع الموردين والمقاولين',
        ],
      },
      {
        id: 'websites',
        num: '05',
        label: 'مواقع إلكترونية للعملاء',
        tag: 'تصميم وتطوير الويب',
        desc: 'مواقع إلكترونية مصممة ومطورة للعملاء الذين يحتاجون شريكًا تقنيًا يفهم أيضًا متطلبات الامتثال والاستضافة المحلية.',
        points: [
          'تصميم وتطوير مواقع ثنائية اللغة (عربي/إنجليزي)',
          'تكامل إدارة المحتوى',
          'أسس تحسين محركات البحث والأداء التقني',
        ],
      },
    ],
    complianceTitle: 'مصممة للامتثال السعودي منذ البداية، لا تُضاف لاحقًا.',
    complianceSubtitle: 'كل نظام نبنيه يأخذ في الحسبان البيئة التنظيمية التي سيعمل ضمنها.',
    complianceItems: [
      { code: 'ZATCA', name: 'الفوترة الإلكترونية (فاتورة)', desc: 'توافق مع المرحلتين الأولى والثانية للفوترة الإلكترونية مدمج في الوحدات المالية منذ البداية.' },
      { code: 'GOSI / WPS', name: 'نظام حماية الأجور', desc: 'وحدات الرواتب والموارد البشرية متوافقة مع متطلبات التأمينات الاجتماعية ونظام حماية الأجور.' },
      { code: 'PDPL', name: 'نظام حماية البيانات الشخصية', desc: 'معالجة البيانات وتخزينها وضوابط الوصول إليها مصممة وفق متطلبات نظام حماية البيانات الشخصية السعودي.' },
    ],
    ctaTitle: 'لديك نظام يحتاج إلى تطوير؟',
    ctaSubtitle: 'سواء كان نظام معلومات مستشفى، أو تطبيق تخطيط موارد المؤسسات، أو موقعًا إلكترونيًا للعملاء — تواصل مع فريق هندسة البرمجيات لدينا.',
  },
};
