/* Shared strings reused across many components (nav, footer, buttons,
 * breadcrumbs, locale switcher) — page-specific prose lives in each page's
 * own copy module instead of here. */
export const UI = {
  en: {
    home: 'Home',
    skipToContent: 'Skip to content',
    switchLocaleLabel: 'العربية',
    switchLocaleTo: 'ar',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    sectors: 'Sectors',
    sectorHealthcare: 'Healthcare Construction',
    sectorHealthcareTag: 'Structural shielding, doors, MEP & surfaces',
    sectorManufacturing: 'Manufacturing',
    sectorManufacturingTag: 'Wood, Corian & steel factories',
    sectorSoftware: 'Software Engineering',
    sectorSoftwareTag: 'HIS/RIS, ERP & KSA-compliant systems',
    contactUs: 'Contact Us',
    learnMore: 'Learn more',
    viewAll: 'View all',
    readMore: 'Read more',
    getInTouch: 'Get in touch',
    callUs: 'Call us',
    discussProject: 'Discuss a project',
    footerCompany: 'Company',
    footerAbout: 'About Us',
    footerWhatWeBuild: 'What We Build',
    footerManufacturing: 'Manufacturing',
    footerSoftware: 'Software Engineering',
    footerProjects: 'Projects',
    footerTeam: 'Team',
    footerWorkWithUs: 'Work With Us',
    footerCareers: 'Careers',
    footerSuppliers: 'Suppliers',
    footerContact: 'Contact Us',
    footerInstall: 'Install App',
    footerContactHeading: 'Contact',
    footerSupplierPortal: 'Supplier Portal Login',
    footerRights: 'All rights reserved.',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms & Conditions',
    footerCrLabel: 'CR No.',
    devBanner: 'This website is currently under development — some sections and information may not be fully up to date.',
    devBannerDismiss: 'Dismiss notice',
  },
  ar: {
    home: 'الرئيسية',
    skipToContent: 'تخطَّ إلى المحتوى',
    switchLocaleLabel: 'English',
    switchLocaleTo: 'en',
    menuOpen: 'فتح القائمة',
    menuClose: 'إغلاق القائمة',
    sectors: 'القطاعات',
    sectorHealthcare: 'الإنشاءات الطبية',
    sectorHealthcareTag: 'التدريع الإنشائي، الأبواب، الأعمال الكهروميكانيكية والأسطح',
    sectorManufacturing: 'التصنيع',
    sectorManufacturingTag: 'مصانع الخشب والكوريان والصلب',
    sectorSoftware: 'هندسة البرمجيات',
    sectorSoftwareTag: 'أنظمة المستشفيات والأشعة وتخطيط الموارد المتوافقة سعوديًا',
    contactUs: 'تواصل معنا',
    learnMore: 'اعرف المزيد',
    viewAll: 'عرض الكل',
    readMore: 'اقرأ المزيد',
    getInTouch: 'تواصل معنا',
    callUs: 'اتصل بنا',
    discussProject: 'ناقش مشروعك',
    footerCompany: 'الشركة',
    footerAbout: 'من نحن',
    footerWhatWeBuild: 'ماذا نبني',
    footerManufacturing: 'التصنيع',
    footerSoftware: 'هندسة البرمجيات',
    footerProjects: 'المشاريع',
    footerTeam: 'الفريق',
    footerWorkWithUs: 'اعمل معنا',
    footerCareers: 'الوظائف',
    footerSuppliers: 'الموردون',
    footerContact: 'تواصل معنا',
    footerInstall: 'تثبيت التطبيق',
    footerContactHeading: 'التواصل',
    footerSupplierPortal: 'دخول بوابة الموردين',
    footerRights: 'جميع الحقوق محفوظة.',
    footerPrivacy: 'سياسة الخصوصية',
    footerTerms: 'الشروط والأحكام',
    footerCrLabel: 'رقم السجل التجاري',
    devBanner: 'هذا الموقع قيد التطوير حاليًا — قد لا تكون بعض الأقسام والمعلومات محدثة بالكامل.',
    devBannerDismiss: 'إغلاق التنبيه',
  },
};
