/* Shared interface strings (header, footer, buttons, section labels). */
export const UI = {
  en: {
    skipToContent: 'Skip to content',
    home: 'Home',
    menuOpen: 'Open menu',
    menuClose: 'Close menu',
    primaryNav: 'Primary navigation',
    switchLabel: 'العربية',
    switchAria: 'Switch to Arabic',
    switchLang: 'ar',
    contactUs: 'Contact us',
    requestProposal: 'Request a proposal',
    soon: 'Soon',
    learnMore: 'Learn more',
    relatedDisciplines: 'Related disciplines',
    relatedServices: 'Related services',
    rooms: 'Where it is used',
    deliver: 'What we deliver',
    howWeWork: 'How we deliver it',
    viewDiscipline: 'View discipline',
    callUs: 'Call us',
    emailUs: 'Email us',
    sendEmail: 'Send by email',
    footerTagline: 'Healthcare contractor, Wood & Corian factory and software engineering, headquartered in Jeddah.',
    footerCompany: 'Company',
    footerServices: 'Services',
    footerAllServices: 'All services',
    footerAbout: 'About us',
    footerHub: 'Healthcare contractor',
    footerManufacturing: 'Manufacturing',
    footerSoftware: 'Software engineering',
    footerProjects: 'Projects',
    footerCareers: 'Careers',
    footerSuppliers: 'Suppliers',
    footerContact: 'Contact us',
    footerInstall: 'Install the app',
    footerContactHeading: 'Contact',
    footerSupplierPortal: 'Supplier portal login',
    footerRights: 'All rights reserved.',
    footerPrivacy: 'Privacy policy',
    footerTerms: 'Terms & conditions',
    footerCr: 'CR No.',
    devBanner: 'This website is under active development. Some project information is illustrative and will be updated.',
    devBannerDismiss: 'Dismiss notice',
    notFoundTitle: 'This page does not exist',
    notFoundText: 'The address may have changed. Try the home page or one of the sections below.',
    notFoundHome: 'Back to home',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    hours: 'Hours',
  },
  ar: {
    skipToContent: 'تخطَّ إلى المحتوى',
    home: 'الرئيسية',
    menuOpen: 'فتح القائمة',
    menuClose: 'إغلاق القائمة',
    primaryNav: 'القائمة الرئيسية',
    switchLabel: 'English',
    switchAria: 'التبديل إلى الإنجليزية',
    switchLang: 'en',
    contactUs: 'تواصل معنا',
    requestProposal: 'اطلب عرضًا',
    soon: 'قريبًا',
    learnMore: 'اعرف المزيد',
    relatedDisciplines: 'تخصصات ذات صلة',
    relatedServices: 'خدمات ذات صلة',
    rooms: 'أين يُستخدم',
    deliver: 'ما نقدّمه',
    howWeWork: 'كيف ننفذه',
    viewDiscipline: 'عرض التخصص',
    callUs: 'اتصل بنا',
    emailUs: 'راسلنا',
    sendEmail: 'إرسال عبر البريد',
    footerTagline: 'مقاول مشاريع صحية ومصنع للخشب والكوريان وهندسة برمجيات، مقرها جدة.',
    footerCompany: 'الشركة',
    footerServices: 'الخدمات',
    footerAllServices: 'جميع الخدمات',
    footerAbout: 'من نحن',
    footerHub: 'مقاول مشاريع صحية',
    footerManufacturing: 'التصنيع',
    footerSoftware: 'هندسة البرمجيات',
    footerProjects: 'المشاريع',
    footerCareers: 'الوظائف',
    footerSuppliers: 'الموردون',
    footerContact: 'تواصل معنا',
    footerInstall: 'ثبّت التطبيق',
    footerContactHeading: 'التواصل',
    footerSupplierPortal: 'دخول بوابة الموردين',
    footerRights: 'جميع الحقوق محفوظة.',
    footerPrivacy: 'سياسة الخصوصية',
    footerTerms: 'الشروط والأحكام',
    footerCr: 'السجل التجاري',
    devBanner: 'الموقع قيد التطوير النشط. بعض معلومات المشاريع توضيحية وسيجري تحديثها.',
    devBannerDismiss: 'إغلاق التنبيه',
    notFoundTitle: 'هذه الصفحة غير موجودة',
    notFoundText: 'ربما تغيّر العنوان. جرّب الصفحة الرئيسية أو أحد الأقسام أدناه.',
    notFoundHome: 'العودة إلى الرئيسية',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    hours: 'ساعات العمل',
  },
};
